// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19
);


output   ap_ready;
input  [31:0] data_0_V_read;
input  [31:0] data_1_V_read;
input  [31:0] data_2_V_read;
input  [31:0] data_3_V_read;
input  [31:0] data_4_V_read;
input  [31:0] data_5_V_read;
input  [31:0] data_6_V_read;
input  [31:0] data_7_V_read;
input  [31:0] data_8_V_read;
input  [31:0] data_9_V_read;
input  [31:0] data_10_V_read;
input  [31:0] data_11_V_read;
input  [31:0] data_12_V_read;
input  [31:0] data_13_V_read;
input  [31:0] data_14_V_read;
input  [31:0] data_15_V_read;
input  [31:0] data_16_V_read;
input  [31:0] data_17_V_read;
input  [31:0] data_18_V_read;
input  [31:0] data_19_V_read;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;
output  [63:0] ap_return_8;
output  [63:0] ap_return_9;
output  [63:0] ap_return_10;
output  [63:0] ap_return_11;
output  [63:0] ap_return_12;
output  [63:0] ap_return_13;
output  [63:0] ap_return_14;
output  [63:0] ap_return_15;
output  [63:0] ap_return_16;
output  [63:0] ap_return_17;
output  [63:0] ap_return_18;
output  [63:0] ap_return_19;

wire   [49:0] res_0_V_write_assign_fu_184_p3;
wire   [49:0] res_1_V_write_assign_fu_196_p3;
wire   [49:0] res_2_V_write_assign_fu_208_p3;
wire   [49:0] res_3_V_write_assign_fu_220_p3;
wire   [49:0] res_4_V_write_assign_fu_232_p3;
wire   [49:0] res_5_V_write_assign_fu_244_p3;
wire   [49:0] res_6_V_write_assign_fu_256_p3;
wire   [49:0] res_7_V_write_assign_fu_268_p3;
wire   [49:0] res_8_V_write_assign_fu_280_p3;
wire   [49:0] res_9_V_write_assign_fu_292_p3;
wire   [49:0] res_10_V_write_assign_fu_304_p3;
wire   [49:0] res_11_V_write_assign_fu_316_p3;
wire   [49:0] res_12_V_write_assign_fu_328_p3;
wire   [49:0] res_13_V_write_assign_fu_340_p3;
wire   [49:0] res_14_V_write_assign_fu_352_p3;
wire   [49:0] res_15_V_write_assign_fu_364_p3;
wire   [49:0] res_16_V_write_assign_fu_376_p3;
wire   [49:0] res_17_V_write_assign_fu_388_p3;
wire   [49:0] res_18_V_write_assign_fu_400_p3;
wire   [49:0] res_19_V_write_assign_fu_412_p3;
wire  signed [63:0] sext_ln728_fu_192_p1;
wire  signed [63:0] sext_ln728_1_fu_204_p1;
wire  signed [63:0] sext_ln728_2_fu_216_p1;
wire  signed [63:0] sext_ln728_3_fu_228_p1;
wire  signed [63:0] sext_ln728_4_fu_240_p1;
wire  signed [63:0] sext_ln728_5_fu_252_p1;
wire  signed [63:0] sext_ln728_6_fu_264_p1;
wire  signed [63:0] sext_ln728_7_fu_276_p1;
wire  signed [63:0] sext_ln728_8_fu_288_p1;
wire  signed [63:0] sext_ln728_9_fu_300_p1;
wire  signed [63:0] sext_ln728_10_fu_312_p1;
wire  signed [63:0] sext_ln728_11_fu_324_p1;
wire  signed [63:0] sext_ln728_12_fu_336_p1;
wire  signed [63:0] sext_ln728_13_fu_348_p1;
wire  signed [63:0] sext_ln728_14_fu_360_p1;
wire  signed [63:0] sext_ln728_15_fu_372_p1;
wire  signed [63:0] sext_ln728_16_fu_384_p1;
wire  signed [63:0] sext_ln728_17_fu_396_p1;
wire  signed [63:0] sext_ln728_18_fu_408_p1;
wire  signed [63:0] sext_ln728_19_fu_420_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln728_fu_192_p1;

assign ap_return_1 = sext_ln728_1_fu_204_p1;

assign ap_return_10 = sext_ln728_10_fu_312_p1;

assign ap_return_11 = sext_ln728_11_fu_324_p1;

assign ap_return_12 = sext_ln728_12_fu_336_p1;

assign ap_return_13 = sext_ln728_13_fu_348_p1;

assign ap_return_14 = sext_ln728_14_fu_360_p1;

assign ap_return_15 = sext_ln728_15_fu_372_p1;

assign ap_return_16 = sext_ln728_16_fu_384_p1;

assign ap_return_17 = sext_ln728_17_fu_396_p1;

assign ap_return_18 = sext_ln728_18_fu_408_p1;

assign ap_return_19 = sext_ln728_19_fu_420_p1;

assign ap_return_2 = sext_ln728_2_fu_216_p1;

assign ap_return_3 = sext_ln728_3_fu_228_p1;

assign ap_return_4 = sext_ln728_4_fu_240_p1;

assign ap_return_5 = sext_ln728_5_fu_252_p1;

assign ap_return_6 = sext_ln728_6_fu_264_p1;

assign ap_return_7 = sext_ln728_7_fu_276_p1;

assign ap_return_8 = sext_ln728_8_fu_288_p1;

assign ap_return_9 = sext_ln728_9_fu_300_p1;

assign res_0_V_write_assign_fu_184_p3 = {{data_0_V_read}, {18'd0}};

assign res_10_V_write_assign_fu_304_p3 = {{data_10_V_read}, {18'd0}};

assign res_11_V_write_assign_fu_316_p3 = {{data_11_V_read}, {18'd0}};

assign res_12_V_write_assign_fu_328_p3 = {{data_12_V_read}, {18'd0}};

assign res_13_V_write_assign_fu_340_p3 = {{data_13_V_read}, {18'd0}};

assign res_14_V_write_assign_fu_352_p3 = {{data_14_V_read}, {18'd0}};

assign res_15_V_write_assign_fu_364_p3 = {{data_15_V_read}, {18'd0}};

assign res_16_V_write_assign_fu_376_p3 = {{data_16_V_read}, {18'd0}};

assign res_17_V_write_assign_fu_388_p3 = {{data_17_V_read}, {18'd0}};

assign res_18_V_write_assign_fu_400_p3 = {{data_18_V_read}, {18'd0}};

assign res_19_V_write_assign_fu_412_p3 = {{data_19_V_read}, {18'd0}};

assign res_1_V_write_assign_fu_196_p3 = {{data_1_V_read}, {18'd0}};

assign res_2_V_write_assign_fu_208_p3 = {{data_2_V_read}, {18'd0}};

assign res_3_V_write_assign_fu_220_p3 = {{data_3_V_read}, {18'd0}};

assign res_4_V_write_assign_fu_232_p3 = {{data_4_V_read}, {18'd0}};

assign res_5_V_write_assign_fu_244_p3 = {{data_5_V_read}, {18'd0}};

assign res_6_V_write_assign_fu_256_p3 = {{data_6_V_read}, {18'd0}};

assign res_7_V_write_assign_fu_268_p3 = {{data_7_V_read}, {18'd0}};

assign res_8_V_write_assign_fu_280_p3 = {{data_8_V_read}, {18'd0}};

assign res_9_V_write_assign_fu_292_p3 = {{data_9_V_read}, {18'd0}};

assign sext_ln728_10_fu_312_p1 = $signed(res_10_V_write_assign_fu_304_p3);

assign sext_ln728_11_fu_324_p1 = $signed(res_11_V_write_assign_fu_316_p3);

assign sext_ln728_12_fu_336_p1 = $signed(res_12_V_write_assign_fu_328_p3);

assign sext_ln728_13_fu_348_p1 = $signed(res_13_V_write_assign_fu_340_p3);

assign sext_ln728_14_fu_360_p1 = $signed(res_14_V_write_assign_fu_352_p3);

assign sext_ln728_15_fu_372_p1 = $signed(res_15_V_write_assign_fu_364_p3);

assign sext_ln728_16_fu_384_p1 = $signed(res_16_V_write_assign_fu_376_p3);

assign sext_ln728_17_fu_396_p1 = $signed(res_17_V_write_assign_fu_388_p3);

assign sext_ln728_18_fu_408_p1 = $signed(res_18_V_write_assign_fu_400_p3);

assign sext_ln728_19_fu_420_p1 = $signed(res_19_V_write_assign_fu_412_p3);

assign sext_ln728_1_fu_204_p1 = $signed(res_1_V_write_assign_fu_196_p3);

assign sext_ln728_2_fu_216_p1 = $signed(res_2_V_write_assign_fu_208_p3);

assign sext_ln728_3_fu_228_p1 = $signed(res_3_V_write_assign_fu_220_p3);

assign sext_ln728_4_fu_240_p1 = $signed(res_4_V_write_assign_fu_232_p3);

assign sext_ln728_5_fu_252_p1 = $signed(res_5_V_write_assign_fu_244_p3);

assign sext_ln728_6_fu_264_p1 = $signed(res_6_V_write_assign_fu_256_p3);

assign sext_ln728_7_fu_276_p1 = $signed(res_7_V_write_assign_fu_268_p3);

assign sext_ln728_8_fu_288_p1 = $signed(res_8_V_write_assign_fu_280_p3);

assign sext_ln728_9_fu_300_p1 = $signed(res_9_V_write_assign_fu_292_p3);

assign sext_ln728_fu_192_p1 = $signed(res_0_V_write_assign_fu_184_p3);

endmodule //linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s
