// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config3_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);


output   ap_ready;
input  [22:0] data_0_V_read;
input  [22:0] data_1_V_read;
input  [22:0] data_2_V_read;
input  [22:0] data_3_V_read;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;

wire   [51:0] res_0_V_write_assign_fu_56_p3;
wire   [51:0] res_1_V_write_assign_fu_68_p3;
wire   [51:0] res_2_V_write_assign_fu_80_p3;
wire   [51:0] res_3_V_write_assign_fu_92_p3;
wire  signed [63:0] sext_ln728_fu_64_p1;
wire  signed [63:0] sext_ln728_19_fu_76_p1;
wire  signed [63:0] sext_ln728_20_fu_88_p1;
wire  signed [63:0] sext_ln728_21_fu_100_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln728_fu_64_p1;

assign ap_return_1 = sext_ln728_19_fu_76_p1;

assign ap_return_2 = sext_ln728_20_fu_88_p1;

assign ap_return_3 = sext_ln728_21_fu_100_p1;

assign res_0_V_write_assign_fu_56_p3 = {{data_0_V_read}, {29'd0}};

assign res_1_V_write_assign_fu_68_p3 = {{data_1_V_read}, {29'd0}};

assign res_2_V_write_assign_fu_80_p3 = {{data_2_V_read}, {29'd0}};

assign res_3_V_write_assign_fu_92_p3 = {{data_3_V_read}, {29'd0}};

assign sext_ln728_19_fu_76_p1 = $signed(res_1_V_write_assign_fu_68_p3);

assign sext_ln728_20_fu_88_p1 = $signed(res_2_V_write_assign_fu_80_p3);

assign sext_ln728_21_fu_100_p1 = $signed(res_3_V_write_assign_fu_92_p3);

assign sext_ln728_fu_64_p1 = $signed(res_0_V_write_assign_fu_56_p3);

endmodule //linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config3_s
