// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config6_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


output   ap_ready;
input  [22:0] data_0_V_read;
input  [22:0] data_1_V_read;
input  [22:0] data_2_V_read;
input  [22:0] data_3_V_read;
input  [22:0] data_4_V_read;
input  [22:0] data_5_V_read;
input  [22:0] data_6_V_read;
input  [22:0] data_7_V_read;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;

wire   [51:0] res_0_V_write_assign_fu_88_p3;
wire   [51:0] res_1_V_write_assign_fu_100_p3;
wire   [51:0] res_2_V_write_assign_fu_112_p3;
wire   [51:0] res_3_V_write_assign_fu_124_p3;
wire   [51:0] res_4_V_write_assign_fu_136_p3;
wire   [51:0] res_5_V_write_assign_fu_148_p3;
wire   [51:0] res_6_V_write_assign_fu_160_p3;
wire   [51:0] res_7_V_write_assign_fu_172_p3;
wire  signed [63:0] sext_ln728_fu_96_p1;
wire  signed [63:0] sext_ln728_12_fu_108_p1;
wire  signed [63:0] sext_ln728_13_fu_120_p1;
wire  signed [63:0] sext_ln728_14_fu_132_p1;
wire  signed [63:0] sext_ln728_15_fu_144_p1;
wire  signed [63:0] sext_ln728_16_fu_156_p1;
wire  signed [63:0] sext_ln728_17_fu_168_p1;
wire  signed [63:0] sext_ln728_18_fu_180_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln728_fu_96_p1;

assign ap_return_1 = sext_ln728_12_fu_108_p1;

assign ap_return_2 = sext_ln728_13_fu_120_p1;

assign ap_return_3 = sext_ln728_14_fu_132_p1;

assign ap_return_4 = sext_ln728_15_fu_144_p1;

assign ap_return_5 = sext_ln728_16_fu_156_p1;

assign ap_return_6 = sext_ln728_17_fu_168_p1;

assign ap_return_7 = sext_ln728_18_fu_180_p1;

assign res_0_V_write_assign_fu_88_p3 = {{data_0_V_read}, {29'd0}};

assign res_1_V_write_assign_fu_100_p3 = {{data_1_V_read}, {29'd0}};

assign res_2_V_write_assign_fu_112_p3 = {{data_2_V_read}, {29'd0}};

assign res_3_V_write_assign_fu_124_p3 = {{data_3_V_read}, {29'd0}};

assign res_4_V_write_assign_fu_136_p3 = {{data_4_V_read}, {29'd0}};

assign res_5_V_write_assign_fu_148_p3 = {{data_5_V_read}, {29'd0}};

assign res_6_V_write_assign_fu_160_p3 = {{data_6_V_read}, {29'd0}};

assign res_7_V_write_assign_fu_172_p3 = {{data_7_V_read}, {29'd0}};

assign sext_ln728_12_fu_108_p1 = $signed(res_1_V_write_assign_fu_100_p3);

assign sext_ln728_13_fu_120_p1 = $signed(res_2_V_write_assign_fu_112_p3);

assign sext_ln728_14_fu_132_p1 = $signed(res_3_V_write_assign_fu_124_p3);

assign sext_ln728_15_fu_144_p1 = $signed(res_4_V_write_assign_fu_136_p3);

assign sext_ln728_16_fu_156_p1 = $signed(res_5_V_write_assign_fu_148_p3);

assign sext_ln728_17_fu_168_p1 = $signed(res_6_V_write_assign_fu_160_p3);

assign sext_ln728_18_fu_180_p1 = $signed(res_7_V_write_assign_fu_172_p3);

assign sext_ln728_fu_96_p1 = $signed(res_0_V_write_assign_fu_88_p3);

endmodule //linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config6_s
