// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_3 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [13:0] data_0_V_read;
input  [13:0] data_1_V_read;
input  [13:0] data_2_V_read;
input  [13:0] data_3_V_read;
input  [13:0] data_4_V_read;
input  [13:0] data_5_V_read;
input  [13:0] data_6_V_read;
input  [13:0] data_7_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;

wire   [27:0] mul_ln1118_5_fu_401_p2;
reg   [27:0] mul_ln1118_5_reg_36549;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [23:0] mul_ln728_18_fu_393_p2;
reg   [23:0] mul_ln728_18_reg_36586;
wire   [26:0] mul_ln728_19_fu_364_p2;
reg   [26:0] mul_ln728_19_reg_36590;
wire   [25:0] mul_ln728_23_fu_348_p2;
reg   [25:0] mul_ln728_23_reg_36618;
wire   [24:0] mul_ln1118_16_fu_356_p2;
reg   [24:0] mul_ln1118_16_reg_36652;
wire   [25:0] mul_ln1118_18_fu_417_p2;
reg   [25:0] mul_ln1118_18_reg_36662;
wire   [27:0] mul_ln728_32_fu_431_p2;
reg   [27:0] mul_ln728_32_reg_36666;
wire   [27:0] mul_ln1118_19_fu_402_p2;
reg   [27:0] mul_ln1118_19_reg_36670;
wire   [25:0] mul_ln1118_20_fu_373_p2;
reg   [25:0] mul_ln1118_20_reg_36674;
wire   [25:0] mul_ln728_33_fu_429_p2;
reg   [25:0] mul_ln728_33_reg_36678;
wire   [27:0] mul_ln1118_21_fu_361_p2;
reg   [27:0] mul_ln1118_21_reg_36682;
wire   [26:0] mul_ln1118_22_fu_359_p2;
reg   [26:0] mul_ln1118_22_reg_36686;
wire   [26:0] mul_ln728_34_fu_411_p2;
reg   [26:0] mul_ln728_34_reg_36690;
wire   [25:0] mul_ln1118_23_fu_375_p2;
reg   [25:0] mul_ln1118_23_reg_36694;
wire   [26:0] mul_ln728_35_fu_338_p2;
reg   [26:0] mul_ln728_35_reg_36698;
wire   [26:0] mul_ln728_36_fu_352_p2;
reg   [26:0] mul_ln728_36_reg_36702;
wire   [25:0] mul_ln1118_24_fu_382_p2;
reg   [25:0] mul_ln1118_24_reg_36706;
wire   [26:0] mul_ln728_37_fu_353_p2;
reg   [26:0] mul_ln728_37_reg_36710;
wire   [26:0] mul_ln1118_25_fu_399_p2;
reg   [26:0] mul_ln1118_25_reg_36714;
wire   [26:0] mul_ln728_38_fu_345_p2;
reg   [26:0] mul_ln728_38_reg_36718;
wire   [27:0] mul_ln1118_26_fu_343_p2;
reg   [27:0] mul_ln1118_26_reg_36722;
wire   [27:0] mul_ln728_39_fu_368_p2;
reg   [27:0] mul_ln728_39_reg_36726;
wire   [26:0] mul_ln728_40_fu_360_p2;
reg   [26:0] mul_ln728_40_reg_36730;
wire   [27:0] mul_ln728_41_fu_385_p2;
reg   [27:0] mul_ln728_41_reg_36734;
wire   [26:0] mul_ln1118_27_fu_383_p2;
reg   [26:0] mul_ln1118_27_reg_36738;
wire   [27:0] mul_ln1118_28_fu_376_p2;
reg   [27:0] mul_ln1118_28_reg_36742;
wire   [24:0] mul_ln1118_29_fu_370_p2;
reg   [24:0] mul_ln1118_29_reg_36746;
wire   [26:0] mul_ln1118_30_fu_371_p2;
reg   [26:0] mul_ln1118_30_reg_36750;
wire   [26:0] mul_ln728_42_fu_369_p2;
reg   [26:0] mul_ln728_42_reg_36754;
wire   [26:0] mul_ln728_44_fu_378_p2;
reg   [26:0] mul_ln728_44_reg_36761;
wire   [24:0] mul_ln1118_34_fu_416_p2;
reg   [24:0] mul_ln1118_34_reg_36774;
wire   [24:0] mul_ln728_45_fu_387_p2;
reg   [24:0] mul_ln728_45_reg_36778;
wire   [24:0] mul_ln728_48_fu_395_p2;
reg   [24:0] mul_ln728_48_reg_36791;
reg   [13:0] data_7_V_read_12_reg_38912;
wire   [23:0] sub_ln1118_1_fu_37296_p2;
reg   [23:0] sub_ln1118_1_reg_38920;
wire   [51:0] add_ln703_fu_37686_p2;
reg   [51:0] add_ln703_reg_38925;
wire   [51:0] add_ln703_8_fu_37698_p2;
reg   [51:0] add_ln703_8_reg_38930;
wire   [51:0] add_ln703_11_fu_37704_p2;
reg   [51:0] add_ln703_11_reg_38935;
wire   [51:0] add_ln703_12_fu_37710_p2;
reg   [51:0] add_ln703_12_reg_38940;
wire   [50:0] add_ln703_15_fu_37716_p2;
reg   [50:0] add_ln703_15_reg_38945;
wire   [49:0] add_ln703_19_fu_37722_p2;
reg   [49:0] add_ln703_19_reg_38950;
wire   [51:0] add_ln703_20_fu_37728_p2;
reg   [51:0] add_ln703_20_reg_38955;
wire   [51:0] add_ln703_24_fu_37740_p2;
reg   [51:0] add_ln703_24_reg_38960;
wire   [51:0] add_ln703_27_fu_37746_p2;
reg   [51:0] add_ln703_27_reg_38965;
wire   [51:0] add_ln703_28_fu_37752_p2;
reg   [51:0] add_ln703_28_reg_38970;
wire   [51:0] add_ln703_32_fu_37764_p2;
reg   [51:0] add_ln703_32_reg_38975;
wire   [51:0] add_ln703_35_fu_37770_p2;
reg   [51:0] add_ln703_35_reg_38980;
wire   [51:0] add_ln703_36_fu_37776_p2;
reg   [51:0] add_ln703_36_reg_38985;
wire   [51:0] add_ln703_40_fu_37788_p2;
reg   [51:0] add_ln703_40_reg_38990;
wire   [51:0] add_ln703_43_fu_37794_p2;
reg   [51:0] add_ln703_43_reg_38995;
wire   [51:0] add_ln703_44_fu_37800_p2;
reg   [51:0] add_ln703_44_reg_39000;
wire   [50:0] add_ln703_51_fu_37806_p2;
reg   [50:0] add_ln703_51_reg_39005;
wire   [51:0] add_ln703_52_fu_37812_p2;
reg   [51:0] add_ln703_52_reg_39010;
wire   [51:0] add_ln703_59_fu_37818_p2;
reg   [51:0] add_ln703_59_reg_39015;
wire   [51:0] add_ln703_60_fu_37824_p2;
reg   [51:0] add_ln703_60_reg_39020;
wire   [51:0] add_ln703_64_fu_37836_p2;
reg   [51:0] add_ln703_64_reg_39025;
wire   [51:0] add_ln703_67_fu_37842_p2;
reg   [51:0] add_ln703_67_reg_39030;
wire   [50:0] add_ln703_68_fu_37848_p2;
reg   [50:0] add_ln703_68_reg_39035;
wire   [51:0] add_ln703_72_fu_37860_p2;
reg   [51:0] add_ln703_72_reg_39040;
wire   [51:0] add_ln703_75_fu_37866_p2;
reg   [51:0] add_ln703_75_reg_39045;
wire   [51:0] add_ln703_80_fu_37878_p2;
reg   [51:0] add_ln703_80_reg_39050;
wire   [50:0] add_ln703_83_fu_37884_p2;
reg   [50:0] add_ln703_83_reg_39055;
wire   [51:0] add_ln703_84_fu_37890_p2;
reg   [51:0] add_ln703_84_reg_39060;
wire   [48:0] add_ln703_87_fu_37896_p2;
reg   [48:0] add_ln703_87_reg_39065;
wire   [50:0] add_ln703_92_fu_37902_p2;
reg   [50:0] add_ln703_92_reg_39070;
wire   [51:0] add_ln703_95_fu_37908_p2;
reg   [51:0] add_ln703_95_reg_39075;
wire   [13:0] mul_ln1118_8_fu_336_p0;
wire   [26:0] zext_ln1118_7_fu_37105_p1;
wire    ap_block_pp0_stage0;
wire   [13:0] mul_ln728_30_fu_337_p0;
wire   [25:0] zext_ln1118_15_fu_37330_p1;
wire   [13:0] mul_ln728_35_fu_338_p0;
wire   [26:0] zext_ln1118_16_fu_37416_p1;
wire   [13:0] mul_ln728_22_fu_339_p0;
wire   [25:0] zext_ln1118_10_fu_37199_p1;
wire   [13:0] mul_ln728_8_fu_340_p0;
wire   [27:0] zext_ln1118_2_fu_36840_p1;
wire   [13:0] mul_ln728_31_fu_341_p0;
wire   [26:0] zext_ln1118_12_fu_37252_p1;
wire   [13:0] mul_ln728_14_fu_342_p0;
wire   [27:0] zext_ln1118_5_fu_36979_p1;
wire   [13:0] mul_ln1118_26_fu_343_p0;
wire   [27:0] zext_ln1118_21_fu_37456_p1;
wire   [13:0] mul_ln728_47_fu_344_p0;
wire   [13:0] mul_ln728_38_fu_345_p0;
wire   [26:0] zext_ln1118_20_fu_37445_p1;
wire   [13:0] mul_ln1118_14_fu_346_p0;
wire   [27:0] zext_ln728_16_fu_37241_p1;
wire   [13:0] mul_ln728_56_fu_347_p0;
wire   [27:0] zext_ln1118_27_fu_37573_p1;
wire   [13:0] mul_ln728_23_fu_348_p0;
wire   [13:0] mul_ln1118_31_fu_349_p0;
wire   [26:0] zext_ln1118_23_fu_37471_p1;
wire   [13:0] mul_ln728_15_fu_350_p0;
wire   [24:0] zext_ln1118_6_fu_37003_p1;
wire   [13:0] mul_ln1118_35_fu_351_p0;
wire   [27:0] zext_ln1118_24_fu_37478_p1;
wire   [13:0] mul_ln728_36_fu_352_p0;
wire   [13:0] mul_ln728_37_fu_353_p0;
wire   [13:0] mul_ln1118_3_fu_354_p0;
wire   [13:0] mul_ln728_7_fu_355_p0;
wire   [25:0] zext_ln1118_3_fu_36849_p1;
wire   [13:0] mul_ln1118_16_fu_356_p0;
wire   [13:0] mul_ln728_46_fu_358_p0;
wire   [13:0] mul_ln1118_22_fu_359_p0;
wire   [13:0] mul_ln728_40_fu_360_p0;
wire   [13:0] mul_ln1118_21_fu_361_p0;
wire   [27:0] zext_ln1118_17_fu_37424_p1;
wire   [13:0] mul_ln1118_10_fu_362_p0;
wire   [13:0] mul_ln1118_2_fu_363_p0;
wire   [26:0] zext_ln1118_1_fu_36834_p1;
wire   [13:0] mul_ln728_19_fu_364_p0;
wire   [13:0] mul_ln728_fu_365_p0;
wire   [13:0] mul_ln1118_36_fu_366_p0;
wire   [13:0] mul_ln728_43_fu_367_p0;
wire   [13:0] mul_ln728_39_fu_368_p0;
wire   [13:0] mul_ln728_42_fu_369_p0;
wire   [13:0] mul_ln1118_29_fu_370_p0;
wire   [13:0] mul_ln1118_30_fu_371_p0;
wire   [13:0] mul_ln1118_17_fu_372_p0;
wire   [13:0] mul_ln1118_20_fu_373_p0;
wire   [25:0] zext_ln1118_18_fu_37431_p1;
wire   [13:0] mul_ln728_52_fu_374_p0;
wire   [13:0] mul_ln1118_23_fu_375_p0;
wire   [13:0] mul_ln1118_28_fu_376_p0;
wire   [13:0] mul_ln1118_13_fu_377_p0;
wire   [13:0] mul_ln728_44_fu_378_p0;
wire   [13:0] mul_ln728_29_fu_379_p0;
wire   [13:0] mul_ln1118_6_fu_380_p0;
wire   [26:0] zext_ln1118_4_fu_36970_p1;
wire   [13:0] mul_ln1118_7_fu_381_p0;
wire   [13:0] mul_ln1118_24_fu_382_p0;
wire   [13:0] mul_ln1118_27_fu_383_p0;
wire   [13:0] mul_ln728_5_fu_384_p0;
wire   [13:0] mul_ln728_41_fu_385_p0;
wire   [13:0] mul_ln1118_15_fu_386_p0;
wire   [13:0] mul_ln728_45_fu_387_p0;
wire   [24:0] zext_ln1118_22_fu_37464_p1;
wire   [13:0] mul_ln728_20_fu_388_p0;
wire   [24:0] zext_ln1118_9_fu_37121_p1;
wire   [13:0] mul_ln1118_fu_389_p0;
wire   [13:0] mul_ln728_21_fu_390_p0;
wire   [13:0] mul_ln728_50_fu_391_p0;
wire   [13:0] mul_ln728_18_fu_393_p0;
wire   [13:0] mul_ln728_12_fu_394_p0;
wire   [13:0] mul_ln728_48_fu_395_p0;
wire   [13:0] mul_ln728_11_fu_396_p0;
wire   [13:0] mul_ln1118_11_fu_397_p0;
wire   [27:0] zext_ln1118_8_fu_37114_p1;
wire   [13:0] mul_ln1118_12_fu_398_p0;
wire   [13:0] mul_ln1118_25_fu_399_p0;
wire   [13:0] mul_ln1118_33_fu_400_p0;
wire   [13:0] mul_ln1118_5_fu_401_p0;
wire   [13:0] mul_ln1118_19_fu_402_p0;
wire   [13:0] mul_ln1118_4_fu_403_p0;
wire   [13:0] mul_ln1118_9_fu_404_p0;
wire   [13:0] mul_ln728_6_fu_405_p0;
wire   [13:0] mul_ln728_24_fu_406_p0;
wire   [13:0] mul_ln728_25_fu_407_p0;
wire   [13:0] mul_ln728_10_fu_408_p0;
wire   [13:0] mul_ln1118_32_fu_409_p0;
wire   [13:0] mul_ln728_51_fu_410_p0;
wire   [13:0] mul_ln728_34_fu_411_p0;
wire   [13:0] mul_ln1118_1_fu_412_p0;
wire   [13:0] mul_ln1118_38_fu_413_p0;
wire   [13:0] mul_ln728_27_fu_414_p0;
wire   [13:0] mul_ln728_28_fu_415_p0;
wire   [13:0] mul_ln1118_34_fu_416_p0;
wire   [13:0] mul_ln1118_18_fu_417_p0;
wire   [13:0] mul_ln1118_37_fu_419_p0;
wire   [13:0] mul_ln728_4_fu_420_p0;
wire   [13:0] mul_ln728_13_fu_421_p0;
wire   [13:0] mul_ln728_55_fu_422_p0;
wire   [13:0] mul_ln728_26_fu_423_p0;
wire   [13:0] mul_ln728_54_fu_424_p0;
wire   [26:0] zext_ln1118_29_fu_37588_p1;
wire   [13:0] mul_ln728_17_fu_425_p0;
wire   [13:0] mul_ln728_49_fu_426_p0;
wire   [13:0] mul_ln728_16_fu_427_p0;
wire   [13:0] mul_ln728_53_fu_428_p0;
wire   [13:0] mul_ln728_33_fu_429_p0;
wire   [13:0] mul_ln728_9_fu_430_p0;
wire   [13:0] mul_ln728_32_fu_431_p0;
wire   [25:0] mul_ln1118_fu_389_p2;
wire   [49:0] shl_ln_fu_36857_p3;
wire   [26:0] mul_ln728_fu_365_p2;
wire   [50:0] shl_ln728_s_fu_36869_p3;
wire   [25:0] mul_ln1118_1_fu_412_p2;
wire   [27:0] mul_ln728_4_fu_420_p2;
wire   [25:0] mul_ln728_5_fu_384_p2;
wire   [49:0] shl_ln728_3_fu_36897_p3;
wire   [27:0] mul_ln728_6_fu_405_p2;
wire   [26:0] mul_ln1118_2_fu_363_p2;
wire   [27:0] mul_ln1118_3_fu_354_p2;
wire   [25:0] mul_ln728_7_fu_355_p2;
wire   [49:0] shl_ln728_7_fu_36933_p3;
wire   [27:0] mul_ln728_8_fu_340_p2;
wire   [24:0] mul_ln1118_4_fu_403_p2;
wire   [48:0] shl_ln728_9_fu_36953_p3;
wire   [27:0] mul_ln728_9_fu_430_p2;
wire   [27:0] mul_ln728_10_fu_408_p2;
wire   [24:0] mul_ln728_11_fu_396_p2;
wire   [48:0] shl_ln728_13_fu_37009_p3;
wire   [27:0] mul_ln728_12_fu_394_p2;
wire   [26:0] mul_ln728_13_fu_421_p2;
wire   [50:0] shl_ln728_15_fu_37029_p3;
wire   [27:0] mul_ln728_14_fu_342_p2;
wire   [24:0] mul_ln728_15_fu_350_p2;
wire   [48:0] shl_ln728_17_fu_37049_p3;
wire   [26:0] mul_ln728_16_fu_427_p2;
wire   [50:0] shl_ln728_18_fu_37061_p3;
wire   [26:0] mul_ln728_17_fu_425_p2;
wire   [50:0] shl_ln728_19_fu_37073_p3;
wire   [26:0] mul_ln1118_6_fu_380_p2;
wire   [50:0] shl_ln728_20_fu_37085_p3;
wire   [26:0] mul_ln1118_7_fu_381_p2;
wire   [24:0] mul_ln728_20_fu_388_p2;
wire   [48:0] shl_ln728_24_fu_37127_p3;
wire   [26:0] mul_ln1118_8_fu_336_p2;
wire   [50:0] shl_ln728_25_fu_37139_p3;
wire   [26:0] mul_ln728_21_fu_390_p2;
wire   [50:0] shl_ln728_26_fu_37151_p3;
wire   [27:0] mul_ln1118_9_fu_404_p2;
wire   [26:0] mul_ln1118_10_fu_362_p2;
wire   [50:0] shl_ln728_28_fu_37171_p3;
wire   [27:0] mul_ln1118_11_fu_397_p2;
wire   [27:0] mul_ln1118_12_fu_398_p2;
wire   [25:0] mul_ln728_22_fu_339_p2;
wire   [49:0] shl_ln728_31_fu_37205_p3;
wire   [26:0] mul_ln1118_13_fu_377_p2;
wire   [50:0] shl_ln728_33_fu_37217_p3;
wire   [24:0] mul_ln728_24_fu_406_p2;
wire   [48:0] shl_ln728_34_fu_37229_p3;
wire   [21:0] shl_ln1_fu_37262_p3;
wire   [22:0] zext_ln1118_13_fu_37270_p1;
wire   [22:0] sub_ln1118_fu_37274_p2;
wire   [17:0] shl_ln1118_s_fu_37284_p3;
wire  signed [23:0] sext_ln1118_fu_37280_p1;
wire   [23:0] zext_ln1118_14_fu_37292_p1;
wire   [27:0] mul_ln728_25_fu_407_p2;
wire   [26:0] mul_ln728_26_fu_423_p2;
wire   [50:0] shl_ln728_37_fu_37310_p3;
wire   [27:0] mul_ln1118_14_fu_346_p2;
wire   [25:0] mul_ln728_27_fu_414_p2;
wire   [49:0] shl_ln728_39_fu_37336_p3;
wire   [26:0] mul_ln728_28_fu_415_p2;
wire   [50:0] shl_ln728_40_fu_37348_p3;
wire   [26:0] mul_ln1118_15_fu_386_p2;
wire   [50:0] shl_ln728_41_fu_37360_p3;
wire   [26:0] mul_ln728_29_fu_379_p2;
wire   [50:0] shl_ln728_42_fu_37372_p3;
wire   [25:0] mul_ln728_30_fu_337_p2;
wire   [49:0] shl_ln728_43_fu_37384_p3;
wire   [26:0] mul_ln728_31_fu_341_p2;
wire   [50:0] shl_ln728_45_fu_37396_p3;
wire   [26:0] mul_ln1118_17_fu_372_p2;
wire   [27:0] mul_ln728_43_fu_367_p2;
wire   [26:0] mul_ln1118_31_fu_349_p2;
wire   [50:0] shl_ln728_73_fu_37495_p3;
wire   [27:0] mul_ln1118_32_fu_409_p2;
wire   [26:0] mul_ln1118_33_fu_400_p2;
wire   [50:0] shl_ln728_75_fu_37515_p3;
wire   [27:0] mul_ln728_46_fu_358_p2;
wire   [25:0] mul_ln728_47_fu_344_p2;
wire   [49:0] shl_ln728_79_fu_37540_p3;
wire   [27:0] mul_ln1118_35_fu_351_p2;
wire   [27:0] mul_ln1118_36_fu_366_p2;
wire   [26:0] mul_ln728_49_fu_426_p2;
wire   [50:0] shl_ln728_83_fu_37594_p3;
wire   [25:0] mul_ln728_50_fu_391_p2;
wire   [49:0] shl_ln728_84_fu_37606_p3;
wire   [27:0] mul_ln728_51_fu_410_p2;
wire   [27:0] mul_ln728_52_fu_374_p2;
wire   [27:0] mul_ln728_53_fu_428_p2;
wire   [26:0] mul_ln728_54_fu_424_p2;
wire   [50:0] shl_ln728_90_fu_37642_p3;
wire   [27:0] mul_ln728_55_fu_422_p2;
wire   [27:0] mul_ln1118_37_fu_419_p2;
wire   [24:0] mul_ln1118_38_fu_413_p2;
wire   [27:0] mul_ln728_56_fu_347_p2;
wire  signed [51:0] sext_ln728_fu_36865_p1;
wire   [51:0] shl_ln728_11_fu_36987_p3;
wire   [51:0] zext_ln728_35_fu_37602_p1;
wire   [51:0] add_ln703_7_fu_37692_p2;
wire   [51:0] shl_ln728_71_fu_37487_p3;
wire   [51:0] zext_ln728_fu_36877_p1;
wire   [51:0] shl_ln728_12_fu_36995_p3;
wire   [51:0] zext_ln728_11_fu_37135_p1;
wire   [51:0] shl_ln728_36_fu_37302_p3;
wire   [50:0] zext_ln1118_30_fu_37614_p1;
wire   [49:0] shl_ln728_1_fu_36881_p3;
wire   [49:0] zext_ln728_4_fu_37017_p1;
wire  signed [51:0] sext_ln728_55_fu_37147_p1;
wire   [51:0] zext_ln728_17_fu_37318_p1;
wire   [51:0] shl_ln728_85_fu_37618_p3;
wire   [51:0] add_ln703_23_fu_37734_p2;
wire  signed [51:0] sext_ln728_70_fu_37503_p1;
wire   [51:0] shl_ln728_2_fu_36889_p3;
wire   [51:0] shl_ln728_14_fu_37021_p3;
wire   [51:0] zext_ln728_12_fu_37159_p1;
wire   [51:0] shl_ln728_38_fu_37322_p3;
wire   [51:0] shl_ln728_86_fu_37626_p3;
wire   [51:0] add_ln703_31_fu_37758_p2;
wire   [51:0] shl_ln728_74_fu_37507_p3;
wire   [51:0] zext_ln728_1_fu_36905_p1;
wire   [51:0] zext_ln728_5_fu_37037_p1;
wire   [51:0] shl_ln728_27_fu_37163_p3;
wire   [51:0] zext_ln728_18_fu_37344_p1;
wire   [51:0] shl_ln728_87_fu_37634_p3;
wire   [51:0] add_ln703_39_fu_37782_p2;
wire  signed [51:0] sext_ln728_71_fu_37523_p1;
wire   [51:0] shl_ln728_4_fu_36909_p3;
wire   [51:0] shl_ln728_16_fu_37041_p3;
wire  signed [51:0] sext_ln728_56_fu_37179_p1;
wire   [51:0] zext_ln728_19_fu_37356_p1;
wire   [50:0] shl_ln728_5_fu_36917_p3;
wire   [50:0] zext_ln728_6_fu_37057_p1;
wire   [51:0] shl_ln728_29_fu_37183_p3;
wire  signed [51:0] sext_ln728_59_fu_37368_p1;
wire   [51:0] shl_ln728_6_fu_36925_p3;
wire   [51:0] zext_ln728_7_fu_37069_p1;
wire   [51:0] shl_ln728_30_fu_37191_p3;
wire   [51:0] zext_ln728_20_fu_37380_p1;
wire   [51:0] zext_ln728_36_fu_37650_p1;
wire   [51:0] add_ln703_63_fu_37830_p2;
wire   [51:0] shl_ln728_78_fu_37527_p3;
wire   [51:0] zext_ln728_2_fu_36941_p1;
wire   [51:0] zext_ln728_8_fu_37081_p1;
wire   [50:0] zext_ln728_13_fu_37213_p1;
wire   [50:0] zext_ln728_21_fu_37392_p1;
wire   [51:0] shl_ln728_91_fu_37654_p3;
wire   [51:0] add_ln703_71_fu_37854_p2;
wire   [51:0] zext_ln728_33_fu_37548_p1;
wire   [51:0] shl_ln728_8_fu_36945_p3;
wire  signed [51:0] sext_ln728_54_fu_37093_p1;
wire   [51:0] shl_ln728_92_fu_37662_p3;
wire   [51:0] add_ln703_79_fu_37872_p2;
wire   [51:0] shl_ln728_80_fu_37552_p3;
wire  signed [50:0] sext_ln728_53_fu_36961_p1;
wire   [50:0] shl_ln728_21_fu_37097_p3;
wire  signed [51:0] sext_ln728_57_fu_37225_p1;
wire   [51:0] zext_ln728_22_fu_37404_p1;
wire   [48:0] shl_ln728_93_fu_37670_p3;
wire   [50:0] zext_ln728_15_fu_37237_p1;
wire   [50:0] shl_ln728_46_fu_37408_p3;
wire   [51:0] shl_ln728_82_fu_37560_p3;
wire   [51:0] shl_ln728_94_fu_37678_p3;
wire   [47:0] shl_ln728_22_fu_37922_p3;
wire   [50:0] shl_ln728_23_fu_37934_p3;
wire   [49:0] shl_ln728_32_fu_37946_p3;
wire   [47:0] shl_ln728_35_fu_37958_p3;
wire   [48:0] shl_ln728_44_fu_37969_p3;
wire   [49:0] shl_ln728_47_fu_37981_p3;
wire   [49:0] shl_ln728_50_fu_38009_p3;
wire   [49:0] shl_ln728_51_fu_38021_p3;
wire   [50:0] shl_ln728_53_fu_38041_p3;
wire   [50:0] shl_ln728_54_fu_38053_p3;
wire   [49:0] shl_ln728_55_fu_38065_p3;
wire   [50:0] shl_ln728_56_fu_38077_p3;
wire   [50:0] shl_ln728_57_fu_38089_p3;
wire   [49:0] shl_ln728_58_fu_38101_p3;
wire   [50:0] shl_ln728_59_fu_38113_p3;
wire   [50:0] shl_ln728_60_fu_38125_p3;
wire   [50:0] shl_ln728_61_fu_38137_p3;
wire   [50:0] shl_ln728_64_fu_38165_p3;
wire   [50:0] shl_ln728_66_fu_38185_p3;
wire   [48:0] shl_ln728_68_fu_38205_p3;
wire   [50:0] shl_ln728_69_fu_38217_p3;
wire   [50:0] shl_ln728_70_fu_38229_p3;
wire   [50:0] shl_ln728_72_fu_38241_p3;
wire   [48:0] shl_ln728_76_fu_38253_p3;
wire   [48:0] shl_ln728_77_fu_38265_p3;
wire   [48:0] shl_ln728_81_fu_38277_p3;
wire   [24:0] shl_ln1118_1_fu_38289_p3;
wire   [16:0] shl_ln1118_2_fu_38300_p3;
wire   [25:0] zext_ln1118_32_fu_38307_p1;
wire   [25:0] zext_ln1118_31_fu_38296_p1;
wire   [25:0] add_ln1118_fu_38311_p2;
wire   [49:0] shl_ln728_88_fu_38317_p3;
wire   [25:0] shl_ln1118_3_fu_38329_p3;
wire   [17:0] shl_ln1118_4_fu_38340_p3;
wire   [26:0] zext_ln1118_35_fu_38347_p1;
wire   [26:0] zext_ln1118_34_fu_38336_p1;
wire   [26:0] sub_ln1118_2_fu_38351_p2;
wire   [50:0] shl_ln728_89_fu_38357_p3;
wire   [51:0] zext_ln728_10_fu_37942_p1;
wire  signed [51:0] sext_ln728_58_fu_37965_p1;
wire   [51:0] add_ln703_4_fu_38369_p2;
wire  signed [51:0] sext_ln728_61_fu_37989_p1;
wire   [51:0] zext_ln728_27_fu_38121_p1;
wire   [51:0] add_ln703_6_fu_38380_p2;
wire   [51:0] add_ln703_9_fu_38386_p2;
wire   [51:0] add_ln703_5_fu_38375_p2;
wire   [51:0] shl_ln728_48_fu_37993_p3;
wire  signed [51:0] sext_ln728_66_fu_38133_p1;
wire  signed [51:0] sext_ln703_fu_38407_p1;
wire   [51:0] zext_ln728_31_fu_38249_p1;
wire   [51:0] add_ln703_16_fu_38410_p2;
wire   [51:0] add_ln703_14_fu_38401_p2;
wire   [51:0] add_ln703_17_fu_38416_p2;
wire   [51:0] add_ln703_13_fu_38397_p2;
wire  signed [51:0] sext_ln703_1_fu_38428_p1;
wire   [51:0] shl_ln728_49_fu_38001_p3;
wire   [51:0] zext_ln728_28_fu_38145_p1;
wire   [51:0] add_ln703_22_fu_38436_p2;
wire   [51:0] add_ln703_25_fu_38442_p2;
wire   [51:0] add_ln703_21_fu_38431_p2;
wire  signed [51:0] sext_ln728_62_fu_38017_p1;
wire   [51:0] shl_ln728_62_fu_38149_p3;
wire   [51:0] add_ln703_30_fu_38457_p2;
wire   [51:0] add_ln703_33_fu_38463_p2;
wire   [51:0] add_ln703_29_fu_38453_p2;
wire   [51:0] zext_ln728_23_fu_38029_p1;
wire   [51:0] shl_ln728_63_fu_38157_p3;
wire   [51:0] add_ln703_38_fu_38478_p2;
wire   [51:0] add_ln703_41_fu_38484_p2;
wire   [51:0] add_ln703_37_fu_38474_p2;
wire   [51:0] shl_ln728_52_fu_38033_p3;
wire   [51:0] zext_ln728_29_fu_38173_p1;
wire   [50:0] zext_ln1118_33_fu_38325_p1;
wire   [50:0] add_ln703_47_fu_38505_p2;
wire  signed [50:0] sext_ln1118_1_fu_38261_p1;
wire   [50:0] add_ln703_48_fu_38511_p2;
wire  signed [51:0] sext_ln703_2_fu_38517_p1;
wire   [51:0] add_ln703_46_fu_38499_p2;
wire   [51:0] add_ln703_49_fu_38521_p2;
wire   [51:0] add_ln703_45_fu_38495_p2;
wire  signed [51:0] sext_ln703_3_fu_38533_p1;
wire  signed [51:0] sext_ln728_63_fu_38049_p1;
wire   [51:0] shl_ln728_65_fu_38177_p3;
wire  signed [51:0] sext_ln728_72_fu_38365_p1;
wire   [51:0] add_ln703_55_fu_38547_p2;
wire   [51:0] zext_ln728_32_fu_38273_p1;
wire   [51:0] add_ln703_56_fu_38553_p2;
wire   [51:0] add_ln703_54_fu_38541_p2;
wire   [51:0] add_ln703_57_fu_38559_p2;
wire   [51:0] add_ln703_53_fu_38536_p2;
wire   [51:0] zext_ln728_24_fu_38061_p1;
wire  signed [51:0] sext_ln728_67_fu_38193_p1;
wire   [51:0] add_ln703_62_fu_38575_p2;
wire   [51:0] add_ln703_65_fu_38581_p2;
wire   [51:0] add_ln703_61_fu_38571_p2;
wire   [51:0] zext_ln703_fu_38592_p1;
wire  signed [51:0] sext_ln728_64_fu_38073_p1;
wire   [51:0] shl_ln728_67_fu_38197_p3;
wire   [51:0] add_ln703_70_fu_38600_p2;
wire   [51:0] add_ln703_73_fu_38606_p2;
wire   [51:0] add_ln703_69_fu_38595_p2;
wire   [50:0] zext_ln728_14_fu_37954_p1;
wire  signed [50:0] sext_ln728_60_fu_37977_p1;
wire   [50:0] add_ln703_76_fu_38617_p2;
wire  signed [51:0] sext_ln703_4_fu_38623_p1;
wire   [51:0] zext_ln728_25_fu_38085_p1;
wire  signed [51:0] sext_ln728_68_fu_38213_p1;
wire   [51:0] add_ln703_78_fu_38632_p2;
wire   [51:0] add_ln703_81_fu_38638_p2;
wire   [51:0] add_ln703_77_fu_38627_p2;
wire  signed [51:0] sext_ln703_5_fu_38649_p1;
wire   [51:0] zext_ln728_26_fu_38097_p1;
wire  signed [51:0] sext_ln728_69_fu_38225_p1;
wire  signed [49:0] sext_ln703_6_fu_38663_p1;
wire   [49:0] zext_ln1118_26_fu_38285_p1;
wire   [49:0] add_ln703_88_fu_38666_p2;
wire  signed [51:0] sext_ln703_7_fu_38672_p1;
wire   [51:0] add_ln703_86_fu_38657_p2;
wire   [51:0] add_ln703_89_fu_38676_p2;
wire   [51:0] add_ln703_85_fu_38652_p2;
wire   [51:0] zext_ln728_9_fu_37930_p1;
wire   [51:0] shl_ln728_10_fu_37914_p3;
wire  signed [51:0] sext_ln703_8_fu_38694_p1;
wire   [51:0] add_ln703_91_fu_38688_p2;
wire  signed [51:0] sext_ln728_65_fu_38109_p1;
wire   [51:0] zext_ln728_30_fu_38237_p1;
wire   [51:0] add_ln703_94_fu_38703_p2;
wire   [51:0] add_ln703_96_fu_38709_p2;
wire   [51:0] add_ln703_93_fu_38697_p2;
wire   [51:0] p_Val2_s_fu_38391_p2;
wire   [51:0] acc_1_V_fu_38422_p2;
wire   [51:0] acc_2_V_fu_38447_p2;
wire   [51:0] acc_3_V_fu_38468_p2;
wire   [51:0] acc_4_V_fu_38489_p2;
wire   [51:0] acc_5_V_fu_38527_p2;
wire   [51:0] acc_6_V_fu_38565_p2;
wire   [51:0] acc_7_V_fu_38586_p2;
wire   [51:0] acc_8_V_fu_38611_p2;
wire   [51:0] acc_9_V_fu_38643_p2;
wire   [51:0] acc_10_V_fu_38682_p2;
wire   [51:0] acc_11_V_fu_38714_p2;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;
reg   [15:0] ap_return_8_int_reg;
reg   [15:0] ap_return_9_int_reg;
reg   [15:0] ap_return_10_int_reg;
reg   [15:0] ap_return_11_int_reg;
wire   [24:0] mul_ln1118_16_fu_356_p00;
wire   [24:0] mul_ln1118_29_fu_370_p00;
wire   [24:0] mul_ln1118_38_fu_413_p00;
wire   [24:0] mul_ln1118_4_fu_403_p00;
wire   [23:0] mul_ln728_18_fu_393_p00;
wire   [25:0] mul_ln728_47_fu_344_p00;
wire   [25:0] mul_ln728_50_fu_391_p00;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln703_11_reg_38935[51 : 27] <= add_ln703_11_fu_37704_p2[51 : 27];
        add_ln703_12_reg_38940[51 : 25] <= add_ln703_12_fu_37710_p2[51 : 25];
        add_ln703_15_reg_38945[50 : 25] <= add_ln703_15_fu_37716_p2[50 : 25];
        add_ln703_19_reg_38950[49 : 24] <= add_ln703_19_fu_37722_p2[49 : 24];
        add_ln703_20_reg_38955[51 : 24] <= add_ln703_20_fu_37728_p2[51 : 24];
        add_ln703_24_reg_38960[51 : 27] <= add_ln703_24_fu_37740_p2[51 : 27];
        add_ln703_27_reg_38965[51 : 25] <= add_ln703_27_fu_37746_p2[51 : 25];
        add_ln703_28_reg_38970[51 : 25] <= add_ln703_28_fu_37752_p2[51 : 25];
        add_ln703_32_reg_38975[51 : 24] <= add_ln703_32_fu_37764_p2[51 : 24];
        add_ln703_35_reg_38980[51 : 25] <= add_ln703_35_fu_37770_p2[51 : 25];
        add_ln703_36_reg_38985[51 : 26] <= add_ln703_36_fu_37776_p2[51 : 26];
        add_ln703_40_reg_38990[51 : 26] <= add_ln703_40_fu_37788_p2[51 : 26];
        add_ln703_43_reg_38995[51 : 25] <= add_ln703_43_fu_37794_p2[51 : 25];
        add_ln703_44_reg_39000[51 : 24] <= add_ln703_44_fu_37800_p2[51 : 24];
        add_ln703_51_reg_39005[50 : 25] <= add_ln703_51_fu_37806_p2[50 : 25];
        add_ln703_52_reg_39010[51 : 25] <= add_ln703_52_fu_37812_p2[51 : 25];
        add_ln703_59_reg_39015[51 : 24] <= add_ln703_59_fu_37818_p2[51 : 24];
        add_ln703_60_reg_39020[51 : 25] <= add_ln703_60_fu_37824_p2[51 : 25];
        add_ln703_64_reg_39025[51 : 24] <= add_ln703_64_fu_37836_p2[51 : 24];
        add_ln703_67_reg_39030[51 : 24] <= add_ln703_67_fu_37842_p2[51 : 24];
        add_ln703_68_reg_39035[50 : 25] <= add_ln703_68_fu_37848_p2[50 : 25];
        add_ln703_72_reg_39040[51 : 24] <= add_ln703_72_fu_37860_p2[51 : 24];
        add_ln703_75_reg_39045[51 : 27] <= add_ln703_75_fu_37866_p2[51 : 27];
        add_ln703_80_reg_39050[51 : 24] <= add_ln703_80_fu_37878_p2[51 : 24];
        add_ln703_83_reg_39055[50 : 27] <= add_ln703_83_fu_37884_p2[50 : 27];
        add_ln703_84_reg_39060[51 : 24] <= add_ln703_84_fu_37890_p2[51 : 24];
        add_ln703_87_reg_39065[48 : 27] <= add_ln703_87_fu_37896_p2[48 : 27];
        add_ln703_8_reg_38930[51 : 24] <= add_ln703_8_fu_37698_p2[51 : 24];
        add_ln703_92_reg_39070[50 : 24] <= add_ln703_92_fu_37902_p2[50 : 24];
        add_ln703_95_reg_39075[51 : 26] <= add_ln703_95_fu_37908_p2[51 : 26];
        add_ln703_reg_38925[51 : 27] <= add_ln703_fu_37686_p2[51 : 27];
        data_7_V_read_12_reg_38912 <= data_7_V_read;
        mul_ln1118_16_reg_36652 <= mul_ln1118_16_fu_356_p2;
        mul_ln1118_18_reg_36662 <= mul_ln1118_18_fu_417_p2;
        mul_ln1118_19_reg_36670[27 : 1] <= mul_ln1118_19_fu_402_p2[27 : 1];
        mul_ln1118_20_reg_36674[25 : 1] <= mul_ln1118_20_fu_373_p2[25 : 1];
        mul_ln1118_21_reg_36682[27 : 5] <= mul_ln1118_21_fu_361_p2[27 : 5];
        mul_ln1118_22_reg_36686[26 : 1] <= mul_ln1118_22_fu_359_p2[26 : 1];
        mul_ln1118_23_reg_36694 <= mul_ln1118_23_fu_375_p2;
        mul_ln1118_24_reg_36706[25 : 2] <= mul_ln1118_24_fu_382_p2[25 : 2];
        mul_ln1118_25_reg_36714[26 : 1] <= mul_ln1118_25_fu_399_p2[26 : 1];
        mul_ln1118_26_reg_36722[27 : 1] <= mul_ln1118_26_fu_343_p2[27 : 1];
        mul_ln1118_27_reg_36738[26 : 1] <= mul_ln1118_27_fu_383_p2[26 : 1];
        mul_ln1118_28_reg_36742[27 : 3] <= mul_ln1118_28_fu_376_p2[27 : 3];
        mul_ln1118_29_reg_36746[24 : 3] <= mul_ln1118_29_fu_370_p2[24 : 3];
        mul_ln1118_30_reg_36750[26 : 1] <= mul_ln1118_30_fu_371_p2[26 : 1];
        mul_ln1118_34_reg_36774[24 : 1] <= mul_ln1118_34_fu_416_p2[24 : 1];
        mul_ln1118_5_reg_36549[27 : 1] <= mul_ln1118_5_fu_401_p2[27 : 1];
        mul_ln728_18_reg_36586[23 : 1] <= mul_ln728_18_fu_393_p2[23 : 1];
        mul_ln728_19_reg_36590 <= mul_ln728_19_fu_364_p2;
        mul_ln728_23_reg_36618[25 : 3] <= mul_ln728_23_fu_348_p2[25 : 3];
        mul_ln728_32_reg_36666[27 : 1] <= mul_ln728_32_fu_431_p2[27 : 1];
        mul_ln728_33_reg_36678[25 : 2] <= mul_ln728_33_fu_429_p2[25 : 2];
        mul_ln728_34_reg_36690[26 : 2] <= mul_ln728_34_fu_411_p2[26 : 2];
        mul_ln728_35_reg_36698[26 : 1] <= mul_ln728_35_fu_338_p2[26 : 1];
        mul_ln728_36_reg_36702[26 : 5] <= mul_ln728_36_fu_352_p2[26 : 5];
        mul_ln728_37_reg_36710[26 : 2] <= mul_ln728_37_fu_353_p2[26 : 2];
        mul_ln728_38_reg_36718[26 : 1] <= mul_ln728_38_fu_345_p2[26 : 1];
        mul_ln728_39_reg_36726[27 : 3] <= mul_ln728_39_fu_368_p2[27 : 3];
        mul_ln728_40_reg_36730[26 : 1] <= mul_ln728_40_fu_360_p2[26 : 1];
        mul_ln728_41_reg_36734 <= mul_ln728_41_fu_385_p2;
        mul_ln728_42_reg_36754[26 : 1] <= mul_ln728_42_fu_369_p2[26 : 1];
        mul_ln728_44_reg_36761[26 : 1] <= mul_ln728_44_fu_378_p2[26 : 1];
        mul_ln728_45_reg_36778 <= mul_ln728_45_fu_387_p2;
        mul_ln728_48_reg_36791 <= mul_ln728_48_fu_395_p2;
        sub_ln1118_1_reg_38920[23 : 4] <= sub_ln1118_1_fu_37296_p2[23 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= {{p_Val2_s_fu_38391_p2[51:36]}};
        ap_return_10_int_reg <= {{acc_10_V_fu_38682_p2[51:36]}};
        ap_return_11_int_reg <= {{acc_11_V_fu_38714_p2[51:36]}};
        ap_return_1_int_reg <= {{acc_1_V_fu_38422_p2[51:36]}};
        ap_return_2_int_reg <= {{acc_2_V_fu_38447_p2[51:36]}};
        ap_return_3_int_reg <= {{acc_3_V_fu_38468_p2[51:36]}};
        ap_return_4_int_reg <= {{acc_4_V_fu_38489_p2[51:36]}};
        ap_return_5_int_reg <= {{acc_5_V_fu_38527_p2[51:36]}};
        ap_return_6_int_reg <= {{acc_6_V_fu_38565_p2[51:36]}};
        ap_return_7_int_reg <= {{acc_7_V_fu_38586_p2[51:36]}};
        ap_return_8_int_reg <= {{acc_8_V_fu_38611_p2[51:36]}};
        ap_return_9_int_reg <= {{acc_9_V_fu_38643_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = {{p_Val2_s_fu_38391_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = {{acc_1_V_fu_38422_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_10 = ap_return_10_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_10 = {{acc_10_V_fu_38682_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_11 = ap_return_11_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_11 = {{acc_11_V_fu_38714_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = {{acc_2_V_fu_38447_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = {{acc_3_V_fu_38468_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = {{acc_4_V_fu_38489_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = {{acc_5_V_fu_38527_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = {{acc_6_V_fu_38565_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = {{acc_7_V_fu_38586_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = {{acc_8_V_fu_38611_p2[51:36]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_9 = ap_return_9_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_9 = {{acc_9_V_fu_38643_p2[51:36]}};
    end
end

assign acc_10_V_fu_38682_p2 = (add_ln703_89_fu_38676_p2 + add_ln703_85_fu_38652_p2);

assign acc_11_V_fu_38714_p2 = (add_ln703_96_fu_38709_p2 + add_ln703_93_fu_38697_p2);

assign acc_1_V_fu_38422_p2 = (add_ln703_17_fu_38416_p2 + add_ln703_13_fu_38397_p2);

assign acc_2_V_fu_38447_p2 = (add_ln703_25_fu_38442_p2 + add_ln703_21_fu_38431_p2);

assign acc_3_V_fu_38468_p2 = (add_ln703_33_fu_38463_p2 + add_ln703_29_fu_38453_p2);

assign acc_4_V_fu_38489_p2 = (add_ln703_41_fu_38484_p2 + add_ln703_37_fu_38474_p2);

assign acc_5_V_fu_38527_p2 = (add_ln703_49_fu_38521_p2 + add_ln703_45_fu_38495_p2);

assign acc_6_V_fu_38565_p2 = (add_ln703_57_fu_38559_p2 + add_ln703_53_fu_38536_p2);

assign acc_7_V_fu_38586_p2 = (add_ln703_65_fu_38581_p2 + add_ln703_61_fu_38571_p2);

assign acc_8_V_fu_38611_p2 = (add_ln703_73_fu_38606_p2 + add_ln703_69_fu_38595_p2);

assign acc_9_V_fu_38643_p2 = (add_ln703_81_fu_38638_p2 + add_ln703_77_fu_38627_p2);

assign add_ln1118_fu_38311_p2 = (zext_ln1118_32_fu_38307_p1 + zext_ln1118_31_fu_38296_p1);

assign add_ln703_11_fu_37704_p2 = (zext_ln728_fu_36877_p1 + shl_ln728_12_fu_36995_p3);

assign add_ln703_12_fu_37710_p2 = (zext_ln728_11_fu_37135_p1 + shl_ln728_36_fu_37302_p3);

assign add_ln703_13_fu_38397_p2 = (add_ln703_12_reg_38940 + add_ln703_11_reg_38935);

assign add_ln703_14_fu_38401_p2 = ($signed(shl_ln728_48_fu_37993_p3) + $signed(sext_ln728_66_fu_38133_p1));

assign add_ln703_15_fu_37716_p2 = ($signed(zext_ln1118_30_fu_37614_p1) + $signed(51'd2246508413976576));

assign add_ln703_16_fu_38410_p2 = ($signed(sext_ln703_fu_38407_p1) + $signed(zext_ln728_31_fu_38249_p1));

assign add_ln703_17_fu_38416_p2 = (add_ln703_16_fu_38410_p2 + add_ln703_14_fu_38401_p2);

assign add_ln703_19_fu_37722_p2 = (shl_ln728_1_fu_36881_p3 + zext_ln728_4_fu_37017_p1);

assign add_ln703_20_fu_37728_p2 = ($signed(sext_ln728_55_fu_37147_p1) + $signed(zext_ln728_17_fu_37318_p1));

assign add_ln703_21_fu_38431_p2 = ($signed(add_ln703_20_reg_38955) + $signed(sext_ln703_1_fu_38428_p1));

assign add_ln703_22_fu_38436_p2 = (shl_ln728_49_fu_38001_p3 + zext_ln728_28_fu_38145_p1);

assign add_ln703_23_fu_37734_p2 = ($signed(shl_ln728_85_fu_37618_p3) + $signed(52'd4487897226936320));

assign add_ln703_24_fu_37740_p2 = ($signed(add_ln703_23_fu_37734_p2) + $signed(sext_ln728_70_fu_37503_p1));

assign add_ln703_25_fu_38442_p2 = (add_ln703_24_reg_38960 + add_ln703_22_fu_38436_p2);

assign add_ln703_27_fu_37746_p2 = (shl_ln728_2_fu_36889_p3 + shl_ln728_14_fu_37021_p3);

assign add_ln703_28_fu_37752_p2 = (zext_ln728_12_fu_37159_p1 + shl_ln728_38_fu_37322_p3);

assign add_ln703_29_fu_38453_p2 = (add_ln703_28_reg_38970 + add_ln703_27_reg_38965);

assign add_ln703_30_fu_38457_p2 = ($signed(sext_ln728_62_fu_38017_p1) + $signed(shl_ln728_62_fu_38149_p3));

assign add_ln703_31_fu_37758_p2 = (shl_ln728_86_fu_37626_p3 + 52'd50989851738112);

assign add_ln703_32_fu_37764_p2 = (add_ln703_31_fu_37758_p2 + shl_ln728_74_fu_37507_p3);

assign add_ln703_33_fu_38463_p2 = (add_ln703_32_reg_38975 + add_ln703_30_fu_38457_p2);

assign add_ln703_35_fu_37770_p2 = (zext_ln728_1_fu_36905_p1 + zext_ln728_5_fu_37037_p1);

assign add_ln703_36_fu_37776_p2 = (shl_ln728_27_fu_37163_p3 + zext_ln728_18_fu_37344_p1);

assign add_ln703_37_fu_38474_p2 = (add_ln703_36_reg_38985 + add_ln703_35_reg_38980);

assign add_ln703_38_fu_38478_p2 = (zext_ln728_23_fu_38029_p1 + shl_ln728_63_fu_38157_p3);

assign add_ln703_39_fu_37782_p2 = ($signed(shl_ln728_87_fu_37634_p3) + $signed(52'd4491762697502720));

assign add_ln703_40_fu_37788_p2 = ($signed(add_ln703_39_fu_37782_p2) + $signed(sext_ln728_71_fu_37523_p1));

assign add_ln703_41_fu_38484_p2 = (add_ln703_40_reg_38990 + add_ln703_38_fu_38478_p2);

assign add_ln703_43_fu_37794_p2 = (shl_ln728_4_fu_36909_p3 + shl_ln728_16_fu_37041_p3);

assign add_ln703_44_fu_37800_p2 = ($signed(sext_ln728_56_fu_37179_p1) + $signed(zext_ln728_19_fu_37356_p1));

assign add_ln703_45_fu_38495_p2 = (add_ln703_44_reg_39000 + add_ln703_43_reg_38995);

assign add_ln703_46_fu_38499_p2 = (shl_ln728_52_fu_38033_p3 + zext_ln728_29_fu_38173_p1);

assign add_ln703_47_fu_38505_p2 = ($signed(zext_ln1118_33_fu_38325_p1) + $signed(51'd2240735977930752));

assign add_ln703_48_fu_38511_p2 = ($signed(add_ln703_47_fu_38505_p2) + $signed(sext_ln1118_1_fu_38261_p1));

assign add_ln703_49_fu_38521_p2 = ($signed(sext_ln703_2_fu_38517_p1) + $signed(add_ln703_46_fu_38499_p2));

assign add_ln703_4_fu_38369_p2 = ($signed(zext_ln728_10_fu_37942_p1) + $signed(sext_ln728_58_fu_37965_p1));

assign add_ln703_51_fu_37806_p2 = (shl_ln728_5_fu_36917_p3 + zext_ln728_6_fu_37057_p1);

assign add_ln703_52_fu_37812_p2 = ($signed(shl_ln728_29_fu_37183_p3) + $signed(sext_ln728_59_fu_37368_p1));

assign add_ln703_53_fu_38536_p2 = ($signed(add_ln703_52_reg_39010) + $signed(sext_ln703_3_fu_38533_p1));

assign add_ln703_54_fu_38541_p2 = ($signed(sext_ln728_63_fu_38049_p1) + $signed(shl_ln728_65_fu_38177_p3));

assign add_ln703_55_fu_38547_p2 = ($signed(sext_ln728_72_fu_38365_p1) + $signed(52'd4501641122283520));

assign add_ln703_56_fu_38553_p2 = (add_ln703_55_fu_38547_p2 + zext_ln728_32_fu_38273_p1);

assign add_ln703_57_fu_38559_p2 = (add_ln703_56_fu_38553_p2 + add_ln703_54_fu_38541_p2);

assign add_ln703_59_fu_37818_p2 = (shl_ln728_6_fu_36925_p3 + zext_ln728_7_fu_37069_p1);

assign add_ln703_5_fu_38375_p2 = (add_ln703_4_fu_38369_p2 + add_ln703_reg_38925);

assign add_ln703_60_fu_37824_p2 = (shl_ln728_30_fu_37191_p3 + zext_ln728_20_fu_37380_p1);

assign add_ln703_61_fu_38571_p2 = (add_ln703_60_reg_39020 + add_ln703_59_reg_39015);

assign add_ln703_62_fu_38575_p2 = ($signed(zext_ln728_24_fu_38061_p1) + $signed(sext_ln728_67_fu_38193_p1));

assign add_ln703_63_fu_37830_p2 = ($signed(zext_ln728_36_fu_37650_p1) + $signed(52'd4486935154262016));

assign add_ln703_64_fu_37836_p2 = (add_ln703_63_fu_37830_p2 + shl_ln728_78_fu_37527_p3);

assign add_ln703_65_fu_38581_p2 = (add_ln703_64_reg_39025 + add_ln703_62_fu_38575_p2);

assign add_ln703_67_fu_37842_p2 = (zext_ln728_2_fu_36941_p1 + zext_ln728_8_fu_37081_p1);

assign add_ln703_68_fu_37848_p2 = (zext_ln728_13_fu_37213_p1 + zext_ln728_21_fu_37392_p1);

assign add_ln703_69_fu_38595_p2 = (zext_ln703_fu_38592_p1 + add_ln703_67_reg_39030);

assign add_ln703_6_fu_38380_p2 = ($signed(sext_ln728_61_fu_37989_p1) + $signed(zext_ln728_27_fu_38121_p1));

assign add_ln703_70_fu_38600_p2 = ($signed(sext_ln728_64_fu_38073_p1) + $signed(shl_ln728_67_fu_38197_p3));

assign add_ln703_71_fu_37854_p2 = ($signed(shl_ln728_91_fu_37654_p3) + $signed(52'd4483877137547264));

assign add_ln703_72_fu_37860_p2 = (add_ln703_71_fu_37854_p2 + zext_ln728_33_fu_37548_p1);

assign add_ln703_73_fu_38606_p2 = (add_ln703_72_reg_39040 + add_ln703_70_fu_38600_p2);

assign add_ln703_75_fu_37866_p2 = ($signed(shl_ln728_8_fu_36945_p3) + $signed(sext_ln728_54_fu_37093_p1));

assign add_ln703_76_fu_38617_p2 = ($signed(zext_ln728_14_fu_37954_p1) + $signed(sext_ln728_60_fu_37977_p1));

assign add_ln703_77_fu_38627_p2 = ($signed(sext_ln703_4_fu_38623_p1) + $signed(add_ln703_75_reg_39045));

assign add_ln703_78_fu_38632_p2 = ($signed(zext_ln728_25_fu_38085_p1) + $signed(sext_ln728_68_fu_38213_p1));

assign add_ln703_79_fu_37872_p2 = ($signed(shl_ln728_92_fu_37662_p3) + $signed(52'd4482227870105600));

assign add_ln703_7_fu_37692_p2 = ($signed(zext_ln728_35_fu_37602_p1) + $signed(52'd4498308227661824));

assign add_ln703_80_fu_37878_p2 = (add_ln703_79_fu_37872_p2 + shl_ln728_80_fu_37552_p3);

assign add_ln703_81_fu_38638_p2 = (add_ln703_80_reg_39050 + add_ln703_78_fu_38632_p2);

assign add_ln703_83_fu_37884_p2 = ($signed(sext_ln728_53_fu_36961_p1) + $signed(shl_ln728_21_fu_37097_p3));

assign add_ln703_84_fu_37890_p2 = ($signed(sext_ln728_57_fu_37225_p1) + $signed(zext_ln728_22_fu_37404_p1));

assign add_ln703_85_fu_38652_p2 = ($signed(add_ln703_84_reg_39060) + $signed(sext_ln703_5_fu_38649_p1));

assign add_ln703_86_fu_38657_p2 = ($signed(zext_ln728_26_fu_38097_p1) + $signed(sext_ln728_69_fu_38225_p1));

assign add_ln703_87_fu_37896_p2 = ($signed(shl_ln728_93_fu_37670_p3) + $signed(49'd547041394556928));

assign add_ln703_88_fu_38666_p2 = ($signed(sext_ln703_6_fu_38663_p1) + $signed(zext_ln1118_26_fu_38285_p1));

assign add_ln703_89_fu_38676_p2 = ($signed(sext_ln703_7_fu_38672_p1) + $signed(add_ln703_86_fu_38657_p2));

assign add_ln703_8_fu_37698_p2 = (add_ln703_7_fu_37692_p2 + shl_ln728_71_fu_37487_p3);

assign add_ln703_91_fu_38688_p2 = (zext_ln728_9_fu_37930_p1 + shl_ln728_10_fu_37914_p3);

assign add_ln703_92_fu_37902_p2 = (zext_ln728_15_fu_37237_p1 + shl_ln728_46_fu_37408_p3);

assign add_ln703_93_fu_38697_p2 = ($signed(sext_ln703_8_fu_38694_p1) + $signed(add_ln703_91_fu_38688_p2));

assign add_ln703_94_fu_38703_p2 = ($signed(sext_ln728_65_fu_38109_p1) + $signed(zext_ln728_30_fu_38237_p1));

assign add_ln703_95_fu_37908_p2 = (shl_ln728_82_fu_37560_p3 + shl_ln728_94_fu_37678_p3);

assign add_ln703_96_fu_38709_p2 = (add_ln703_95_reg_39075 + add_ln703_94_fu_38703_p2);

assign add_ln703_9_fu_38386_p2 = (add_ln703_8_reg_38930 + add_ln703_6_fu_38380_p2);

assign add_ln703_fu_37686_p2 = ($signed(sext_ln728_fu_36865_p1) + $signed(shl_ln728_11_fu_36987_p3));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1118_10_fu_362_p0 = zext_ln1118_7_fu_37105_p1;

assign mul_ln1118_10_fu_362_p2 = ($signed({{1'b0}, {mul_ln1118_10_fu_362_p0}}) * $signed(-'h94E));

assign mul_ln1118_11_fu_397_p0 = zext_ln1118_8_fu_37114_p1;

assign mul_ln1118_11_fu_397_p2 = ($signed({{1'b0}, {mul_ln1118_11_fu_397_p0}}) * $signed(-'h1642));

assign mul_ln1118_12_fu_398_p0 = zext_ln1118_8_fu_37114_p1;

assign mul_ln1118_12_fu_398_p2 = ($signed({{1'b0}, {mul_ln1118_12_fu_398_p0}}) * $signed(-'h1DC4));

assign mul_ln1118_13_fu_377_p0 = zext_ln1118_7_fu_37105_p1;

assign mul_ln1118_13_fu_377_p2 = ($signed({{1'b0}, {mul_ln1118_13_fu_377_p0}}) * $signed(-'hA18));

assign mul_ln1118_14_fu_346_p0 = zext_ln728_16_fu_37241_p1;

assign mul_ln1118_14_fu_346_p2 = ($signed({{1'b0}, {mul_ln1118_14_fu_346_p0}}) * $signed(-'h13EC));

assign mul_ln1118_15_fu_386_p0 = zext_ln1118_12_fu_37252_p1;

assign mul_ln1118_15_fu_386_p2 = ($signed({{1'b0}, {mul_ln1118_15_fu_386_p0}}) * $signed(-'h86E));

assign mul_ln1118_16_fu_356_p0 = mul_ln1118_16_fu_356_p00;

assign mul_ln1118_16_fu_356_p00 = data_3_V_read;

assign mul_ln1118_16_fu_356_p2 = ($signed({{1'b0}, {mul_ln1118_16_fu_356_p0}}) * $signed(-'h28D));

assign mul_ln1118_17_fu_372_p0 = zext_ln1118_12_fu_37252_p1;

assign mul_ln1118_17_fu_372_p2 = ($signed({{1'b0}, {mul_ln1118_17_fu_372_p0}}) * $signed(-'hCC6));

assign mul_ln1118_18_fu_417_p0 = zext_ln1118_18_fu_37431_p1;

assign mul_ln1118_18_fu_417_p2 = ($signed({{1'b0}, {mul_ln1118_18_fu_417_p0}}) * $signed(-'h65D));

assign mul_ln1118_19_fu_402_p0 = zext_ln1118_17_fu_37424_p1;

assign mul_ln1118_19_fu_402_p2 = ($signed({{1'b0}, {mul_ln1118_19_fu_402_p0}}) * $signed(-'h1656));

assign mul_ln1118_1_fu_412_p0 = zext_ln1118_3_fu_36849_p1;

assign mul_ln1118_1_fu_412_p2 = ($signed({{1'b0}, {mul_ln1118_1_fu_412_p0}}) * $signed(-'h5F9));

assign mul_ln1118_20_fu_373_p0 = zext_ln1118_18_fu_37431_p1;

assign mul_ln1118_20_fu_373_p2 = ($signed({{1'b0}, {mul_ln1118_20_fu_373_p0}}) * $signed(-'h496));

assign mul_ln1118_21_fu_361_p0 = zext_ln1118_17_fu_37424_p1;

assign mul_ln1118_21_fu_361_p2 = ($signed({{1'b0}, {mul_ln1118_21_fu_361_p0}}) * $signed(-'h14A0));

assign mul_ln1118_22_fu_359_p0 = zext_ln1118_16_fu_37416_p1;

assign mul_ln1118_22_fu_359_p2 = ($signed({{1'b0}, {mul_ln1118_22_fu_359_p0}}) * $signed(-'hAE6));

assign mul_ln1118_23_fu_375_p0 = zext_ln1118_18_fu_37431_p1;

assign mul_ln1118_23_fu_375_p2 = ($signed({{1'b0}, {mul_ln1118_23_fu_375_p0}}) * $signed(-'h43D));

assign mul_ln1118_24_fu_382_p0 = zext_ln1118_18_fu_37431_p1;

assign mul_ln1118_24_fu_382_p2 = ($signed({{1'b0}, {mul_ln1118_24_fu_382_p0}}) * $signed(-'h6AC));

assign mul_ln1118_25_fu_399_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln1118_25_fu_399_p2 = ($signed({{1'b0}, {mul_ln1118_25_fu_399_p0}}) * $signed(-'h90E));

assign mul_ln1118_26_fu_343_p0 = zext_ln1118_21_fu_37456_p1;

assign mul_ln1118_26_fu_343_p2 = ($signed({{1'b0}, {mul_ln1118_26_fu_343_p0}}) * $signed(-'h1CBE));

assign mul_ln1118_27_fu_383_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln1118_27_fu_383_p2 = ($signed({{1'b0}, {mul_ln1118_27_fu_383_p0}}) * $signed(-'hA1E));

assign mul_ln1118_28_fu_376_p0 = zext_ln1118_21_fu_37456_p1;

assign mul_ln1118_28_fu_376_p2 = ($signed({{1'b0}, {mul_ln1118_28_fu_376_p0}}) * $signed(-'h1928));

assign mul_ln1118_29_fu_370_p0 = mul_ln1118_29_fu_370_p00;

assign mul_ln1118_29_fu_370_p00 = data_5_V_read;

assign mul_ln1118_29_fu_370_p2 = ($signed({{1'b0}, {mul_ln1118_29_fu_370_p0}}) * $signed(-'h3D8));

assign mul_ln1118_2_fu_363_p0 = zext_ln1118_1_fu_36834_p1;

assign mul_ln1118_2_fu_363_p2 = ($signed({{1'b0}, {mul_ln1118_2_fu_363_p0}}) * $signed(-'hF68));

assign mul_ln1118_30_fu_371_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln1118_30_fu_371_p2 = ($signed({{1'b0}, {mul_ln1118_30_fu_371_p0}}) * $signed(-'hDBA));

assign mul_ln1118_31_fu_349_p0 = zext_ln1118_23_fu_37471_p1;

assign mul_ln1118_31_fu_349_p2 = ($signed({{1'b0}, {mul_ln1118_31_fu_349_p0}}) * $signed(-'h878));

assign mul_ln1118_32_fu_409_p0 = zext_ln1118_24_fu_37478_p1;

assign mul_ln1118_32_fu_409_p2 = ($signed({{1'b0}, {mul_ln1118_32_fu_409_p0}}) * $signed(-'h1AF5));

assign mul_ln1118_33_fu_400_p0 = zext_ln1118_23_fu_37471_p1;

assign mul_ln1118_33_fu_400_p2 = ($signed({{1'b0}, {mul_ln1118_33_fu_400_p0}}) * $signed(-'hE34));

assign mul_ln1118_34_fu_416_p0 = zext_ln1118_22_fu_37464_p1;

assign mul_ln1118_34_fu_416_p2 = ($signed({{1'b0}, {mul_ln1118_34_fu_416_p0}}) * $signed(-'h2F6));

assign mul_ln1118_35_fu_351_p0 = zext_ln1118_24_fu_37478_p1;

assign mul_ln1118_35_fu_351_p2 = ($signed({{1'b0}, {mul_ln1118_35_fu_351_p0}}) * $signed(-'h132D));

assign mul_ln1118_36_fu_366_p0 = zext_ln1118_24_fu_37478_p1;

assign mul_ln1118_36_fu_366_p2 = ($signed({{1'b0}, {mul_ln1118_36_fu_366_p0}}) * $signed(-'h1BC8));

assign mul_ln1118_37_fu_419_p0 = zext_ln1118_27_fu_37573_p1;

assign mul_ln1118_37_fu_419_p2 = ($signed({{1'b0}, {mul_ln1118_37_fu_419_p0}}) * $signed(-'h1CCE));

assign mul_ln1118_38_fu_413_p0 = mul_ln1118_38_fu_413_p00;

assign mul_ln1118_38_fu_413_p00 = data_7_V_read;

assign mul_ln1118_38_fu_413_p2 = ($signed({{1'b0}, {mul_ln1118_38_fu_413_p0}}) * $signed(-'h2A8));

assign mul_ln1118_3_fu_354_p0 = zext_ln1118_2_fu_36840_p1;

assign mul_ln1118_3_fu_354_p2 = ($signed({{1'b0}, {mul_ln1118_3_fu_354_p0}}) * $signed(-'h14D1));

assign mul_ln1118_4_fu_403_p0 = mul_ln1118_4_fu_403_p00;

assign mul_ln1118_4_fu_403_p00 = data_0_V_read;

assign mul_ln1118_4_fu_403_p2 = ($signed({{1'b0}, {mul_ln1118_4_fu_403_p0}}) * $signed(-'h348));

assign mul_ln1118_5_fu_401_p0 = zext_ln1118_2_fu_36840_p1;

assign mul_ln1118_5_fu_401_p2 = ($signed({{1'b0}, {mul_ln1118_5_fu_401_p0}}) * $signed(-'h16A2));

assign mul_ln1118_6_fu_380_p0 = zext_ln1118_4_fu_36970_p1;

assign mul_ln1118_6_fu_380_p2 = ($signed({{1'b0}, {mul_ln1118_6_fu_380_p0}}) * $signed(-'hC38));

assign mul_ln1118_7_fu_381_p0 = zext_ln1118_4_fu_36970_p1;

assign mul_ln1118_7_fu_381_p2 = ($signed({{1'b0}, {mul_ln1118_7_fu_381_p0}}) * $signed(-'hAD8));

assign mul_ln1118_8_fu_336_p0 = zext_ln1118_7_fu_37105_p1;

assign mul_ln1118_8_fu_336_p2 = ($signed({{1'b0}, {mul_ln1118_8_fu_336_p0}}) * $signed(-'hA99));

assign mul_ln1118_9_fu_404_p0 = zext_ln1118_8_fu_37114_p1;

assign mul_ln1118_9_fu_404_p2 = ($signed({{1'b0}, {mul_ln1118_9_fu_404_p0}}) * $signed(-'h12B4));

assign mul_ln1118_fu_389_p0 = zext_ln1118_3_fu_36849_p1;

assign mul_ln1118_fu_389_p2 = ($signed({{1'b0}, {mul_ln1118_fu_389_p0}}) * $signed(-'h720));

assign mul_ln728_10_fu_408_p0 = zext_ln1118_5_fu_36979_p1;

assign mul_ln728_10_fu_408_p2 = ($signed({{1'b0}, {mul_ln728_10_fu_408_p0}}) * $signed(-'h21E0));

assign mul_ln728_11_fu_396_p0 = zext_ln1118_6_fu_37003_p1;

assign mul_ln728_11_fu_396_p2 = (mul_ln728_11_fu_396_p0 * $signed('h704));

assign mul_ln728_12_fu_394_p0 = zext_ln1118_5_fu_36979_p1;

assign mul_ln728_12_fu_394_p2 = (mul_ln728_12_fu_394_p0 * $signed('h2108));

assign mul_ln728_13_fu_421_p0 = zext_ln1118_4_fu_36970_p1;

assign mul_ln728_13_fu_421_p2 = (mul_ln728_13_fu_421_p0 * $signed('h19FA));

assign mul_ln728_14_fu_342_p0 = zext_ln1118_5_fu_36979_p1;

assign mul_ln728_14_fu_342_p2 = ($signed({{1'b0}, {mul_ln728_14_fu_342_p0}}) * $signed(-'h263C));

assign mul_ln728_15_fu_350_p0 = zext_ln1118_6_fu_37003_p1;

assign mul_ln728_15_fu_350_p2 = (mul_ln728_15_fu_350_p0 * $signed('h60E));

assign mul_ln728_16_fu_427_p0 = zext_ln1118_4_fu_36970_p1;

assign mul_ln728_16_fu_427_p2 = (mul_ln728_16_fu_427_p0 * $signed('h1924));

assign mul_ln728_17_fu_425_p0 = zext_ln1118_4_fu_36970_p1;

assign mul_ln728_17_fu_425_p2 = (mul_ln728_17_fu_425_p0 * $signed('h1AE7));

assign mul_ln728_18_fu_393_p0 = mul_ln728_18_fu_393_p00;

assign mul_ln728_18_fu_393_p00 = data_1_V_read;

assign mul_ln728_18_fu_393_p2 = (mul_ln728_18_fu_393_p0 * $signed('h3EE));

assign mul_ln728_19_fu_364_p0 = zext_ln1118_7_fu_37105_p1;

assign mul_ln728_19_fu_364_p2 = (mul_ln728_19_fu_364_p0 * $signed('h1383));

assign mul_ln728_20_fu_388_p0 = zext_ln1118_9_fu_37121_p1;

assign mul_ln728_20_fu_388_p2 = (mul_ln728_20_fu_388_p0 * $signed('h5BC));

assign mul_ln728_21_fu_390_p0 = zext_ln1118_7_fu_37105_p1;

assign mul_ln728_21_fu_390_p2 = (mul_ln728_21_fu_390_p0 * $signed('h1302));

assign mul_ln728_22_fu_339_p0 = zext_ln1118_10_fu_37199_p1;

assign mul_ln728_22_fu_339_p2 = (mul_ln728_22_fu_339_p0 * $signed('hDE8));

assign mul_ln728_23_fu_348_p0 = zext_ln1118_10_fu_37199_p1;

assign mul_ln728_23_fu_348_p2 = (mul_ln728_23_fu_348_p0 * $signed('hA18));

assign mul_ln728_24_fu_406_p0 = zext_ln1118_9_fu_37121_p1;

assign mul_ln728_24_fu_406_p2 = (mul_ln728_24_fu_406_p0 * $signed('h53B));

assign mul_ln728_25_fu_407_p0 = zext_ln728_16_fu_37241_p1;

assign mul_ln728_25_fu_407_p2 = ($signed({{1'b0}, {mul_ln728_25_fu_407_p0}}) * $signed(-'h203E));

assign mul_ln728_26_fu_423_p0 = zext_ln1118_12_fu_37252_p1;

assign mul_ln728_26_fu_423_p2 = (mul_ln728_26_fu_423_p0 * $signed('h1BD6));

assign mul_ln728_27_fu_414_p0 = zext_ln1118_15_fu_37330_p1;

assign mul_ln728_27_fu_414_p2 = (mul_ln728_27_fu_414_p0 * $signed('hC70));

assign mul_ln728_28_fu_415_p0 = zext_ln1118_12_fu_37252_p1;

assign mul_ln728_28_fu_415_p2 = (mul_ln728_28_fu_415_p0 * $signed('h157F));

assign mul_ln728_29_fu_379_p0 = zext_ln1118_12_fu_37252_p1;

assign mul_ln728_29_fu_379_p2 = (mul_ln728_29_fu_379_p0 * $signed('h1222));

assign mul_ln728_30_fu_337_p0 = zext_ln1118_15_fu_37330_p1;

assign mul_ln728_30_fu_337_p2 = (mul_ln728_30_fu_337_p0 * $signed('h9EE));

assign mul_ln728_31_fu_341_p0 = zext_ln1118_12_fu_37252_p1;

assign mul_ln728_31_fu_341_p2 = (mul_ln728_31_fu_341_p0 * $signed('h1D63));

assign mul_ln728_32_fu_431_p0 = zext_ln1118_17_fu_37424_p1;

assign mul_ln728_32_fu_431_p2 = (mul_ln728_32_fu_431_p0 * $signed('h202E));

assign mul_ln728_33_fu_429_p0 = zext_ln1118_18_fu_37431_p1;

assign mul_ln728_33_fu_429_p2 = (mul_ln728_33_fu_429_p0 * $signed('hE6C));

assign mul_ln728_34_fu_411_p0 = zext_ln1118_16_fu_37416_p1;

assign mul_ln728_34_fu_411_p2 = (mul_ln728_34_fu_411_p0 * $signed('h1F84));

assign mul_ln728_35_fu_338_p0 = zext_ln1118_16_fu_37416_p1;

assign mul_ln728_35_fu_338_p2 = (mul_ln728_35_fu_338_p0 * $signed('h10EA));

assign mul_ln728_36_fu_352_p0 = zext_ln1118_16_fu_37416_p1;

assign mul_ln728_36_fu_352_p2 = (mul_ln728_36_fu_352_p0 * $signed('h19A0));

assign mul_ln728_37_fu_353_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln728_37_fu_353_p2 = (mul_ln728_37_fu_353_p0 * $signed('h1724));

assign mul_ln728_38_fu_345_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln728_38_fu_345_p2 = (mul_ln728_38_fu_345_p0 * $signed('h14BA));

assign mul_ln728_39_fu_368_p0 = zext_ln1118_21_fu_37456_p1;

assign mul_ln728_39_fu_368_p2 = ($signed({{1'b0}, {mul_ln728_39_fu_368_p0}}) * $signed(-'h2388));

assign mul_ln728_40_fu_360_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln728_40_fu_360_p2 = (mul_ln728_40_fu_360_p0 * $signed('h16EE));

assign mul_ln728_41_fu_385_p0 = zext_ln1118_21_fu_37456_p1;

assign mul_ln728_41_fu_385_p2 = (mul_ln728_41_fu_385_p0 * $signed('h24EB));

assign mul_ln728_42_fu_369_p0 = zext_ln1118_20_fu_37445_p1;

assign mul_ln728_42_fu_369_p2 = (mul_ln728_42_fu_369_p0 * $signed('h1C9A));

assign mul_ln728_43_fu_367_p0 = zext_ln1118_24_fu_37478_p1;

assign mul_ln728_43_fu_367_p2 = ($signed({{1'b0}, {mul_ln728_43_fu_367_p0}}) * $signed(-'h2350));

assign mul_ln728_44_fu_378_p0 = zext_ln1118_23_fu_37471_p1;

assign mul_ln728_44_fu_378_p2 = (mul_ln728_44_fu_378_p0 * $signed('h1D52));

assign mul_ln728_45_fu_387_p0 = zext_ln1118_22_fu_37464_p1;

assign mul_ln728_45_fu_387_p2 = (mul_ln728_45_fu_387_p0 * $signed('h59B));

assign mul_ln728_46_fu_358_p0 = zext_ln1118_24_fu_37478_p1;

assign mul_ln728_46_fu_358_p2 = (mul_ln728_46_fu_358_p0 * $signed('h27C3));

assign mul_ln728_47_fu_344_p0 = mul_ln728_47_fu_344_p00;

assign mul_ln728_47_fu_344_p00 = data_6_V_read;

assign mul_ln728_47_fu_344_p2 = (mul_ln728_47_fu_344_p0 * $signed('hE47));

assign mul_ln728_48_fu_395_p0 = zext_ln1118_22_fu_37464_p1;

assign mul_ln728_48_fu_395_p2 = (mul_ln728_48_fu_395_p0 * $signed('h797));

assign mul_ln728_49_fu_426_p0 = zext_ln1118_29_fu_37588_p1;

assign mul_ln728_49_fu_426_p2 = (mul_ln728_49_fu_426_p0 * $signed('h13EF));

assign mul_ln728_4_fu_420_p0 = zext_ln1118_2_fu_36840_p1;

assign mul_ln728_4_fu_420_p2 = ($signed({{1'b0}, {mul_ln728_4_fu_420_p0}}) * $signed(-'h20B6));

assign mul_ln728_50_fu_391_p0 = mul_ln728_50_fu_391_p00;

assign mul_ln728_50_fu_391_p00 = data_7_V_read;

assign mul_ln728_50_fu_391_p2 = (mul_ln728_50_fu_391_p0 * $signed('hB1E));

assign mul_ln728_51_fu_410_p0 = zext_ln1118_27_fu_37573_p1;

assign mul_ln728_51_fu_410_p2 = (mul_ln728_51_fu_410_p0 * $signed('h2310));

assign mul_ln728_52_fu_374_p0 = zext_ln1118_27_fu_37573_p1;

assign mul_ln728_52_fu_374_p2 = (mul_ln728_52_fu_374_p0 * $signed('h249E));

assign mul_ln728_53_fu_428_p0 = zext_ln1118_27_fu_37573_p1;

assign mul_ln728_53_fu_428_p2 = (mul_ln728_53_fu_428_p0 * $signed('h21FC));

assign mul_ln728_54_fu_424_p0 = zext_ln1118_29_fu_37588_p1;

assign mul_ln728_54_fu_424_p2 = (mul_ln728_54_fu_424_p0 * $signed('h1368));

assign mul_ln728_55_fu_422_p0 = zext_ln1118_27_fu_37573_p1;

assign mul_ln728_55_fu_422_p2 = ($signed({{1'b0}, {mul_ln728_55_fu_422_p0}}) * $signed(-'h26A8));

assign mul_ln728_56_fu_347_p0 = zext_ln1118_27_fu_37573_p1;

assign mul_ln728_56_fu_347_p2 = ($signed({{1'b0}, {mul_ln728_56_fu_347_p0}}) * $signed(-'h2214));

assign mul_ln728_5_fu_384_p0 = zext_ln1118_3_fu_36849_p1;

assign mul_ln728_5_fu_384_p2 = (mul_ln728_5_fu_384_p0 * $signed('h8A8));

assign mul_ln728_6_fu_405_p0 = zext_ln1118_2_fu_36840_p1;

assign mul_ln728_6_fu_405_p2 = ($signed({{1'b0}, {mul_ln728_6_fu_405_p0}}) * $signed(-'h22EE));

assign mul_ln728_7_fu_355_p0 = zext_ln1118_3_fu_36849_p1;

assign mul_ln728_7_fu_355_p2 = (mul_ln728_7_fu_355_p0 * $signed('hB84));

assign mul_ln728_8_fu_340_p0 = zext_ln1118_2_fu_36840_p1;

assign mul_ln728_8_fu_340_p2 = (mul_ln728_8_fu_340_p0 * $signed('h21F8));

assign mul_ln728_9_fu_430_p0 = zext_ln1118_5_fu_36979_p1;

assign mul_ln728_9_fu_430_p2 = ($signed({{1'b0}, {mul_ln728_9_fu_430_p0}}) * $signed(-'h24A8));

assign mul_ln728_fu_365_p0 = zext_ln1118_1_fu_36834_p1;

assign mul_ln728_fu_365_p2 = (mul_ln728_fu_365_p0 * $signed('h1668));

assign p_Val2_s_fu_38391_p2 = (add_ln703_9_fu_38386_p2 + add_ln703_5_fu_38375_p2);

assign sext_ln1118_1_fu_38261_p1 = $signed(shl_ln728_76_fu_38253_p3);

assign sext_ln1118_fu_37280_p1 = $signed(sub_ln1118_fu_37274_p2);

assign sext_ln703_1_fu_38428_p1 = $signed(add_ln703_19_reg_38950);

assign sext_ln703_2_fu_38517_p1 = $signed(add_ln703_48_fu_38511_p2);

assign sext_ln703_3_fu_38533_p1 = $signed(add_ln703_51_reg_39005);

assign sext_ln703_4_fu_38623_p1 = $signed(add_ln703_76_fu_38617_p2);

assign sext_ln703_5_fu_38649_p1 = $signed(add_ln703_83_reg_39055);

assign sext_ln703_6_fu_38663_p1 = $signed(add_ln703_87_reg_39065);

assign sext_ln703_7_fu_38672_p1 = $signed(add_ln703_88_fu_38666_p2);

assign sext_ln703_8_fu_38694_p1 = $signed(add_ln703_92_reg_39070);

assign sext_ln703_fu_38407_p1 = $signed(add_ln703_15_reg_38945);

assign sext_ln728_53_fu_36961_p1 = $signed(shl_ln728_9_fu_36953_p3);

assign sext_ln728_54_fu_37093_p1 = $signed(shl_ln728_20_fu_37085_p3);

assign sext_ln728_55_fu_37147_p1 = $signed(shl_ln728_25_fu_37139_p3);

assign sext_ln728_56_fu_37179_p1 = $signed(shl_ln728_28_fu_37171_p3);

assign sext_ln728_57_fu_37225_p1 = $signed(shl_ln728_33_fu_37217_p3);

assign sext_ln728_58_fu_37965_p1 = $signed(shl_ln728_35_fu_37958_p3);

assign sext_ln728_59_fu_37368_p1 = $signed(shl_ln728_41_fu_37360_p3);

assign sext_ln728_60_fu_37977_p1 = $signed(shl_ln728_44_fu_37969_p3);

assign sext_ln728_61_fu_37989_p1 = $signed(shl_ln728_47_fu_37981_p3);

assign sext_ln728_62_fu_38017_p1 = $signed(shl_ln728_50_fu_38009_p3);

assign sext_ln728_63_fu_38049_p1 = $signed(shl_ln728_53_fu_38041_p3);

assign sext_ln728_64_fu_38073_p1 = $signed(shl_ln728_55_fu_38065_p3);

assign sext_ln728_65_fu_38109_p1 = $signed(shl_ln728_58_fu_38101_p3);

assign sext_ln728_66_fu_38133_p1 = $signed(shl_ln728_60_fu_38125_p3);

assign sext_ln728_67_fu_38193_p1 = $signed(shl_ln728_66_fu_38185_p3);

assign sext_ln728_68_fu_38213_p1 = $signed(shl_ln728_68_fu_38205_p3);

assign sext_ln728_69_fu_38225_p1 = $signed(shl_ln728_69_fu_38217_p3);

assign sext_ln728_70_fu_37503_p1 = $signed(shl_ln728_73_fu_37495_p3);

assign sext_ln728_71_fu_37523_p1 = $signed(shl_ln728_75_fu_37515_p3);

assign sext_ln728_72_fu_38365_p1 = $signed(shl_ln728_89_fu_38357_p3);

assign sext_ln728_fu_36865_p1 = $signed(shl_ln_fu_36857_p3);

assign shl_ln1118_1_fu_38289_p3 = {{data_7_V_read_12_reg_38912}, {11'd0}};

assign shl_ln1118_2_fu_38300_p3 = {{data_7_V_read_12_reg_38912}, {3'd0}};

assign shl_ln1118_3_fu_38329_p3 = {{data_7_V_read_12_reg_38912}, {12'd0}};

assign shl_ln1118_4_fu_38340_p3 = {{data_7_V_read_12_reg_38912}, {4'd0}};

assign shl_ln1118_s_fu_37284_p3 = {{data_3_V_read}, {4'd0}};

assign shl_ln1_fu_37262_p3 = {{data_3_V_read}, {8'd0}};

assign shl_ln728_10_fu_37914_p3 = {{mul_ln1118_5_reg_36549}, {24'd0}};

assign shl_ln728_11_fu_36987_p3 = {{mul_ln728_9_fu_430_p2}, {24'd0}};

assign shl_ln728_12_fu_36995_p3 = {{mul_ln728_10_fu_408_p2}, {24'd0}};

assign shl_ln728_13_fu_37009_p3 = {{mul_ln728_11_fu_396_p2}, {24'd0}};

assign shl_ln728_14_fu_37021_p3 = {{mul_ln728_12_fu_394_p2}, {24'd0}};

assign shl_ln728_15_fu_37029_p3 = {{mul_ln728_13_fu_421_p2}, {24'd0}};

assign shl_ln728_16_fu_37041_p3 = {{mul_ln728_14_fu_342_p2}, {24'd0}};

assign shl_ln728_17_fu_37049_p3 = {{mul_ln728_15_fu_350_p2}, {24'd0}};

assign shl_ln728_18_fu_37061_p3 = {{mul_ln728_16_fu_427_p2}, {24'd0}};

assign shl_ln728_19_fu_37073_p3 = {{mul_ln728_17_fu_425_p2}, {24'd0}};

assign shl_ln728_1_fu_36881_p3 = {{mul_ln1118_1_fu_412_p2}, {24'd0}};

assign shl_ln728_20_fu_37085_p3 = {{mul_ln1118_6_fu_380_p2}, {24'd0}};

assign shl_ln728_21_fu_37097_p3 = {{mul_ln1118_7_fu_381_p2}, {24'd0}};

assign shl_ln728_22_fu_37922_p3 = {{mul_ln728_18_reg_36586}, {24'd0}};

assign shl_ln728_23_fu_37934_p3 = {{mul_ln728_19_reg_36590}, {24'd0}};

assign shl_ln728_24_fu_37127_p3 = {{mul_ln728_20_fu_388_p2}, {24'd0}};

assign shl_ln728_25_fu_37139_p3 = {{mul_ln1118_8_fu_336_p2}, {24'd0}};

assign shl_ln728_26_fu_37151_p3 = {{mul_ln728_21_fu_390_p2}, {24'd0}};

assign shl_ln728_27_fu_37163_p3 = {{mul_ln1118_9_fu_404_p2}, {24'd0}};

assign shl_ln728_28_fu_37171_p3 = {{mul_ln1118_10_fu_362_p2}, {24'd0}};

assign shl_ln728_29_fu_37183_p3 = {{mul_ln1118_11_fu_397_p2}, {24'd0}};

assign shl_ln728_2_fu_36889_p3 = {{mul_ln728_4_fu_420_p2}, {24'd0}};

assign shl_ln728_30_fu_37191_p3 = {{mul_ln1118_12_fu_398_p2}, {24'd0}};

assign shl_ln728_31_fu_37205_p3 = {{mul_ln728_22_fu_339_p2}, {24'd0}};

assign shl_ln728_32_fu_37946_p3 = {{mul_ln728_23_reg_36618}, {24'd0}};

assign shl_ln728_33_fu_37217_p3 = {{mul_ln1118_13_fu_377_p2}, {24'd0}};

assign shl_ln728_34_fu_37229_p3 = {{mul_ln728_24_fu_406_p2}, {24'd0}};

assign shl_ln728_35_fu_37958_p3 = {{sub_ln1118_1_reg_38920}, {24'd0}};

assign shl_ln728_36_fu_37302_p3 = {{mul_ln728_25_fu_407_p2}, {24'd0}};

assign shl_ln728_37_fu_37310_p3 = {{mul_ln728_26_fu_423_p2}, {24'd0}};

assign shl_ln728_38_fu_37322_p3 = {{mul_ln1118_14_fu_346_p2}, {24'd0}};

assign shl_ln728_39_fu_37336_p3 = {{mul_ln728_27_fu_414_p2}, {24'd0}};

assign shl_ln728_3_fu_36897_p3 = {{mul_ln728_5_fu_384_p2}, {24'd0}};

assign shl_ln728_40_fu_37348_p3 = {{mul_ln728_28_fu_415_p2}, {24'd0}};

assign shl_ln728_41_fu_37360_p3 = {{mul_ln1118_15_fu_386_p2}, {24'd0}};

assign shl_ln728_42_fu_37372_p3 = {{mul_ln728_29_fu_379_p2}, {24'd0}};

assign shl_ln728_43_fu_37384_p3 = {{mul_ln728_30_fu_337_p2}, {24'd0}};

assign shl_ln728_44_fu_37969_p3 = {{mul_ln1118_16_reg_36652}, {24'd0}};

assign shl_ln728_45_fu_37396_p3 = {{mul_ln728_31_fu_341_p2}, {24'd0}};

assign shl_ln728_46_fu_37408_p3 = {{mul_ln1118_17_fu_372_p2}, {24'd0}};

assign shl_ln728_47_fu_37981_p3 = {{mul_ln1118_18_reg_36662}, {24'd0}};

assign shl_ln728_48_fu_37993_p3 = {{mul_ln728_32_reg_36666}, {24'd0}};

assign shl_ln728_49_fu_38001_p3 = {{mul_ln1118_19_reg_36670}, {24'd0}};

assign shl_ln728_4_fu_36909_p3 = {{mul_ln728_6_fu_405_p2}, {24'd0}};

assign shl_ln728_50_fu_38009_p3 = {{mul_ln1118_20_reg_36674}, {24'd0}};

assign shl_ln728_51_fu_38021_p3 = {{mul_ln728_33_reg_36678}, {24'd0}};

assign shl_ln728_52_fu_38033_p3 = {{mul_ln1118_21_reg_36682}, {24'd0}};

assign shl_ln728_53_fu_38041_p3 = {{mul_ln1118_22_reg_36686}, {24'd0}};

assign shl_ln728_54_fu_38053_p3 = {{mul_ln728_34_reg_36690}, {24'd0}};

assign shl_ln728_55_fu_38065_p3 = {{mul_ln1118_23_reg_36694}, {24'd0}};

assign shl_ln728_56_fu_38077_p3 = {{mul_ln728_35_reg_36698}, {24'd0}};

assign shl_ln728_57_fu_38089_p3 = {{mul_ln728_36_reg_36702}, {24'd0}};

assign shl_ln728_58_fu_38101_p3 = {{mul_ln1118_24_reg_36706}, {24'd0}};

assign shl_ln728_59_fu_38113_p3 = {{mul_ln728_37_reg_36710}, {24'd0}};

assign shl_ln728_5_fu_36917_p3 = {{mul_ln1118_2_fu_363_p2}, {24'd0}};

assign shl_ln728_60_fu_38125_p3 = {{mul_ln1118_25_reg_36714}, {24'd0}};

assign shl_ln728_61_fu_38137_p3 = {{mul_ln728_38_reg_36718}, {24'd0}};

assign shl_ln728_62_fu_38149_p3 = {{mul_ln1118_26_reg_36722}, {24'd0}};

assign shl_ln728_63_fu_38157_p3 = {{mul_ln728_39_reg_36726}, {24'd0}};

assign shl_ln728_64_fu_38165_p3 = {{mul_ln728_40_reg_36730}, {24'd0}};

assign shl_ln728_65_fu_38177_p3 = {{mul_ln728_41_reg_36734}, {24'd0}};

assign shl_ln728_66_fu_38185_p3 = {{mul_ln1118_27_reg_36738}, {24'd0}};

assign shl_ln728_67_fu_38197_p3 = {{mul_ln1118_28_reg_36742}, {24'd0}};

assign shl_ln728_68_fu_38205_p3 = {{mul_ln1118_29_reg_36746}, {24'd0}};

assign shl_ln728_69_fu_38217_p3 = {{mul_ln1118_30_reg_36750}, {24'd0}};

assign shl_ln728_6_fu_36925_p3 = {{mul_ln1118_3_fu_354_p2}, {24'd0}};

assign shl_ln728_70_fu_38229_p3 = {{mul_ln728_42_reg_36754}, {24'd0}};

assign shl_ln728_71_fu_37487_p3 = {{mul_ln728_43_fu_367_p2}, {24'd0}};

assign shl_ln728_72_fu_38241_p3 = {{mul_ln728_44_reg_36761}, {24'd0}};

assign shl_ln728_73_fu_37495_p3 = {{mul_ln1118_31_fu_349_p2}, {24'd0}};

assign shl_ln728_74_fu_37507_p3 = {{mul_ln1118_32_fu_409_p2}, {24'd0}};

assign shl_ln728_75_fu_37515_p3 = {{mul_ln1118_33_fu_400_p2}, {24'd0}};

assign shl_ln728_76_fu_38253_p3 = {{mul_ln1118_34_reg_36774}, {24'd0}};

assign shl_ln728_77_fu_38265_p3 = {{mul_ln728_45_reg_36778}, {24'd0}};

assign shl_ln728_78_fu_37527_p3 = {{mul_ln728_46_fu_358_p2}, {24'd0}};

assign shl_ln728_79_fu_37540_p3 = {{mul_ln728_47_fu_344_p2}, {24'd0}};

assign shl_ln728_7_fu_36933_p3 = {{mul_ln728_7_fu_355_p2}, {24'd0}};

assign shl_ln728_80_fu_37552_p3 = {{mul_ln1118_35_fu_351_p2}, {24'd0}};

assign shl_ln728_81_fu_38277_p3 = {{mul_ln728_48_reg_36791}, {24'd0}};

assign shl_ln728_82_fu_37560_p3 = {{mul_ln1118_36_fu_366_p2}, {24'd0}};

assign shl_ln728_83_fu_37594_p3 = {{mul_ln728_49_fu_426_p2}, {24'd0}};

assign shl_ln728_84_fu_37606_p3 = {{mul_ln728_50_fu_391_p2}, {24'd0}};

assign shl_ln728_85_fu_37618_p3 = {{mul_ln728_51_fu_410_p2}, {24'd0}};

assign shl_ln728_86_fu_37626_p3 = {{mul_ln728_52_fu_374_p2}, {24'd0}};

assign shl_ln728_87_fu_37634_p3 = {{mul_ln728_53_fu_428_p2}, {24'd0}};

assign shl_ln728_88_fu_38317_p3 = {{add_ln1118_fu_38311_p2}, {24'd0}};

assign shl_ln728_89_fu_38357_p3 = {{sub_ln1118_2_fu_38351_p2}, {24'd0}};

assign shl_ln728_8_fu_36945_p3 = {{mul_ln728_8_fu_340_p2}, {24'd0}};

assign shl_ln728_90_fu_37642_p3 = {{mul_ln728_54_fu_424_p2}, {24'd0}};

assign shl_ln728_91_fu_37654_p3 = {{mul_ln728_55_fu_422_p2}, {24'd0}};

assign shl_ln728_92_fu_37662_p3 = {{mul_ln1118_37_fu_419_p2}, {24'd0}};

assign shl_ln728_93_fu_37670_p3 = {{mul_ln1118_38_fu_413_p2}, {24'd0}};

assign shl_ln728_94_fu_37678_p3 = {{mul_ln728_56_fu_347_p2}, {24'd0}};

assign shl_ln728_9_fu_36953_p3 = {{mul_ln1118_4_fu_403_p2}, {24'd0}};

assign shl_ln728_s_fu_36869_p3 = {{mul_ln728_fu_365_p2}, {24'd0}};

assign shl_ln_fu_36857_p3 = {{mul_ln1118_fu_389_p2}, {24'd0}};

assign sub_ln1118_1_fu_37296_p2 = ($signed(sext_ln1118_fu_37280_p1) - $signed(zext_ln1118_14_fu_37292_p1));

assign sub_ln1118_2_fu_38351_p2 = (zext_ln1118_35_fu_38347_p1 - zext_ln1118_34_fu_38336_p1);

assign sub_ln1118_fu_37274_p2 = (23'd0 - zext_ln1118_13_fu_37270_p1);

assign zext_ln1118_10_fu_37199_p1 = data_2_V_read;

assign zext_ln1118_12_fu_37252_p1 = data_3_V_read;

assign zext_ln1118_13_fu_37270_p1 = shl_ln1_fu_37262_p3;

assign zext_ln1118_14_fu_37292_p1 = shl_ln1118_s_fu_37284_p3;

assign zext_ln1118_15_fu_37330_p1 = data_3_V_read;

assign zext_ln1118_16_fu_37416_p1 = data_4_V_read;

assign zext_ln1118_17_fu_37424_p1 = data_4_V_read;

assign zext_ln1118_18_fu_37431_p1 = data_4_V_read;

assign zext_ln1118_1_fu_36834_p1 = data_0_V_read;

assign zext_ln1118_20_fu_37445_p1 = data_5_V_read;

assign zext_ln1118_21_fu_37456_p1 = data_5_V_read;

assign zext_ln1118_22_fu_37464_p1 = data_6_V_read;

assign zext_ln1118_23_fu_37471_p1 = data_6_V_read;

assign zext_ln1118_24_fu_37478_p1 = data_6_V_read;

assign zext_ln1118_26_fu_38285_p1 = shl_ln728_81_fu_38277_p3;

assign zext_ln1118_27_fu_37573_p1 = data_7_V_read;

assign zext_ln1118_29_fu_37588_p1 = data_7_V_read;

assign zext_ln1118_2_fu_36840_p1 = data_0_V_read;

assign zext_ln1118_30_fu_37614_p1 = shl_ln728_84_fu_37606_p3;

assign zext_ln1118_31_fu_38296_p1 = shl_ln1118_1_fu_38289_p3;

assign zext_ln1118_32_fu_38307_p1 = shl_ln1118_2_fu_38300_p3;

assign zext_ln1118_33_fu_38325_p1 = shl_ln728_88_fu_38317_p3;

assign zext_ln1118_34_fu_38336_p1 = shl_ln1118_3_fu_38329_p3;

assign zext_ln1118_35_fu_38347_p1 = shl_ln1118_4_fu_38340_p3;

assign zext_ln1118_3_fu_36849_p1 = data_0_V_read;

assign zext_ln1118_4_fu_36970_p1 = data_1_V_read;

assign zext_ln1118_5_fu_36979_p1 = data_1_V_read;

assign zext_ln1118_6_fu_37003_p1 = data_1_V_read;

assign zext_ln1118_7_fu_37105_p1 = data_2_V_read;

assign zext_ln1118_8_fu_37114_p1 = data_2_V_read;

assign zext_ln1118_9_fu_37121_p1 = data_2_V_read;

assign zext_ln703_fu_38592_p1 = add_ln703_68_reg_39035;

assign zext_ln728_10_fu_37942_p1 = shl_ln728_23_fu_37934_p3;

assign zext_ln728_11_fu_37135_p1 = shl_ln728_24_fu_37127_p3;

assign zext_ln728_12_fu_37159_p1 = shl_ln728_26_fu_37151_p3;

assign zext_ln728_13_fu_37213_p1 = shl_ln728_31_fu_37205_p3;

assign zext_ln728_14_fu_37954_p1 = shl_ln728_32_fu_37946_p3;

assign zext_ln728_15_fu_37237_p1 = shl_ln728_34_fu_37229_p3;

assign zext_ln728_16_fu_37241_p1 = data_3_V_read;

assign zext_ln728_17_fu_37318_p1 = shl_ln728_37_fu_37310_p3;

assign zext_ln728_18_fu_37344_p1 = shl_ln728_39_fu_37336_p3;

assign zext_ln728_19_fu_37356_p1 = shl_ln728_40_fu_37348_p3;

assign zext_ln728_1_fu_36905_p1 = shl_ln728_3_fu_36897_p3;

assign zext_ln728_20_fu_37380_p1 = shl_ln728_42_fu_37372_p3;

assign zext_ln728_21_fu_37392_p1 = shl_ln728_43_fu_37384_p3;

assign zext_ln728_22_fu_37404_p1 = shl_ln728_45_fu_37396_p3;

assign zext_ln728_23_fu_38029_p1 = shl_ln728_51_fu_38021_p3;

assign zext_ln728_24_fu_38061_p1 = shl_ln728_54_fu_38053_p3;

assign zext_ln728_25_fu_38085_p1 = shl_ln728_56_fu_38077_p3;

assign zext_ln728_26_fu_38097_p1 = shl_ln728_57_fu_38089_p3;

assign zext_ln728_27_fu_38121_p1 = shl_ln728_59_fu_38113_p3;

assign zext_ln728_28_fu_38145_p1 = shl_ln728_61_fu_38137_p3;

assign zext_ln728_29_fu_38173_p1 = shl_ln728_64_fu_38165_p3;

assign zext_ln728_2_fu_36941_p1 = shl_ln728_7_fu_36933_p3;

assign zext_ln728_30_fu_38237_p1 = shl_ln728_70_fu_38229_p3;

assign zext_ln728_31_fu_38249_p1 = shl_ln728_72_fu_38241_p3;

assign zext_ln728_32_fu_38273_p1 = shl_ln728_77_fu_38265_p3;

assign zext_ln728_33_fu_37548_p1 = shl_ln728_79_fu_37540_p3;

assign zext_ln728_35_fu_37602_p1 = shl_ln728_83_fu_37594_p3;

assign zext_ln728_36_fu_37650_p1 = shl_ln728_90_fu_37642_p3;

assign zext_ln728_4_fu_37017_p1 = shl_ln728_13_fu_37009_p3;

assign zext_ln728_5_fu_37037_p1 = shl_ln728_15_fu_37029_p3;

assign zext_ln728_6_fu_37057_p1 = shl_ln728_17_fu_37049_p3;

assign zext_ln728_7_fu_37069_p1 = shl_ln728_18_fu_37061_p3;

assign zext_ln728_8_fu_37081_p1 = shl_ln728_19_fu_37073_p3;

assign zext_ln728_9_fu_37930_p1 = shl_ln728_22_fu_37922_p3;

assign zext_ln728_fu_36877_p1 = shl_ln728_s_fu_36869_p3;

always @ (posedge ap_clk) begin
    mul_ln1118_5_reg_36549[0] <= 1'b0;
    mul_ln728_18_reg_36586[0] <= 1'b0;
    mul_ln728_23_reg_36618[2:0] <= 3'b000;
    mul_ln728_32_reg_36666[0] <= 1'b0;
    mul_ln1118_19_reg_36670[0] <= 1'b0;
    mul_ln1118_20_reg_36674[0] <= 1'b0;
    mul_ln728_33_reg_36678[1:0] <= 2'b00;
    mul_ln1118_21_reg_36682[4:0] <= 5'b00000;
    mul_ln1118_22_reg_36686[0] <= 1'b0;
    mul_ln728_34_reg_36690[1:0] <= 2'b00;
    mul_ln728_35_reg_36698[0] <= 1'b0;
    mul_ln728_36_reg_36702[4:0] <= 5'b00000;
    mul_ln1118_24_reg_36706[1:0] <= 2'b00;
    mul_ln728_37_reg_36710[1:0] <= 2'b00;
    mul_ln1118_25_reg_36714[0] <= 1'b0;
    mul_ln728_38_reg_36718[0] <= 1'b0;
    mul_ln1118_26_reg_36722[0] <= 1'b0;
    mul_ln728_39_reg_36726[2:0] <= 3'b000;
    mul_ln728_40_reg_36730[0] <= 1'b0;
    mul_ln1118_27_reg_36738[0] <= 1'b0;
    mul_ln1118_28_reg_36742[2:0] <= 3'b000;
    mul_ln1118_29_reg_36746[2:0] <= 3'b000;
    mul_ln1118_30_reg_36750[0] <= 1'b0;
    mul_ln728_42_reg_36754[0] <= 1'b0;
    mul_ln728_44_reg_36761[0] <= 1'b0;
    mul_ln1118_34_reg_36774[0] <= 1'b0;
    sub_ln1118_1_reg_38920[3:0] <= 4'b0000;
    add_ln703_reg_38925[26:0] <= 27'b000000000000000000000000000;
    add_ln703_8_reg_38930[23:0] <= 24'b000000000000000000000000;
    add_ln703_11_reg_38935[26:0] <= 27'b000000000000000000000000000;
    add_ln703_12_reg_38940[24:0] <= 25'b0000000000000000000000000;
    add_ln703_15_reg_38945[24:0] <= 25'b0000000000000000000000000;
    add_ln703_19_reg_38950[23:0] <= 24'b000000000000000000000000;
    add_ln703_20_reg_38955[23:0] <= 24'b000000000000000000000000;
    add_ln703_24_reg_38960[26:0] <= 27'b000000000000000000000000000;
    add_ln703_27_reg_38965[24:0] <= 25'b0000000000000000000000000;
    add_ln703_28_reg_38970[24:0] <= 25'b0000000000000000000000000;
    add_ln703_32_reg_38975[23:0] <= 24'b000000000000000000000000;
    add_ln703_35_reg_38980[24:0] <= 25'b0000000000000000000000000;
    add_ln703_36_reg_38985[25:0] <= 26'b00000000000000000000000000;
    add_ln703_40_reg_38990[25:0] <= 26'b00000000000000000000000000;
    add_ln703_43_reg_38995[24:0] <= 25'b0000000000000000000000000;
    add_ln703_44_reg_39000[23:0] <= 24'b000000000000000000000000;
    add_ln703_51_reg_39005[24:0] <= 25'b0000000000000000000000000;
    add_ln703_52_reg_39010[24:0] <= 25'b0000000000000000000000000;
    add_ln703_59_reg_39015[23:0] <= 24'b000000000000000000000000;
    add_ln703_60_reg_39020[24:0] <= 25'b0000000000000000000000000;
    add_ln703_64_reg_39025[23:0] <= 24'b000000000000000000000000;
    add_ln703_67_reg_39030[23:0] <= 24'b000000000000000000000000;
    add_ln703_68_reg_39035[24:0] <= 25'b0000000000000000000000000;
    add_ln703_72_reg_39040[23:0] <= 24'b000000000000000000000000;
    add_ln703_75_reg_39045[26:0] <= 27'b000000000000000000000000000;
    add_ln703_80_reg_39050[23:0] <= 24'b000000000000000000000000;
    add_ln703_83_reg_39055[26:0] <= 27'b000000000000000000000000000;
    add_ln703_84_reg_39060[23:0] <= 24'b000000000000000000000000;
    add_ln703_87_reg_39065[26:0] <= 27'b000000000000000000000000000;
    add_ln703_92_reg_39070[23:0] <= 24'b000000000000000000000000;
    add_ln703_95_reg_39075[25:0] <= 26'b00000000000000000000000000;
end

endmodule //dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_3
