// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config12_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11
);


output   ap_ready;
input  [23:0] data_0_V_read;
input  [23:0] data_1_V_read;
input  [23:0] data_2_V_read;
input  [23:0] data_3_V_read;
input  [23:0] data_4_V_read;
input  [23:0] data_5_V_read;
input  [23:0] data_6_V_read;
input  [23:0] data_7_V_read;
input  [23:0] data_8_V_read;
input  [23:0] data_9_V_read;
input  [23:0] data_10_V_read;
input  [23:0] data_11_V_read;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;
output  [63:0] ap_return_8;
output  [63:0] ap_return_9;
output  [63:0] ap_return_10;
output  [63:0] ap_return_11;

wire   [51:0] res_0_V_write_assign_fu_120_p3;
wire   [51:0] res_1_V_write_assign_fu_132_p3;
wire   [51:0] res_2_V_write_assign_fu_144_p3;
wire   [51:0] res_3_V_write_assign_fu_156_p3;
wire   [51:0] res_4_V_write_assign_fu_168_p3;
wire   [51:0] res_5_V_write_assign_fu_180_p3;
wire   [51:0] res_6_V_write_assign_fu_192_p3;
wire   [51:0] res_7_V_write_assign_fu_204_p3;
wire   [51:0] res_8_V_write_assign_fu_216_p3;
wire   [51:0] res_9_V_write_assign_fu_228_p3;
wire   [51:0] res_10_V_write_assign_fu_240_p3;
wire   [51:0] res_11_V_write_assign_fu_252_p3;
wire  signed [63:0] sext_ln728_fu_128_p1;
wire  signed [63:0] sext_ln728_42_fu_140_p1;
wire  signed [63:0] sext_ln728_43_fu_152_p1;
wire  signed [63:0] sext_ln728_44_fu_164_p1;
wire  signed [63:0] sext_ln728_45_fu_176_p1;
wire  signed [63:0] sext_ln728_46_fu_188_p1;
wire  signed [63:0] sext_ln728_47_fu_200_p1;
wire  signed [63:0] sext_ln728_48_fu_212_p1;
wire  signed [63:0] sext_ln728_49_fu_224_p1;
wire  signed [63:0] sext_ln728_50_fu_236_p1;
wire  signed [63:0] sext_ln728_51_fu_248_p1;
wire  signed [63:0] sext_ln728_52_fu_260_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln728_fu_128_p1;

assign ap_return_1 = sext_ln728_42_fu_140_p1;

assign ap_return_10 = sext_ln728_51_fu_248_p1;

assign ap_return_11 = sext_ln728_52_fu_260_p1;

assign ap_return_2 = sext_ln728_43_fu_152_p1;

assign ap_return_3 = sext_ln728_44_fu_164_p1;

assign ap_return_4 = sext_ln728_45_fu_176_p1;

assign ap_return_5 = sext_ln728_46_fu_188_p1;

assign ap_return_6 = sext_ln728_47_fu_200_p1;

assign ap_return_7 = sext_ln728_48_fu_212_p1;

assign ap_return_8 = sext_ln728_49_fu_224_p1;

assign ap_return_9 = sext_ln728_50_fu_236_p1;

assign res_0_V_write_assign_fu_120_p3 = {{data_0_V_read}, {28'd0}};

assign res_10_V_write_assign_fu_240_p3 = {{data_10_V_read}, {28'd0}};

assign res_11_V_write_assign_fu_252_p3 = {{data_11_V_read}, {28'd0}};

assign res_1_V_write_assign_fu_132_p3 = {{data_1_V_read}, {28'd0}};

assign res_2_V_write_assign_fu_144_p3 = {{data_2_V_read}, {28'd0}};

assign res_3_V_write_assign_fu_156_p3 = {{data_3_V_read}, {28'd0}};

assign res_4_V_write_assign_fu_168_p3 = {{data_4_V_read}, {28'd0}};

assign res_5_V_write_assign_fu_180_p3 = {{data_5_V_read}, {28'd0}};

assign res_6_V_write_assign_fu_192_p3 = {{data_6_V_read}, {28'd0}};

assign res_7_V_write_assign_fu_204_p3 = {{data_7_V_read}, {28'd0}};

assign res_8_V_write_assign_fu_216_p3 = {{data_8_V_read}, {28'd0}};

assign res_9_V_write_assign_fu_228_p3 = {{data_9_V_read}, {28'd0}};

assign sext_ln728_42_fu_140_p1 = $signed(res_1_V_write_assign_fu_132_p3);

assign sext_ln728_43_fu_152_p1 = $signed(res_2_V_write_assign_fu_144_p3);

assign sext_ln728_44_fu_164_p1 = $signed(res_3_V_write_assign_fu_156_p3);

assign sext_ln728_45_fu_176_p1 = $signed(res_4_V_write_assign_fu_168_p3);

assign sext_ln728_46_fu_188_p1 = $signed(res_5_V_write_assign_fu_180_p3);

assign sext_ln728_47_fu_200_p1 = $signed(res_6_V_write_assign_fu_192_p3);

assign sext_ln728_48_fu_212_p1 = $signed(res_7_V_write_assign_fu_204_p3);

assign sext_ln728_49_fu_224_p1 = $signed(res_8_V_write_assign_fu_216_p3);

assign sext_ln728_50_fu_236_p1 = $signed(res_9_V_write_assign_fu_228_p3);

assign sext_ln728_51_fu_248_p1 = $signed(res_10_V_write_assign_fu_240_p3);

assign sext_ln728_52_fu_260_p1 = $signed(res_11_V_write_assign_fu_252_p3);

assign sext_ln728_fu_128_p1 = $signed(res_0_V_write_assign_fu_120_p3);

endmodule //linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config12_s
