-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config12_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_10_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_11_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config12_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal res_0_V_write_assign_fu_120_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_1_V_write_assign_fu_132_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_2_V_write_assign_fu_144_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_3_V_write_assign_fu_156_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_4_V_write_assign_fu_168_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_5_V_write_assign_fu_180_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_6_V_write_assign_fu_192_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_7_V_write_assign_fu_204_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_8_V_write_assign_fu_216_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_9_V_write_assign_fu_228_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_10_V_write_assign_fu_240_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal res_11_V_write_assign_fu_252_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln728_fu_128_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_42_fu_140_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_43_fu_152_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_44_fu_164_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_45_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_46_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_47_fu_200_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_48_fu_212_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_49_fu_224_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_50_fu_236_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_51_fu_248_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln728_52_fu_260_p1 : STD_LOGIC_VECTOR (63 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= sext_ln728_fu_128_p1;
    ap_return_1 <= sext_ln728_42_fu_140_p1;
    ap_return_10 <= sext_ln728_51_fu_248_p1;
    ap_return_11 <= sext_ln728_52_fu_260_p1;
    ap_return_2 <= sext_ln728_43_fu_152_p1;
    ap_return_3 <= sext_ln728_44_fu_164_p1;
    ap_return_4 <= sext_ln728_45_fu_176_p1;
    ap_return_5 <= sext_ln728_46_fu_188_p1;
    ap_return_6 <= sext_ln728_47_fu_200_p1;
    ap_return_7 <= sext_ln728_48_fu_212_p1;
    ap_return_8 <= sext_ln728_49_fu_224_p1;
    ap_return_9 <= sext_ln728_50_fu_236_p1;
    res_0_V_write_assign_fu_120_p3 <= (data_0_V_read & ap_const_lv28_0);
    res_10_V_write_assign_fu_240_p3 <= (data_10_V_read & ap_const_lv28_0);
    res_11_V_write_assign_fu_252_p3 <= (data_11_V_read & ap_const_lv28_0);
    res_1_V_write_assign_fu_132_p3 <= (data_1_V_read & ap_const_lv28_0);
    res_2_V_write_assign_fu_144_p3 <= (data_2_V_read & ap_const_lv28_0);
    res_3_V_write_assign_fu_156_p3 <= (data_3_V_read & ap_const_lv28_0);
    res_4_V_write_assign_fu_168_p3 <= (data_4_V_read & ap_const_lv28_0);
    res_5_V_write_assign_fu_180_p3 <= (data_5_V_read & ap_const_lv28_0);
    res_6_V_write_assign_fu_192_p3 <= (data_6_V_read & ap_const_lv28_0);
    res_7_V_write_assign_fu_204_p3 <= (data_7_V_read & ap_const_lv28_0);
    res_8_V_write_assign_fu_216_p3 <= (data_8_V_read & ap_const_lv28_0);
    res_9_V_write_assign_fu_228_p3 <= (data_9_V_read & ap_const_lv28_0);
        sext_ln728_42_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_1_V_write_assign_fu_132_p3),64));

        sext_ln728_43_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_2_V_write_assign_fu_144_p3),64));

        sext_ln728_44_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_3_V_write_assign_fu_156_p3),64));

        sext_ln728_45_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_4_V_write_assign_fu_168_p3),64));

        sext_ln728_46_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_5_V_write_assign_fu_180_p3),64));

        sext_ln728_47_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_6_V_write_assign_fu_192_p3),64));

        sext_ln728_48_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_7_V_write_assign_fu_204_p3),64));

        sext_ln728_49_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_8_V_write_assign_fu_216_p3),64));

        sext_ln728_50_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_9_V_write_assign_fu_228_p3),64));

        sext_ln728_51_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_10_V_write_assign_fu_240_p3),64));

        sext_ln728_52_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_11_V_write_assign_fu_252_p3),64));

        sext_ln728_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_0_V_write_assign_fu_120_p3),64));

end behav;
