-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu_ap_fixed_ap_ufixed_22_3_5_3_0_relu_config4_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (21 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (21 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (21 downto 0) );
end;


architecture behav of relu_ap_fixed_ap_ufixed_22_3_5_3_0_relu_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal icmp_ln1494_fu_62_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_68_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln1494_1_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln708_1_fu_92_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln1494_2_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln708_2_fu_116_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal icmp_ln1494_3_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln708_3_fu_140_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln1494_fu_78_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln1494_34_fu_102_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln1494_35_fu_126_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal select_ln1494_36_fu_150_p3 : STD_LOGIC_VECTOR (21 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln1494_fu_78_p3;
    ap_return_1 <= select_ln1494_34_fu_102_p3;
    ap_return_2 <= select_ln1494_35_fu_126_p3;
    ap_return_3 <= select_ln1494_36_fu_150_p3;
    icmp_ln1494_1_fu_86_p2 <= "1" when (signed(data_1_V_read) > signed(ap_const_lv64_0)) else "0";
    icmp_ln1494_2_fu_110_p2 <= "1" when (signed(data_2_V_read) > signed(ap_const_lv64_0)) else "0";
    icmp_ln1494_3_fu_134_p2 <= "1" when (signed(data_3_V_read) > signed(ap_const_lv64_0)) else "0";
    icmp_ln1494_fu_62_p2 <= "1" when (signed(data_0_V_read) > signed(ap_const_lv64_0)) else "0";
    select_ln1494_34_fu_102_p3 <= 
        trunc_ln708_1_fu_92_p4 when (icmp_ln1494_1_fu_86_p2(0) = '1') else 
        ap_const_lv22_0;
    select_ln1494_35_fu_126_p3 <= 
        trunc_ln708_2_fu_116_p4 when (icmp_ln1494_2_fu_110_p2(0) = '1') else 
        ap_const_lv22_0;
    select_ln1494_36_fu_150_p3 <= 
        trunc_ln708_3_fu_140_p4 when (icmp_ln1494_3_fu_134_p2(0) = '1') else 
        ap_const_lv22_0;
    select_ln1494_fu_78_p3 <= 
        trunc_ln_fu_68_p4 when (icmp_ln1494_fu_62_p2(0) = '1') else 
        ap_const_lv22_0;
    trunc_ln708_1_fu_92_p4 <= data_1_V_read(50 downto 29);
    trunc_ln708_2_fu_116_p4 <= data_2_V_read(50 downto 29);
    trunc_ln708_3_fu_140_p4 <= data_3_V_read(50 downto 29);
    trunc_ln_fu_68_p4 <= data_0_V_read(50 downto 29);
end behav;
