Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  LayerName:
    fc1:
      Precision:
        bias: ap_fixed<16,8>
        weight: ap_fixed<16,8>
      ReuseFactor: 1
    fc1_input:
      Precision:
        result: ap_fixed<16,6>
    fc2:
      Precision:
        bias: ap_fixed<16,8>
        weight: ap_fixed<16,8>
      ReuseFactor: 1
    fc3:
      Precision:
        bias: ap_fixed<16,8>
        weight: ap_fixed<16,8>
      ReuseFactor: 1
    fc4:
      Precision:
        bias: ap_fixed<16,8>
        weight: ap_fixed<16,8>
      ReuseFactor: 1
    fc5:
      Precision:
        bias: ap_fixed<16,8>
        weight: ap_fixed<16,8>
      ReuseFactor: 1
    relu1:
      Precision:
        result: ap_ufixed<16,7>
      ReuseFactor: 1
    relu2:
      Precision:
        result: ap_ufixed<16,7>
      ReuseFactor: 1
    relu3:
      Precision:
        result: ap_ufixed<16,7>
      ReuseFactor: 1
    relu4:
      Precision:
        result: ap_ufixed<16,7>
      ReuseFactor: 1
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model '../model/appendix/reverse_problem/hls4ml_prj/keras_model.h5'
OutputDir: ../model/appendix/reverse_problem/hls4ml_prj
OutputPredictions: null
ProjectName: myproject
Stamp: 5CFfABa2
XilinxPart: XC7A100T
