// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_boolean_1 = true;
const bool dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_boolean_0 = false;
const sc_lv<44> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv44_3302 = "11001100000010";
const sc_lv<44> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv44_3D8A = "11110110001010";
const sc_lv<44> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv44_FFFFFFFDEAF = "11111111111111111111111111111101111010101111";
const sc_lv<44> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv44_3EE8 = "11111011101000";
const sc_lv<8> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv8_0 = "00000000";
const sc_lv<52> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv52_FEB6000000000 = "1111111010110110000000000000000000000000000000000000";
const sc_lv<52> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv52_FEDFC00000000 = "1111111011011111110000000000000000000000000000000000";
const sc_lv<52> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv52_140000000000 = "101000000000000000000000000000000000000000000";
const sc_lv<52> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv52_FF09C00000000 = "1111111100001001110000000000000000000000000000000000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv32_1D = "11101";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::ap_const_lv32_33 = "110011";

dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_211_p2);
    sensitive << ( shl_ln728_1_fu_181_p3 );

    SC_METHOD(thread_acc_2_V_fu_217_p2);
    sensitive << ( shl_ln728_2_fu_189_p3 );

    SC_METHOD(thread_acc_3_V_fu_223_p2);
    sensitive << ( shl_ln728_3_fu_197_p3 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( p_Val2_s_fu_205_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( acc_1_V_fu_211_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( acc_2_V_fu_217_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_2_int_reg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( acc_3_V_fu_223_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_3_int_reg );

    SC_METHOD(thread_mul_ln728_1_fu_67_p0);
    sensitive << ( sext_ln1118_fu_165_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_1_fu_67_p2);
    sensitive << ( mul_ln728_1_fu_67_p0 );

    SC_METHOD(thread_mul_ln728_2_fu_64_p0);
    sensitive << ( sext_ln1118_fu_165_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_2_fu_64_p2);
    sensitive << ( mul_ln728_2_fu_64_p0 );

    SC_METHOD(thread_mul_ln728_3_fu_66_p0);
    sensitive << ( sext_ln1118_fu_165_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_3_fu_66_p2);
    sensitive << ( mul_ln728_3_fu_66_p0 );

    SC_METHOD(thread_mul_ln728_fu_65_p0);
    sensitive << ( sext_ln1118_fu_165_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_fu_65_p2);
    sensitive << ( mul_ln728_fu_65_p0 );

    SC_METHOD(thread_p_Val2_s_fu_205_p2);
    sensitive << ( shl_ln_fu_173_p3 );

    SC_METHOD(thread_sext_ln1118_fu_165_p1);
    sensitive << ( data_V_read );

    SC_METHOD(thread_shl_ln728_1_fu_181_p3);
    sensitive << ( mul_ln728_1_reg_152 );

    SC_METHOD(thread_shl_ln728_2_fu_189_p3);
    sensitive << ( mul_ln728_2_reg_156 );

    SC_METHOD(thread_shl_ln728_3_fu_197_p3);
    sensitive << ( mul_ln728_3_reg_160 );

    SC_METHOD(thread_shl_ln_fu_173_p3);
    sensitive << ( mul_ln728_reg_148 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, mul_ln728_fu_65_p2, "mul_ln728_fu_65_p2");
    sc_trace(mVcdFile, mul_ln728_reg_148, "mul_ln728_reg_148");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, mul_ln728_1_fu_67_p2, "mul_ln728_1_fu_67_p2");
    sc_trace(mVcdFile, mul_ln728_1_reg_152, "mul_ln728_1_reg_152");
    sc_trace(mVcdFile, mul_ln728_2_fu_64_p2, "mul_ln728_2_fu_64_p2");
    sc_trace(mVcdFile, mul_ln728_2_reg_156, "mul_ln728_2_reg_156");
    sc_trace(mVcdFile, mul_ln728_3_fu_66_p2, "mul_ln728_3_fu_66_p2");
    sc_trace(mVcdFile, mul_ln728_3_reg_160, "mul_ln728_3_reg_160");
    sc_trace(mVcdFile, mul_ln728_2_fu_64_p0, "mul_ln728_2_fu_64_p0");
    sc_trace(mVcdFile, sext_ln1118_fu_165_p1, "sext_ln1118_fu_165_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln728_fu_65_p0, "mul_ln728_fu_65_p0");
    sc_trace(mVcdFile, mul_ln728_3_fu_66_p0, "mul_ln728_3_fu_66_p0");
    sc_trace(mVcdFile, mul_ln728_1_fu_67_p0, "mul_ln728_1_fu_67_p0");
    sc_trace(mVcdFile, shl_ln_fu_173_p3, "shl_ln_fu_173_p3");
    sc_trace(mVcdFile, shl_ln728_1_fu_181_p3, "shl_ln728_1_fu_181_p3");
    sc_trace(mVcdFile, shl_ln728_2_fu_189_p3, "shl_ln728_2_fu_189_p3");
    sc_trace(mVcdFile, shl_ln728_3_fu_197_p3, "shl_ln728_3_fu_197_p3");
    sc_trace(mVcdFile, p_Val2_s_fu_205_p2, "p_Val2_s_fu_205_p2");
    sc_trace(mVcdFile, acc_1_V_fu_211_p2, "acc_1_V_fu_211_p2");
    sc_trace(mVcdFile, acc_2_V_fu_217_p2, "acc_2_V_fu_217_p2");
    sc_trace(mVcdFile, acc_3_V_fu_223_p2, "acc_3_V_fu_223_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
    sc_trace(mVcdFile, ap_return_2_int_reg, "ap_return_2_int_reg");
    sc_trace(mVcdFile, ap_return_3_int_reg, "ap_return_3_int_reg");
#endif

    }
}

dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::~dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = p_Val2_s_fu_205_p2.read().range(51, 29);
        ap_return_1_int_reg = acc_1_V_fu_211_p2.read().range(51, 29);
        ap_return_2_int_reg = acc_2_V_fu_217_p2.read().range(51, 29);
        ap_return_3_int_reg = acc_3_V_fu_223_p2.read().range(51, 29);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        mul_ln728_1_reg_152 = mul_ln728_1_fu_67_p2.read();
        mul_ln728_2_reg_156 = mul_ln728_2_fu_64_p2.read();
        mul_ln728_3_reg_160 = mul_ln728_3_fu_66_p2.read();
        mul_ln728_reg_148 = mul_ln728_fu_65_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_acc_1_V_fu_211_p2() {
    acc_1_V_fu_211_p2 = (!shl_ln728_1_fu_181_p3.read().is_01() || !ap_const_lv52_FEDFC00000000.is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_1_fu_181_p3.read()) + sc_bigint<52>(ap_const_lv52_FEDFC00000000));
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_acc_2_V_fu_217_p2() {
    acc_2_V_fu_217_p2 = (!shl_ln728_2_fu_189_p3.read().is_01() || !ap_const_lv52_140000000000.is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_2_fu_189_p3.read()) + sc_biguint<52>(ap_const_lv52_140000000000));
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_acc_3_V_fu_223_p2() {
    acc_3_V_fu_223_p2 = (!shl_ln728_3_fu_197_p3.read().is_01() || !ap_const_lv52_FF09C00000000.is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_3_fu_197_p3.read()) + sc_bigint<52>(ap_const_lv52_FF09C00000000));
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = p_Val2_s_fu_205_p2.read().range(51, 29);
    }
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = acc_1_V_fu_211_p2.read().range(51, 29);
    }
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_return_2() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_2 = ap_return_2_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_2 = acc_2_V_fu_217_p2.read().range(51, 29);
    }
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_ap_return_3() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_3 = ap_return_3_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_3 = acc_3_V_fu_223_p2.read().range(51, 29);
    }
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_1_fu_67_p0() {
    mul_ln728_1_fu_67_p0 =  (sc_lv<32>) (sext_ln1118_fu_165_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_1_fu_67_p2() {
    mul_ln728_1_fu_67_p2 = (!mul_ln728_1_fu_67_p0.read().is_01() || !ap_const_lv44_3EE8.is_01())? sc_lv<44>(): sc_bigint<32>(mul_ln728_1_fu_67_p0.read()) * sc_biguint<44>(ap_const_lv44_3EE8);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_2_fu_64_p0() {
    mul_ln728_2_fu_64_p0 =  (sc_lv<32>) (sext_ln1118_fu_165_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_2_fu_64_p2() {
    mul_ln728_2_fu_64_p2 = (!mul_ln728_2_fu_64_p0.read().is_01() || !ap_const_lv44_3302.is_01())? sc_lv<44>(): sc_bigint<32>(mul_ln728_2_fu_64_p0.read()) * sc_biguint<44>(ap_const_lv44_3302);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_3_fu_66_p0() {
    mul_ln728_3_fu_66_p0 =  (sc_lv<32>) (sext_ln1118_fu_165_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_3_fu_66_p2() {
    mul_ln728_3_fu_66_p2 = (!mul_ln728_3_fu_66_p0.read().is_01() || !ap_const_lv44_FFFFFFFDEAF.is_01())? sc_lv<44>(): sc_bigint<32>(mul_ln728_3_fu_66_p0.read()) * sc_bigint<44>(ap_const_lv44_FFFFFFFDEAF);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_fu_65_p0() {
    mul_ln728_fu_65_p0 =  (sc_lv<32>) (sext_ln1118_fu_165_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_mul_ln728_fu_65_p2() {
    mul_ln728_fu_65_p2 = (!mul_ln728_fu_65_p0.read().is_01() || !ap_const_lv44_3D8A.is_01())? sc_lv<44>(): sc_bigint<32>(mul_ln728_fu_65_p0.read()) * sc_biguint<44>(ap_const_lv44_3D8A);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_p_Val2_s_fu_205_p2() {
    p_Val2_s_fu_205_p2 = (!shl_ln_fu_173_p3.read().is_01() || !ap_const_lv52_FEB6000000000.is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln_fu_173_p3.read()) + sc_bigint<52>(ap_const_lv52_FEB6000000000));
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_sext_ln1118_fu_165_p1() {
    sext_ln1118_fu_165_p1 = esl_sext<44,32>(data_V_read.read());
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_shl_ln728_1_fu_181_p3() {
    shl_ln728_1_fu_181_p3 = esl_concat<44,8>(mul_ln728_1_reg_152.read(), ap_const_lv8_0);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_shl_ln728_2_fu_189_p3() {
    shl_ln728_2_fu_189_p3 = esl_concat<44,8>(mul_ln728_2_reg_156.read(), ap_const_lv8_0);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_shl_ln728_3_fu_197_p3() {
    shl_ln728_3_fu_197_p3 = esl_concat<44,8>(mul_ln728_3_reg_160.read(), ap_const_lv8_0);
}

void dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0::thread_shl_ln_fu_173_p3() {
    shl_ln_fu_173_p3 = esl_concat<44,8>(mul_ln728_reg_148.read(), ap_const_lv8_0);
}

}

