// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_0_0_0_0_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_0_0_0_0_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_0_0_0_0_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_latency_0_0_0_0_0_0_0_0_0::ap_const_boolean_1 = true;
const bool dense_latency_0_0_0_0_0_0_0_0_0::ap_const_boolean_0 = false;
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_2988 = "10100110001000";
const sc_lv<34> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv34_F73 = "111101110011";
const sc_lv<35> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv35_7FFFFF5FE = "11111111111111111111111010111111110";
const sc_lv<35> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv35_7FFFFF4B7 = "11111111111111111111111010010110111";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_FFFFFEF70 = "111111111111111111111110111101110000";
const sc_lv<34> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv34_3FFFFFA4B = "1111111111111111111111101001001011";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_29A3 = "10100110100011";
const sc_lv<37> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv37_1FFFFFD21C = "1111111111111111111111101001000011100";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_FFFFFE3A6 = "111111111111111111111110001110100110";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv32_FFFFFE83 = "11111111111111111111111010000011";
const sc_lv<37> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv37_1FFFFFD262 = "1111111111111111111111101001001100010";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_31FB = "11000111111011";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_FFFFFEDA3 = "111111111111111111111110110110100011";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_2B24 = "10101100100100";
const sc_lv<33> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv33_6AA = "11010101010";
const sc_lv<37> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv37_1FFFFFD516 = "1111111111111111111111101010100010110";
const sc_lv<35> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv35_1F20 = "1111100100000";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_FFFFFEB88 = "111111111111111111111110101110001000";
const sc_lv<35> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv35_1284 = "1001010000100";
const sc_lv<37> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv37_1FFFFFDF8C = "1111111111111111111111101111110001100";
const sc_lv<37> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv37_1FFFFFD9F7 = "1111111111111111111111101100111110111";
const sc_lv<35> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv35_1240 = "1001001000000";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_2D7C = "10110101111100";
const sc_lv<35> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv35_139C = "1001110011100";
const sc_lv<31> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv31_1B8 = "110111000";
const sc_lv<33> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv33_6D0 = "11011010000";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_FFFFFECEA = "111111111111111111111110110011101010";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_395A = "11100101011010";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv32_27F = "1001111111";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_2856 = "10100001010110";
const sc_lv<36> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv36_FFFFFE86B = "111111111111111111111110100001101011";
const sc_lv<15> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv15_0 = "000000000000000";
const sc_lv<9> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv9_0 = "000000000";
const sc_lv<3> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv3_0 = "000";
const sc_lv<52> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv52_FEBE800000000 = "1111111010111110100000000000000000000000000000000000";
const sc_lv<51> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv51_7EEF000000000 = "111111011101111000000000000000000000000000000000000";
const sc_lv<52> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv52_FEF6C00000000 = "1111111011110110110000000000000000000000000000000000";
const sc_lv<52> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv52_FEE5800000000 = "1111111011100101100000000000000000000000000000000000";
const sc_lv<48> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv48_EBD000000000 = "111010111101000000000000000000000000000000000000";
const sc_lv<51> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv51_B3800000000 = "10110011100000000000000000000000000000000000";
const sc_lv<51> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv51_7FBF800000000 = "111111110111111100000000000000000000000000000000000";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv32_1D = "11101";
const sc_lv<32> dense_latency_0_0_0_0_0_0_0_0_0::ap_const_lv32_33 = "110011";

dense_latency_0_0_0_0_0_0_0_0_0::dense_latency_0_0_0_0_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_4131_p2);
    sensitive << ( add_ln703_416_fu_4109_p2 );
    sensitive << ( add_ln703_418_fu_4125_p2 );

    SC_METHOD(thread_acc_2_V_fu_4159_p2);
    sensitive << ( sext_ln703_19_fu_4143_p1 );
    sensitive << ( add_ln703_422_fu_4153_p2 );

    SC_METHOD(thread_acc_3_V_fu_4187_p2);
    sensitive << ( zext_ln703_17_fu_4171_p1 );
    sensitive << ( add_ln703_426_fu_4181_p2 );

    SC_METHOD(thread_acc_4_V_fu_4219_p2);
    sensitive << ( add_ln703_428_fu_4193_p2 );
    sensitive << ( sext_ln703_21_fu_4215_p1 );

    SC_METHOD(thread_acc_5_V_fu_4241_p2);
    sensitive << ( sext_ln703_22_fu_4231_p1 );
    sensitive << ( add_ln703_433_fu_4235_p2 );

    SC_METHOD(thread_acc_6_V_fu_4269_p2);
    sensitive << ( add_ln703_435_fu_4247_p2 );
    sensitive << ( add_ln703_437_fu_4263_p2 );

    SC_METHOD(thread_acc_7_V_fu_4297_p2);
    sensitive << ( add_ln703_439_fu_4275_p2 );
    sensitive << ( add_ln703_441_fu_4291_p2 );

    SC_METHOD(thread_add_ln703_413_fu_4091_p2);
    sensitive << ( shl_ln728_302_fu_4001_p3 );

    SC_METHOD(thread_add_ln703_414_fu_4097_p2);
    sensitive << ( sext_ln728_135_fu_3917_p1 );
    sensitive << ( add_ln703_413_fu_4091_p2 );

    SC_METHOD(thread_add_ln703_416_fu_4109_p2);
    sensitive << ( zext_ln728_259_fu_3804_p1 );
    sensitive << ( sext_ln728_fu_3712_p1 );

    SC_METHOD(thread_add_ln703_417_fu_4115_p2);
    sensitive << ( shl_ln728_303_fu_4009_p3 );

    SC_METHOD(thread_add_ln703_418_fu_4125_p2);
    sensitive << ( sext_ln728_136_fu_3929_p1 );
    sensitive << ( sext_ln703_fu_4121_p1 );

    SC_METHOD(thread_add_ln703_420_fu_4137_p2);
    sensitive << ( zext_ln728_260_fu_3816_p1 );
    sensitive << ( sext_ln728_133_fu_3724_p1 );

    SC_METHOD(thread_add_ln703_421_fu_4147_p2);
    sensitive << ( zext_ln728_265_fu_4025_p1 );

    SC_METHOD(thread_add_ln703_422_fu_4153_p2);
    sensitive << ( zext_ln728_263_fu_3941_p1 );
    sensitive << ( add_ln703_421_fu_4147_p2 );

    SC_METHOD(thread_add_ln703_424_fu_4165_p2);
    sensitive << ( shl_ln728_290_fu_3820_p3 );
    sensitive << ( zext_ln728_253_fu_3736_p1 );

    SC_METHOD(thread_add_ln703_425_fu_4175_p2);
    sensitive << ( shl_ln728_305_fu_4029_p3 );

    SC_METHOD(thread_add_ln703_426_fu_4181_p2);
    sensitive << ( shl_ln728_297_fu_3945_p3 );
    sensitive << ( add_ln703_425_fu_4175_p2 );

    SC_METHOD(thread_add_ln703_428_fu_4193_p2);
    sensitive << ( sext_ln728_134_fu_3864_p1 );
    sensitive << ( zext_ln728_254_fu_3748_p1 );

    SC_METHOD(thread_add_ln703_429_fu_4199_p2);
    sensitive << ( sext_ln1118_fu_4045_p1 );

    SC_METHOD(thread_add_ln703_430_fu_4209_p2);
    sensitive << ( zext_ln1118_229_fu_3961_p1 );
    sensitive << ( sext_ln703_20_fu_4205_p1 );

    SC_METHOD(thread_add_ln703_432_fu_4225_p2);
    sensitive << ( zext_ln728_255_fu_3760_p1 );
    sensitive << ( shl_ln728_291_fu_3868_p3 );

    SC_METHOD(thread_add_ln703_433_fu_4235_p2);
    sensitive << ( sext_ln728_139_fu_4057_p1 );
    sensitive << ( sext_ln728_137_fu_3973_p1 );

    SC_METHOD(thread_add_ln703_435_fu_4247_p2);
    sensitive << ( zext_ln728_261_fu_3884_p1 );
    sensitive << ( shl_ln728_285_fu_3764_p3 );

    SC_METHOD(thread_add_ln703_436_fu_4253_p2);
    sensitive << ( shl_ln728_308_fu_4061_p3 );

    SC_METHOD(thread_add_ln703_437_fu_4263_p2);
    sensitive << ( sext_ln728_138_fu_3985_p1 );
    sensitive << ( zext_ln703_18_fu_4259_p1 );

    SC_METHOD(thread_add_ln703_439_fu_4275_p2);
    sensitive << ( shl_ln728_293_fu_3888_p3 );
    sensitive << ( zext_ln728_256_fu_3780_p1 );

    SC_METHOD(thread_add_ln703_440_fu_4281_p2);
    sensitive << ( zext_ln703_fu_4077_p1 );

    SC_METHOD(thread_add_ln703_441_fu_4291_p2);
    sensitive << ( zext_ln728_264_fu_3997_p1 );
    sensitive << ( sext_ln703_23_fu_4287_p1 );

    SC_METHOD(thread_add_ln703_fu_4081_p2);
    sensitive << ( zext_ln728_258_fu_3792_p1 );
    sensitive << ( zext_ln728_252_fu_3700_p1 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( p_Val2_s_fu_4103_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( acc_1_V_fu_4131_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( acc_2_V_fu_4159_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_2_int_reg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( acc_3_V_fu_4187_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_3_int_reg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( acc_4_V_fu_4219_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_4_int_reg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( acc_5_V_fu_4241_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_5_int_reg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( acc_6_V_fu_4269_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_6_int_reg );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( acc_7_V_fu_4297_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_7_int_reg );

    SC_METHOD(thread_mul_ln1118_160_fu_167_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_218_fu_3620_p1 );

    SC_METHOD(thread_mul_ln1118_160_fu_167_p2);
    sensitive << ( mul_ln1118_160_fu_167_p0 );

    SC_METHOD(thread_mul_ln1118_161_fu_172_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_161_fu_172_p00 );

    SC_METHOD(thread_mul_ln1118_161_fu_172_p00);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_mul_ln1118_161_fu_172_p2);
    sensitive << ( mul_ln1118_161_fu_172_p0 );

    SC_METHOD(thread_mul_ln1118_162_fu_165_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_222_fu_3641_p1 );

    SC_METHOD(thread_mul_ln1118_162_fu_165_p2);
    sensitive << ( mul_ln1118_162_fu_165_p0 );

    SC_METHOD(thread_mul_ln1118_163_fu_178_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_163_fu_178_p00 );

    SC_METHOD(thread_mul_ln1118_163_fu_178_p00);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_mul_ln1118_163_fu_178_p2);
    sensitive << ( mul_ln1118_163_fu_178_p0 );

    SC_METHOD(thread_mul_ln1118_164_fu_189_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_228_fu_3900_p1 );

    SC_METHOD(thread_mul_ln1118_164_fu_189_p2);
    sensitive << ( mul_ln1118_164_fu_189_p0 );

    SC_METHOD(thread_mul_ln1118_165_fu_170_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_228_fu_3900_p1 );

    SC_METHOD(thread_mul_ln1118_165_fu_170_p2);
    sensitive << ( mul_ln1118_165_fu_170_p0 );

    SC_METHOD(thread_mul_ln1118_166_fu_169_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_166_fu_169_p00 );

    SC_METHOD(thread_mul_ln1118_166_fu_169_p00);
    sensitive << ( data_2_V_read_19_reg_4431 );

    SC_METHOD(thread_mul_ln1118_166_fu_169_p2);
    sensitive << ( mul_ln1118_166_fu_169_p0 );

    SC_METHOD(thread_mul_ln1118_167_fu_193_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_228_fu_3900_p1 );

    SC_METHOD(thread_mul_ln1118_167_fu_193_p2);
    sensitive << ( mul_ln1118_167_fu_193_p0 );

    SC_METHOD(thread_mul_ln1118_168_fu_180_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_228_fu_3900_p1 );

    SC_METHOD(thread_mul_ln1118_168_fu_180_p2);
    sensitive << ( mul_ln1118_168_fu_180_p0 );

    SC_METHOD(thread_mul_ln1118_169_fu_183_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_233_fu_3686_p1 );

    SC_METHOD(thread_mul_ln1118_169_fu_183_p2);
    sensitive << ( mul_ln1118_169_fu_183_p0 );

    SC_METHOD(thread_mul_ln1118_170_fu_166_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_232_fu_3679_p1 );

    SC_METHOD(thread_mul_ln1118_170_fu_166_p2);
    sensitive << ( mul_ln1118_170_fu_166_p0 );

    SC_METHOD(thread_mul_ln1118_171_fu_182_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_233_fu_3686_p1 );

    SC_METHOD(thread_mul_ln1118_171_fu_182_p2);
    sensitive << ( mul_ln1118_171_fu_182_p0 );

    SC_METHOD(thread_mul_ln1118_172_fu_171_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_172_fu_171_p00 );

    SC_METHOD(thread_mul_ln1118_172_fu_171_p00);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_mul_ln1118_172_fu_171_p2);
    sensitive << ( mul_ln1118_172_fu_171_p0 );

    SC_METHOD(thread_mul_ln1118_173_fu_164_p0);
    sensitive << ( zext_ln1118_230_reg_4448 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_173_fu_164_p2);
    sensitive << ( mul_ln1118_173_fu_164_p0 );

    SC_METHOD(thread_mul_ln1118_fu_175_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1118_fu_175_p00 );

    SC_METHOD(thread_mul_ln1118_fu_175_p00);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_mul_ln1118_fu_175_p2);
    sensitive << ( mul_ln1118_fu_175_p0 );

    SC_METHOD(thread_mul_ln728_278_fu_191_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln728_278_fu_191_p00 );

    SC_METHOD(thread_mul_ln728_278_fu_191_p00);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_mul_ln728_278_fu_191_p2);
    sensitive << ( mul_ln728_278_fu_191_p0 );

    SC_METHOD(thread_mul_ln728_279_fu_179_p0);
    sensitive << ( zext_ln1118_220_reg_4443 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_279_fu_179_p2);
    sensitive << ( mul_ln728_279_fu_179_p0 );

    SC_METHOD(thread_mul_ln728_280_fu_177_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln728_280_fu_177_p00 );

    SC_METHOD(thread_mul_ln728_280_fu_177_p00);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_mul_ln728_280_fu_177_p2);
    sensitive << ( mul_ln728_280_fu_177_p0 );

    SC_METHOD(thread_mul_ln728_281_fu_184_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln728_281_fu_184_p00 );

    SC_METHOD(thread_mul_ln728_281_fu_184_p00);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_mul_ln728_281_fu_184_p2);
    sensitive << ( mul_ln728_281_fu_184_p0 );

    SC_METHOD(thread_mul_ln728_282_fu_187_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln728_282_fu_187_p00 );

    SC_METHOD(thread_mul_ln728_282_fu_187_p00);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_mul_ln728_282_fu_187_p2);
    sensitive << ( mul_ln728_282_fu_187_p0 );

    SC_METHOD(thread_mul_ln728_283_fu_162_p0);
    sensitive << ( zext_ln1118_224_fu_3657_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_283_fu_162_p2);
    sensitive << ( mul_ln728_283_fu_162_p0 );

    SC_METHOD(thread_mul_ln728_284_fu_186_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_222_fu_3641_p1 );

    SC_METHOD(thread_mul_ln728_284_fu_186_p2);
    sensitive << ( mul_ln728_284_fu_186_p0 );

    SC_METHOD(thread_mul_ln728_285_fu_174_p0);
    sensitive << ( zext_ln1118_224_fu_3657_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_285_fu_174_p2);
    sensitive << ( mul_ln728_285_fu_174_p0 );

    SC_METHOD(thread_mul_ln728_286_fu_176_p0);
    sensitive << ( zext_ln1118_224_fu_3657_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln728_286_fu_176_p2);
    sensitive << ( mul_ln728_286_fu_176_p0 );

    SC_METHOD(thread_mul_ln728_287_fu_168_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_228_fu_3900_p1 );

    SC_METHOD(thread_mul_ln728_287_fu_168_p2);
    sensitive << ( mul_ln728_287_fu_168_p0 );

    SC_METHOD(thread_mul_ln728_288_fu_188_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln728_288_fu_188_p00 );

    SC_METHOD(thread_mul_ln728_288_fu_188_p00);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_mul_ln728_288_fu_188_p2);
    sensitive << ( mul_ln728_288_fu_188_p0 );

    SC_METHOD(thread_mul_ln728_289_fu_190_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_228_fu_3900_p1 );

    SC_METHOD(thread_mul_ln728_289_fu_190_p2);
    sensitive << ( mul_ln728_289_fu_190_p0 );

    SC_METHOD(thread_mul_ln728_290_fu_185_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_232_fu_3679_p1 );

    SC_METHOD(thread_mul_ln728_290_fu_185_p2);
    sensitive << ( mul_ln728_290_fu_185_p0 );

    SC_METHOD(thread_mul_ln728_291_fu_192_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_232_fu_3679_p1 );

    SC_METHOD(thread_mul_ln728_291_fu_192_p2);
    sensitive << ( mul_ln728_291_fu_192_p0 );

    SC_METHOD(thread_mul_ln728_292_fu_181_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln728_292_fu_181_p00 );

    SC_METHOD(thread_mul_ln728_292_fu_181_p00);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_mul_ln728_292_fu_181_p2);
    sensitive << ( mul_ln728_292_fu_181_p0 );

    SC_METHOD(thread_mul_ln728_fu_163_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1118_218_fu_3620_p1 );

    SC_METHOD(thread_mul_ln728_fu_163_p2);
    sensitive << ( mul_ln728_fu_163_p0 );

    SC_METHOD(thread_p_Val2_s_fu_4103_p2);
    sensitive << ( zext_ln703_16_fu_4087_p1 );
    sensitive << ( add_ln703_414_fu_4097_p2 );

    SC_METHOD(thread_sext_ln1118_fu_4045_p1);
    sensitive << ( shl_ln728_306_fu_4037_p3 );

    SC_METHOD(thread_sext_ln703_19_fu_4143_p1);
    sensitive << ( add_ln703_420_fu_4137_p2 );

    SC_METHOD(thread_sext_ln703_20_fu_4205_p1);
    sensitive << ( add_ln703_429_fu_4199_p2 );

    SC_METHOD(thread_sext_ln703_21_fu_4215_p1);
    sensitive << ( add_ln703_430_fu_4209_p2 );

    SC_METHOD(thread_sext_ln703_22_fu_4231_p1);
    sensitive << ( add_ln703_432_fu_4225_p2 );

    SC_METHOD(thread_sext_ln703_23_fu_4287_p1);
    sensitive << ( add_ln703_440_fu_4281_p2 );

    SC_METHOD(thread_sext_ln703_fu_4121_p1);
    sensitive << ( add_ln703_417_fu_4115_p2 );

    SC_METHOD(thread_sext_ln728_133_fu_3724_p1);
    sensitive << ( shl_ln728_281_fu_3716_p3 );

    SC_METHOD(thread_sext_ln728_134_fu_3864_p1);
    sensitive << ( tmp_5_fu_3856_p3 );

    SC_METHOD(thread_sext_ln728_135_fu_3917_p1);
    sensitive << ( shl_ln728_294_fu_3909_p3 );

    SC_METHOD(thread_sext_ln728_136_fu_3929_p1);
    sensitive << ( shl_ln728_295_fu_3921_p3 );

    SC_METHOD(thread_sext_ln728_137_fu_3973_p1);
    sensitive << ( shl_ln728_299_fu_3965_p3 );

    SC_METHOD(thread_sext_ln728_138_fu_3985_p1);
    sensitive << ( shl_ln728_300_fu_3977_p3 );

    SC_METHOD(thread_sext_ln728_139_fu_4057_p1);
    sensitive << ( shl_ln728_307_fu_4049_p3 );

    SC_METHOD(thread_sext_ln728_fu_3712_p1);
    sensitive << ( shl_ln728_s_fu_3704_p3 );

    SC_METHOD(thread_shl_ln1118_s_fu_3839_p3);
    sensitive << ( data_1_V_read_19_reg_4437 );

    SC_METHOD(thread_shl_ln6_fu_3828_p3);
    sensitive << ( data_1_V_read_19_reg_4437 );

    SC_METHOD(thread_shl_ln728_281_fu_3716_p3);
    sensitive << ( mul_ln1118_160_reg_3106 );

    SC_METHOD(thread_shl_ln728_282_fu_3728_p3);
    sensitive << ( mul_ln728_278_reg_3110 );

    SC_METHOD(thread_shl_ln728_283_fu_3740_p3);
    sensitive << ( mul_ln728_279_fu_179_p2 );

    SC_METHOD(thread_shl_ln728_284_fu_3752_p3);
    sensitive << ( mul_ln728_280_reg_3114 );

    SC_METHOD(thread_shl_ln728_285_fu_3764_p3);
    sensitive << ( mul_ln1118_161_reg_3118 );

    SC_METHOD(thread_shl_ln728_286_fu_3772_p3);
    sensitive << ( mul_ln728_281_reg_3122 );

    SC_METHOD(thread_shl_ln728_287_fu_3784_p3);
    sensitive << ( mul_ln728_282_reg_3126 );

    SC_METHOD(thread_shl_ln728_288_fu_3796_p3);
    sensitive << ( mul_ln728_283_reg_3130 );

    SC_METHOD(thread_shl_ln728_289_fu_3808_p3);
    sensitive << ( mul_ln728_284_reg_3134 );

    SC_METHOD(thread_shl_ln728_290_fu_3820_p3);
    sensitive << ( mul_ln728_285_reg_3138 );

    SC_METHOD(thread_shl_ln728_291_fu_3868_p3);
    sensitive << ( mul_ln1118_162_reg_3142 );

    SC_METHOD(thread_shl_ln728_292_fu_3876_p3);
    sensitive << ( mul_ln728_286_reg_3146 );

    SC_METHOD(thread_shl_ln728_293_fu_3888_p3);
    sensitive << ( mul_ln1118_163_reg_3150 );

    SC_METHOD(thread_shl_ln728_294_fu_3909_p3);
    sensitive << ( mul_ln1118_164_fu_189_p2 );

    SC_METHOD(thread_shl_ln728_295_fu_3921_p3);
    sensitive << ( mul_ln1118_165_fu_170_p2 );

    SC_METHOD(thread_shl_ln728_296_fu_3933_p3);
    sensitive << ( mul_ln728_287_fu_168_p2 );

    SC_METHOD(thread_shl_ln728_297_fu_3945_p3);
    sensitive << ( mul_ln1118_166_fu_169_p2 );

    SC_METHOD(thread_shl_ln728_298_fu_3953_p3);
    sensitive << ( mul_ln728_288_reg_3154 );

    SC_METHOD(thread_shl_ln728_299_fu_3965_p3);
    sensitive << ( mul_ln1118_167_fu_193_p2 );

    SC_METHOD(thread_shl_ln728_300_fu_3977_p3);
    sensitive << ( mul_ln1118_168_fu_180_p2 );

    SC_METHOD(thread_shl_ln728_301_fu_3989_p3);
    sensitive << ( mul_ln728_289_fu_190_p2 );

    SC_METHOD(thread_shl_ln728_302_fu_4001_p3);
    sensitive << ( mul_ln1118_169_reg_3158 );

    SC_METHOD(thread_shl_ln728_303_fu_4009_p3);
    sensitive << ( mul_ln1118_170_reg_3162 );

    SC_METHOD(thread_shl_ln728_304_fu_4017_p3);
    sensitive << ( mul_ln728_290_reg_3166 );

    SC_METHOD(thread_shl_ln728_305_fu_4029_p3);
    sensitive << ( mul_ln1118_171_reg_3170 );

    SC_METHOD(thread_shl_ln728_306_fu_4037_p3);
    sensitive << ( mul_ln1118_172_reg_3174 );

    SC_METHOD(thread_shl_ln728_307_fu_4049_p3);
    sensitive << ( mul_ln1118_173_fu_164_p2 );

    SC_METHOD(thread_shl_ln728_308_fu_4061_p3);
    sensitive << ( mul_ln728_291_reg_3178 );

    SC_METHOD(thread_shl_ln728_309_fu_4069_p3);
    sensitive << ( mul_ln728_292_reg_3182 );

    SC_METHOD(thread_shl_ln728_s_fu_3704_p3);
    sensitive << ( mul_ln1118_reg_3102 );

    SC_METHOD(thread_shl_ln_fu_3692_p3);
    sensitive << ( mul_ln728_reg_3098 );

    SC_METHOD(thread_sub_ln1118_fu_3850_p2);
    sensitive << ( zext_ln1118_225_fu_3835_p1 );
    sensitive << ( zext_ln1118_226_fu_3846_p1 );

    SC_METHOD(thread_tmp_5_fu_3856_p3);
    sensitive << ( sub_ln1118_fu_3850_p2 );

    SC_METHOD(thread_zext_ln1118_218_fu_3620_p1);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_zext_ln1118_220_fu_3631_p1);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_zext_ln1118_222_fu_3641_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_zext_ln1118_224_fu_3657_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_zext_ln1118_225_fu_3835_p1);
    sensitive << ( shl_ln6_fu_3828_p3 );

    SC_METHOD(thread_zext_ln1118_226_fu_3846_p1);
    sensitive << ( shl_ln1118_s_fu_3839_p3 );

    SC_METHOD(thread_zext_ln1118_228_fu_3900_p1);
    sensitive << ( data_2_V_read_19_reg_4431 );

    SC_METHOD(thread_zext_ln1118_229_fu_3961_p1);
    sensitive << ( shl_ln728_298_fu_3953_p3 );

    SC_METHOD(thread_zext_ln1118_230_fu_3669_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_zext_ln1118_232_fu_3679_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_zext_ln1118_233_fu_3686_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_zext_ln703_16_fu_4087_p1);
    sensitive << ( add_ln703_fu_4081_p2 );

    SC_METHOD(thread_zext_ln703_17_fu_4171_p1);
    sensitive << ( add_ln703_424_fu_4165_p2 );

    SC_METHOD(thread_zext_ln703_18_fu_4259_p1);
    sensitive << ( add_ln703_436_fu_4253_p2 );

    SC_METHOD(thread_zext_ln703_fu_4077_p1);
    sensitive << ( shl_ln728_309_fu_4069_p3 );

    SC_METHOD(thread_zext_ln728_252_fu_3700_p1);
    sensitive << ( shl_ln_fu_3692_p3 );

    SC_METHOD(thread_zext_ln728_253_fu_3736_p1);
    sensitive << ( shl_ln728_282_fu_3728_p3 );

    SC_METHOD(thread_zext_ln728_254_fu_3748_p1);
    sensitive << ( shl_ln728_283_fu_3740_p3 );

    SC_METHOD(thread_zext_ln728_255_fu_3760_p1);
    sensitive << ( shl_ln728_284_fu_3752_p3 );

    SC_METHOD(thread_zext_ln728_256_fu_3780_p1);
    sensitive << ( shl_ln728_286_fu_3772_p3 );

    SC_METHOD(thread_zext_ln728_258_fu_3792_p1);
    sensitive << ( shl_ln728_287_fu_3784_p3 );

    SC_METHOD(thread_zext_ln728_259_fu_3804_p1);
    sensitive << ( shl_ln728_288_fu_3796_p3 );

    SC_METHOD(thread_zext_ln728_260_fu_3816_p1);
    sensitive << ( shl_ln728_289_fu_3808_p3 );

    SC_METHOD(thread_zext_ln728_261_fu_3884_p1);
    sensitive << ( shl_ln728_292_fu_3876_p3 );

    SC_METHOD(thread_zext_ln728_263_fu_3941_p1);
    sensitive << ( shl_ln728_296_fu_3933_p3 );

    SC_METHOD(thread_zext_ln728_264_fu_3997_p1);
    sensitive << ( shl_ln728_301_fu_3989_p3 );

    SC_METHOD(thread_zext_ln728_265_fu_4025_p1);
    sensitive << ( shl_ln728_304_fu_4017_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_0_0_0_0_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, mul_ln728_fu_163_p2, "mul_ln728_fu_163_p2");
    sc_trace(mVcdFile, mul_ln728_reg_3098, "mul_ln728_reg_3098");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, mul_ln1118_fu_175_p2, "mul_ln1118_fu_175_p2");
    sc_trace(mVcdFile, mul_ln1118_reg_3102, "mul_ln1118_reg_3102");
    sc_trace(mVcdFile, mul_ln1118_160_fu_167_p2, "mul_ln1118_160_fu_167_p2");
    sc_trace(mVcdFile, mul_ln1118_160_reg_3106, "mul_ln1118_160_reg_3106");
    sc_trace(mVcdFile, mul_ln728_278_fu_191_p2, "mul_ln728_278_fu_191_p2");
    sc_trace(mVcdFile, mul_ln728_278_reg_3110, "mul_ln728_278_reg_3110");
    sc_trace(mVcdFile, mul_ln728_280_fu_177_p2, "mul_ln728_280_fu_177_p2");
    sc_trace(mVcdFile, mul_ln728_280_reg_3114, "mul_ln728_280_reg_3114");
    sc_trace(mVcdFile, mul_ln1118_161_fu_172_p2, "mul_ln1118_161_fu_172_p2");
    sc_trace(mVcdFile, mul_ln1118_161_reg_3118, "mul_ln1118_161_reg_3118");
    sc_trace(mVcdFile, mul_ln728_281_fu_184_p2, "mul_ln728_281_fu_184_p2");
    sc_trace(mVcdFile, mul_ln728_281_reg_3122, "mul_ln728_281_reg_3122");
    sc_trace(mVcdFile, mul_ln728_282_fu_187_p2, "mul_ln728_282_fu_187_p2");
    sc_trace(mVcdFile, mul_ln728_282_reg_3126, "mul_ln728_282_reg_3126");
    sc_trace(mVcdFile, mul_ln728_283_fu_162_p2, "mul_ln728_283_fu_162_p2");
    sc_trace(mVcdFile, mul_ln728_283_reg_3130, "mul_ln728_283_reg_3130");
    sc_trace(mVcdFile, mul_ln728_284_fu_186_p2, "mul_ln728_284_fu_186_p2");
    sc_trace(mVcdFile, mul_ln728_284_reg_3134, "mul_ln728_284_reg_3134");
    sc_trace(mVcdFile, mul_ln728_285_fu_174_p2, "mul_ln728_285_fu_174_p2");
    sc_trace(mVcdFile, mul_ln728_285_reg_3138, "mul_ln728_285_reg_3138");
    sc_trace(mVcdFile, mul_ln1118_162_fu_165_p2, "mul_ln1118_162_fu_165_p2");
    sc_trace(mVcdFile, mul_ln1118_162_reg_3142, "mul_ln1118_162_reg_3142");
    sc_trace(mVcdFile, mul_ln728_286_fu_176_p2, "mul_ln728_286_fu_176_p2");
    sc_trace(mVcdFile, mul_ln728_286_reg_3146, "mul_ln728_286_reg_3146");
    sc_trace(mVcdFile, mul_ln1118_163_fu_178_p2, "mul_ln1118_163_fu_178_p2");
    sc_trace(mVcdFile, mul_ln1118_163_reg_3150, "mul_ln1118_163_reg_3150");
    sc_trace(mVcdFile, mul_ln728_288_fu_188_p2, "mul_ln728_288_fu_188_p2");
    sc_trace(mVcdFile, mul_ln728_288_reg_3154, "mul_ln728_288_reg_3154");
    sc_trace(mVcdFile, mul_ln1118_169_fu_183_p2, "mul_ln1118_169_fu_183_p2");
    sc_trace(mVcdFile, mul_ln1118_169_reg_3158, "mul_ln1118_169_reg_3158");
    sc_trace(mVcdFile, mul_ln1118_170_fu_166_p2, "mul_ln1118_170_fu_166_p2");
    sc_trace(mVcdFile, mul_ln1118_170_reg_3162, "mul_ln1118_170_reg_3162");
    sc_trace(mVcdFile, mul_ln728_290_fu_185_p2, "mul_ln728_290_fu_185_p2");
    sc_trace(mVcdFile, mul_ln728_290_reg_3166, "mul_ln728_290_reg_3166");
    sc_trace(mVcdFile, mul_ln1118_171_fu_182_p2, "mul_ln1118_171_fu_182_p2");
    sc_trace(mVcdFile, mul_ln1118_171_reg_3170, "mul_ln1118_171_reg_3170");
    sc_trace(mVcdFile, mul_ln1118_172_fu_171_p2, "mul_ln1118_172_fu_171_p2");
    sc_trace(mVcdFile, mul_ln1118_172_reg_3174, "mul_ln1118_172_reg_3174");
    sc_trace(mVcdFile, mul_ln728_291_fu_192_p2, "mul_ln728_291_fu_192_p2");
    sc_trace(mVcdFile, mul_ln728_291_reg_3178, "mul_ln728_291_reg_3178");
    sc_trace(mVcdFile, mul_ln728_292_fu_181_p2, "mul_ln728_292_fu_181_p2");
    sc_trace(mVcdFile, mul_ln728_292_reg_3182, "mul_ln728_292_reg_3182");
    sc_trace(mVcdFile, data_2_V_read_19_reg_4431, "data_2_V_read_19_reg_4431");
    sc_trace(mVcdFile, data_1_V_read_19_reg_4437, "data_1_V_read_19_reg_4437");
    sc_trace(mVcdFile, zext_ln1118_220_fu_3631_p1, "zext_ln1118_220_fu_3631_p1");
    sc_trace(mVcdFile, zext_ln1118_220_reg_4443, "zext_ln1118_220_reg_4443");
    sc_trace(mVcdFile, zext_ln1118_230_fu_3669_p1, "zext_ln1118_230_fu_3669_p1");
    sc_trace(mVcdFile, zext_ln1118_230_reg_4448, "zext_ln1118_230_reg_4448");
    sc_trace(mVcdFile, mul_ln728_283_fu_162_p0, "mul_ln728_283_fu_162_p0");
    sc_trace(mVcdFile, zext_ln1118_224_fu_3657_p1, "zext_ln1118_224_fu_3657_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln728_fu_163_p0, "mul_ln728_fu_163_p0");
    sc_trace(mVcdFile, zext_ln1118_218_fu_3620_p1, "zext_ln1118_218_fu_3620_p1");
    sc_trace(mVcdFile, mul_ln1118_173_fu_164_p0, "mul_ln1118_173_fu_164_p0");
    sc_trace(mVcdFile, mul_ln1118_162_fu_165_p0, "mul_ln1118_162_fu_165_p0");
    sc_trace(mVcdFile, zext_ln1118_222_fu_3641_p1, "zext_ln1118_222_fu_3641_p1");
    sc_trace(mVcdFile, mul_ln1118_170_fu_166_p0, "mul_ln1118_170_fu_166_p0");
    sc_trace(mVcdFile, zext_ln1118_232_fu_3679_p1, "zext_ln1118_232_fu_3679_p1");
    sc_trace(mVcdFile, mul_ln1118_160_fu_167_p0, "mul_ln1118_160_fu_167_p0");
    sc_trace(mVcdFile, mul_ln728_287_fu_168_p0, "mul_ln728_287_fu_168_p0");
    sc_trace(mVcdFile, zext_ln1118_228_fu_3900_p1, "zext_ln1118_228_fu_3900_p1");
    sc_trace(mVcdFile, mul_ln1118_166_fu_169_p0, "mul_ln1118_166_fu_169_p0");
    sc_trace(mVcdFile, mul_ln1118_165_fu_170_p0, "mul_ln1118_165_fu_170_p0");
    sc_trace(mVcdFile, mul_ln1118_172_fu_171_p0, "mul_ln1118_172_fu_171_p0");
    sc_trace(mVcdFile, mul_ln1118_161_fu_172_p0, "mul_ln1118_161_fu_172_p0");
    sc_trace(mVcdFile, mul_ln728_285_fu_174_p0, "mul_ln728_285_fu_174_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_175_p0, "mul_ln1118_fu_175_p0");
    sc_trace(mVcdFile, mul_ln728_286_fu_176_p0, "mul_ln728_286_fu_176_p0");
    sc_trace(mVcdFile, mul_ln728_280_fu_177_p0, "mul_ln728_280_fu_177_p0");
    sc_trace(mVcdFile, mul_ln1118_163_fu_178_p0, "mul_ln1118_163_fu_178_p0");
    sc_trace(mVcdFile, mul_ln728_279_fu_179_p0, "mul_ln728_279_fu_179_p0");
    sc_trace(mVcdFile, mul_ln1118_168_fu_180_p0, "mul_ln1118_168_fu_180_p0");
    sc_trace(mVcdFile, mul_ln728_292_fu_181_p0, "mul_ln728_292_fu_181_p0");
    sc_trace(mVcdFile, mul_ln1118_171_fu_182_p0, "mul_ln1118_171_fu_182_p0");
    sc_trace(mVcdFile, zext_ln1118_233_fu_3686_p1, "zext_ln1118_233_fu_3686_p1");
    sc_trace(mVcdFile, mul_ln1118_169_fu_183_p0, "mul_ln1118_169_fu_183_p0");
    sc_trace(mVcdFile, mul_ln728_281_fu_184_p0, "mul_ln728_281_fu_184_p0");
    sc_trace(mVcdFile, mul_ln728_290_fu_185_p0, "mul_ln728_290_fu_185_p0");
    sc_trace(mVcdFile, mul_ln728_284_fu_186_p0, "mul_ln728_284_fu_186_p0");
    sc_trace(mVcdFile, mul_ln728_282_fu_187_p0, "mul_ln728_282_fu_187_p0");
    sc_trace(mVcdFile, mul_ln728_288_fu_188_p0, "mul_ln728_288_fu_188_p0");
    sc_trace(mVcdFile, mul_ln1118_164_fu_189_p0, "mul_ln1118_164_fu_189_p0");
    sc_trace(mVcdFile, mul_ln728_289_fu_190_p0, "mul_ln728_289_fu_190_p0");
    sc_trace(mVcdFile, mul_ln728_278_fu_191_p0, "mul_ln728_278_fu_191_p0");
    sc_trace(mVcdFile, mul_ln728_291_fu_192_p0, "mul_ln728_291_fu_192_p0");
    sc_trace(mVcdFile, mul_ln1118_167_fu_193_p0, "mul_ln1118_167_fu_193_p0");
    sc_trace(mVcdFile, shl_ln_fu_3692_p3, "shl_ln_fu_3692_p3");
    sc_trace(mVcdFile, shl_ln728_s_fu_3704_p3, "shl_ln728_s_fu_3704_p3");
    sc_trace(mVcdFile, shl_ln728_281_fu_3716_p3, "shl_ln728_281_fu_3716_p3");
    sc_trace(mVcdFile, shl_ln728_282_fu_3728_p3, "shl_ln728_282_fu_3728_p3");
    sc_trace(mVcdFile, mul_ln728_279_fu_179_p2, "mul_ln728_279_fu_179_p2");
    sc_trace(mVcdFile, shl_ln728_283_fu_3740_p3, "shl_ln728_283_fu_3740_p3");
    sc_trace(mVcdFile, shl_ln728_284_fu_3752_p3, "shl_ln728_284_fu_3752_p3");
    sc_trace(mVcdFile, shl_ln728_286_fu_3772_p3, "shl_ln728_286_fu_3772_p3");
    sc_trace(mVcdFile, shl_ln728_287_fu_3784_p3, "shl_ln728_287_fu_3784_p3");
    sc_trace(mVcdFile, shl_ln728_288_fu_3796_p3, "shl_ln728_288_fu_3796_p3");
    sc_trace(mVcdFile, shl_ln728_289_fu_3808_p3, "shl_ln728_289_fu_3808_p3");
    sc_trace(mVcdFile, shl_ln6_fu_3828_p3, "shl_ln6_fu_3828_p3");
    sc_trace(mVcdFile, shl_ln1118_s_fu_3839_p3, "shl_ln1118_s_fu_3839_p3");
    sc_trace(mVcdFile, zext_ln1118_225_fu_3835_p1, "zext_ln1118_225_fu_3835_p1");
    sc_trace(mVcdFile, zext_ln1118_226_fu_3846_p1, "zext_ln1118_226_fu_3846_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_3850_p2, "sub_ln1118_fu_3850_p2");
    sc_trace(mVcdFile, tmp_5_fu_3856_p3, "tmp_5_fu_3856_p3");
    sc_trace(mVcdFile, shl_ln728_292_fu_3876_p3, "shl_ln728_292_fu_3876_p3");
    sc_trace(mVcdFile, mul_ln1118_164_fu_189_p2, "mul_ln1118_164_fu_189_p2");
    sc_trace(mVcdFile, shl_ln728_294_fu_3909_p3, "shl_ln728_294_fu_3909_p3");
    sc_trace(mVcdFile, mul_ln1118_165_fu_170_p2, "mul_ln1118_165_fu_170_p2");
    sc_trace(mVcdFile, shl_ln728_295_fu_3921_p3, "shl_ln728_295_fu_3921_p3");
    sc_trace(mVcdFile, mul_ln728_287_fu_168_p2, "mul_ln728_287_fu_168_p2");
    sc_trace(mVcdFile, shl_ln728_296_fu_3933_p3, "shl_ln728_296_fu_3933_p3");
    sc_trace(mVcdFile, mul_ln1118_166_fu_169_p2, "mul_ln1118_166_fu_169_p2");
    sc_trace(mVcdFile, shl_ln728_298_fu_3953_p3, "shl_ln728_298_fu_3953_p3");
    sc_trace(mVcdFile, mul_ln1118_167_fu_193_p2, "mul_ln1118_167_fu_193_p2");
    sc_trace(mVcdFile, shl_ln728_299_fu_3965_p3, "shl_ln728_299_fu_3965_p3");
    sc_trace(mVcdFile, mul_ln1118_168_fu_180_p2, "mul_ln1118_168_fu_180_p2");
    sc_trace(mVcdFile, shl_ln728_300_fu_3977_p3, "shl_ln728_300_fu_3977_p3");
    sc_trace(mVcdFile, mul_ln728_289_fu_190_p2, "mul_ln728_289_fu_190_p2");
    sc_trace(mVcdFile, shl_ln728_301_fu_3989_p3, "shl_ln728_301_fu_3989_p3");
    sc_trace(mVcdFile, shl_ln728_304_fu_4017_p3, "shl_ln728_304_fu_4017_p3");
    sc_trace(mVcdFile, shl_ln728_306_fu_4037_p3, "shl_ln728_306_fu_4037_p3");
    sc_trace(mVcdFile, mul_ln1118_173_fu_164_p2, "mul_ln1118_173_fu_164_p2");
    sc_trace(mVcdFile, shl_ln728_307_fu_4049_p3, "shl_ln728_307_fu_4049_p3");
    sc_trace(mVcdFile, shl_ln728_309_fu_4069_p3, "shl_ln728_309_fu_4069_p3");
    sc_trace(mVcdFile, zext_ln728_258_fu_3792_p1, "zext_ln728_258_fu_3792_p1");
    sc_trace(mVcdFile, zext_ln728_252_fu_3700_p1, "zext_ln728_252_fu_3700_p1");
    sc_trace(mVcdFile, add_ln703_fu_4081_p2, "add_ln703_fu_4081_p2");
    sc_trace(mVcdFile, shl_ln728_302_fu_4001_p3, "shl_ln728_302_fu_4001_p3");
    sc_trace(mVcdFile, sext_ln728_135_fu_3917_p1, "sext_ln728_135_fu_3917_p1");
    sc_trace(mVcdFile, add_ln703_413_fu_4091_p2, "add_ln703_413_fu_4091_p2");
    sc_trace(mVcdFile, zext_ln703_16_fu_4087_p1, "zext_ln703_16_fu_4087_p1");
    sc_trace(mVcdFile, add_ln703_414_fu_4097_p2, "add_ln703_414_fu_4097_p2");
    sc_trace(mVcdFile, zext_ln728_259_fu_3804_p1, "zext_ln728_259_fu_3804_p1");
    sc_trace(mVcdFile, sext_ln728_fu_3712_p1, "sext_ln728_fu_3712_p1");
    sc_trace(mVcdFile, shl_ln728_303_fu_4009_p3, "shl_ln728_303_fu_4009_p3");
    sc_trace(mVcdFile, add_ln703_417_fu_4115_p2, "add_ln703_417_fu_4115_p2");
    sc_trace(mVcdFile, sext_ln728_136_fu_3929_p1, "sext_ln728_136_fu_3929_p1");
    sc_trace(mVcdFile, sext_ln703_fu_4121_p1, "sext_ln703_fu_4121_p1");
    sc_trace(mVcdFile, add_ln703_416_fu_4109_p2, "add_ln703_416_fu_4109_p2");
    sc_trace(mVcdFile, add_ln703_418_fu_4125_p2, "add_ln703_418_fu_4125_p2");
    sc_trace(mVcdFile, zext_ln728_260_fu_3816_p1, "zext_ln728_260_fu_3816_p1");
    sc_trace(mVcdFile, sext_ln728_133_fu_3724_p1, "sext_ln728_133_fu_3724_p1");
    sc_trace(mVcdFile, add_ln703_420_fu_4137_p2, "add_ln703_420_fu_4137_p2");
    sc_trace(mVcdFile, zext_ln728_265_fu_4025_p1, "zext_ln728_265_fu_4025_p1");
    sc_trace(mVcdFile, zext_ln728_263_fu_3941_p1, "zext_ln728_263_fu_3941_p1");
    sc_trace(mVcdFile, add_ln703_421_fu_4147_p2, "add_ln703_421_fu_4147_p2");
    sc_trace(mVcdFile, sext_ln703_19_fu_4143_p1, "sext_ln703_19_fu_4143_p1");
    sc_trace(mVcdFile, add_ln703_422_fu_4153_p2, "add_ln703_422_fu_4153_p2");
    sc_trace(mVcdFile, shl_ln728_290_fu_3820_p3, "shl_ln728_290_fu_3820_p3");
    sc_trace(mVcdFile, zext_ln728_253_fu_3736_p1, "zext_ln728_253_fu_3736_p1");
    sc_trace(mVcdFile, add_ln703_424_fu_4165_p2, "add_ln703_424_fu_4165_p2");
    sc_trace(mVcdFile, shl_ln728_305_fu_4029_p3, "shl_ln728_305_fu_4029_p3");
    sc_trace(mVcdFile, shl_ln728_297_fu_3945_p3, "shl_ln728_297_fu_3945_p3");
    sc_trace(mVcdFile, add_ln703_425_fu_4175_p2, "add_ln703_425_fu_4175_p2");
    sc_trace(mVcdFile, zext_ln703_17_fu_4171_p1, "zext_ln703_17_fu_4171_p1");
    sc_trace(mVcdFile, add_ln703_426_fu_4181_p2, "add_ln703_426_fu_4181_p2");
    sc_trace(mVcdFile, sext_ln728_134_fu_3864_p1, "sext_ln728_134_fu_3864_p1");
    sc_trace(mVcdFile, zext_ln728_254_fu_3748_p1, "zext_ln728_254_fu_3748_p1");
    sc_trace(mVcdFile, sext_ln1118_fu_4045_p1, "sext_ln1118_fu_4045_p1");
    sc_trace(mVcdFile, add_ln703_429_fu_4199_p2, "add_ln703_429_fu_4199_p2");
    sc_trace(mVcdFile, zext_ln1118_229_fu_3961_p1, "zext_ln1118_229_fu_3961_p1");
    sc_trace(mVcdFile, sext_ln703_20_fu_4205_p1, "sext_ln703_20_fu_4205_p1");
    sc_trace(mVcdFile, add_ln703_430_fu_4209_p2, "add_ln703_430_fu_4209_p2");
    sc_trace(mVcdFile, add_ln703_428_fu_4193_p2, "add_ln703_428_fu_4193_p2");
    sc_trace(mVcdFile, sext_ln703_21_fu_4215_p1, "sext_ln703_21_fu_4215_p1");
    sc_trace(mVcdFile, zext_ln728_255_fu_3760_p1, "zext_ln728_255_fu_3760_p1");
    sc_trace(mVcdFile, shl_ln728_291_fu_3868_p3, "shl_ln728_291_fu_3868_p3");
    sc_trace(mVcdFile, add_ln703_432_fu_4225_p2, "add_ln703_432_fu_4225_p2");
    sc_trace(mVcdFile, sext_ln728_139_fu_4057_p1, "sext_ln728_139_fu_4057_p1");
    sc_trace(mVcdFile, sext_ln728_137_fu_3973_p1, "sext_ln728_137_fu_3973_p1");
    sc_trace(mVcdFile, sext_ln703_22_fu_4231_p1, "sext_ln703_22_fu_4231_p1");
    sc_trace(mVcdFile, add_ln703_433_fu_4235_p2, "add_ln703_433_fu_4235_p2");
    sc_trace(mVcdFile, zext_ln728_261_fu_3884_p1, "zext_ln728_261_fu_3884_p1");
    sc_trace(mVcdFile, shl_ln728_285_fu_3764_p3, "shl_ln728_285_fu_3764_p3");
    sc_trace(mVcdFile, shl_ln728_308_fu_4061_p3, "shl_ln728_308_fu_4061_p3");
    sc_trace(mVcdFile, add_ln703_436_fu_4253_p2, "add_ln703_436_fu_4253_p2");
    sc_trace(mVcdFile, sext_ln728_138_fu_3985_p1, "sext_ln728_138_fu_3985_p1");
    sc_trace(mVcdFile, zext_ln703_18_fu_4259_p1, "zext_ln703_18_fu_4259_p1");
    sc_trace(mVcdFile, add_ln703_435_fu_4247_p2, "add_ln703_435_fu_4247_p2");
    sc_trace(mVcdFile, add_ln703_437_fu_4263_p2, "add_ln703_437_fu_4263_p2");
    sc_trace(mVcdFile, shl_ln728_293_fu_3888_p3, "shl_ln728_293_fu_3888_p3");
    sc_trace(mVcdFile, zext_ln728_256_fu_3780_p1, "zext_ln728_256_fu_3780_p1");
    sc_trace(mVcdFile, zext_ln703_fu_4077_p1, "zext_ln703_fu_4077_p1");
    sc_trace(mVcdFile, add_ln703_440_fu_4281_p2, "add_ln703_440_fu_4281_p2");
    sc_trace(mVcdFile, zext_ln728_264_fu_3997_p1, "zext_ln728_264_fu_3997_p1");
    sc_trace(mVcdFile, sext_ln703_23_fu_4287_p1, "sext_ln703_23_fu_4287_p1");
    sc_trace(mVcdFile, add_ln703_439_fu_4275_p2, "add_ln703_439_fu_4275_p2");
    sc_trace(mVcdFile, add_ln703_441_fu_4291_p2, "add_ln703_441_fu_4291_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_4103_p2, "p_Val2_s_fu_4103_p2");
    sc_trace(mVcdFile, acc_1_V_fu_4131_p2, "acc_1_V_fu_4131_p2");
    sc_trace(mVcdFile, acc_2_V_fu_4159_p2, "acc_2_V_fu_4159_p2");
    sc_trace(mVcdFile, acc_3_V_fu_4187_p2, "acc_3_V_fu_4187_p2");
    sc_trace(mVcdFile, acc_4_V_fu_4219_p2, "acc_4_V_fu_4219_p2");
    sc_trace(mVcdFile, acc_5_V_fu_4241_p2, "acc_5_V_fu_4241_p2");
    sc_trace(mVcdFile, acc_6_V_fu_4269_p2, "acc_6_V_fu_4269_p2");
    sc_trace(mVcdFile, acc_7_V_fu_4297_p2, "acc_7_V_fu_4297_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
    sc_trace(mVcdFile, ap_return_2_int_reg, "ap_return_2_int_reg");
    sc_trace(mVcdFile, ap_return_3_int_reg, "ap_return_3_int_reg");
    sc_trace(mVcdFile, ap_return_4_int_reg, "ap_return_4_int_reg");
    sc_trace(mVcdFile, ap_return_5_int_reg, "ap_return_5_int_reg");
    sc_trace(mVcdFile, ap_return_6_int_reg, "ap_return_6_int_reg");
    sc_trace(mVcdFile, ap_return_7_int_reg, "ap_return_7_int_reg");
    sc_trace(mVcdFile, mul_ln1118_161_fu_172_p00, "mul_ln1118_161_fu_172_p00");
    sc_trace(mVcdFile, mul_ln1118_163_fu_178_p00, "mul_ln1118_163_fu_178_p00");
    sc_trace(mVcdFile, mul_ln1118_166_fu_169_p00, "mul_ln1118_166_fu_169_p00");
    sc_trace(mVcdFile, mul_ln1118_172_fu_171_p00, "mul_ln1118_172_fu_171_p00");
    sc_trace(mVcdFile, mul_ln1118_fu_175_p00, "mul_ln1118_fu_175_p00");
    sc_trace(mVcdFile, mul_ln728_278_fu_191_p00, "mul_ln728_278_fu_191_p00");
    sc_trace(mVcdFile, mul_ln728_280_fu_177_p00, "mul_ln728_280_fu_177_p00");
    sc_trace(mVcdFile, mul_ln728_281_fu_184_p00, "mul_ln728_281_fu_184_p00");
    sc_trace(mVcdFile, mul_ln728_282_fu_187_p00, "mul_ln728_282_fu_187_p00");
    sc_trace(mVcdFile, mul_ln728_288_fu_188_p00, "mul_ln728_288_fu_188_p00");
    sc_trace(mVcdFile, mul_ln728_292_fu_181_p00, "mul_ln728_292_fu_181_p00");
#endif

    }
}

dense_latency_0_0_0_0_0_0_0_0_0::~dense_latency_0_0_0_0_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = p_Val2_s_fu_4103_p2.read().range(51, 29);
        ap_return_1_int_reg = acc_1_V_fu_4131_p2.read().range(51, 29);
        ap_return_2_int_reg = acc_2_V_fu_4159_p2.read().range(51, 29);
        ap_return_3_int_reg = acc_3_V_fu_4187_p2.read().range(51, 29);
        ap_return_4_int_reg = acc_4_V_fu_4219_p2.read().range(51, 29);
        ap_return_5_int_reg = acc_5_V_fu_4241_p2.read().range(51, 29);
        ap_return_6_int_reg = acc_6_V_fu_4269_p2.read().range(51, 29);
        ap_return_7_int_reg = acc_7_V_fu_4297_p2.read().range(51, 29);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        data_1_V_read_19_reg_4437 = data_1_V_read.read();
        data_2_V_read_19_reg_4431 = data_2_V_read.read();
        mul_ln1118_160_reg_3106 = mul_ln1118_160_fu_167_p2.read();
        mul_ln1118_161_reg_3118 = mul_ln1118_161_fu_172_p2.read();
        mul_ln1118_162_reg_3142 = mul_ln1118_162_fu_165_p2.read();
        mul_ln1118_163_reg_3150 = mul_ln1118_163_fu_178_p2.read();
        mul_ln1118_169_reg_3158 = mul_ln1118_169_fu_183_p2.read();
        mul_ln1118_170_reg_3162 = mul_ln1118_170_fu_166_p2.read();
        mul_ln1118_171_reg_3170 = mul_ln1118_171_fu_182_p2.read();
        mul_ln1118_172_reg_3174 = mul_ln1118_172_fu_171_p2.read();
        mul_ln1118_reg_3102 = mul_ln1118_fu_175_p2.read();
        mul_ln728_278_reg_3110 = mul_ln728_278_fu_191_p2.read();
        mul_ln728_280_reg_3114 = mul_ln728_280_fu_177_p2.read();
        mul_ln728_281_reg_3122 = mul_ln728_281_fu_184_p2.read();
        mul_ln728_282_reg_3126 = mul_ln728_282_fu_187_p2.read();
        mul_ln728_283_reg_3130 = mul_ln728_283_fu_162_p2.read();
        mul_ln728_284_reg_3134 = mul_ln728_284_fu_186_p2.read();
        mul_ln728_285_reg_3138 = mul_ln728_285_fu_174_p2.read();
        mul_ln728_286_reg_3146 = mul_ln728_286_fu_176_p2.read();
        mul_ln728_288_reg_3154 = mul_ln728_288_fu_188_p2.read();
        mul_ln728_290_reg_3166 = mul_ln728_290_fu_185_p2.read();
        mul_ln728_291_reg_3178 = mul_ln728_291_fu_192_p2.read();
        mul_ln728_292_reg_3182 = mul_ln728_292_fu_181_p2.read();
        mul_ln728_reg_3098 = mul_ln728_fu_163_p2.read();
        zext_ln1118_220_reg_4443 = zext_ln1118_220_fu_3631_p1.read();
        zext_ln1118_230_reg_4448 = zext_ln1118_230_fu_3669_p1.read();
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_1_V_fu_4131_p2() {
    acc_1_V_fu_4131_p2 = (!add_ln703_416_fu_4109_p2.read().is_01() || !add_ln703_418_fu_4125_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(add_ln703_416_fu_4109_p2.read()) + sc_biguint<52>(add_ln703_418_fu_4125_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_2_V_fu_4159_p2() {
    acc_2_V_fu_4159_p2 = (!sext_ln703_19_fu_4143_p1.read().is_01() || !add_ln703_422_fu_4153_p2.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln703_19_fu_4143_p1.read()) + sc_biguint<52>(add_ln703_422_fu_4153_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_3_V_fu_4187_p2() {
    acc_3_V_fu_4187_p2 = (!zext_ln703_17_fu_4171_p1.read().is_01() || !add_ln703_426_fu_4181_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln703_17_fu_4171_p1.read()) + sc_biguint<52>(add_ln703_426_fu_4181_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_4_V_fu_4219_p2() {
    acc_4_V_fu_4219_p2 = (!add_ln703_428_fu_4193_p2.read().is_01() || !sext_ln703_21_fu_4215_p1.read().is_01())? sc_lv<52>(): (sc_biguint<52>(add_ln703_428_fu_4193_p2.read()) + sc_bigint<52>(sext_ln703_21_fu_4215_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_5_V_fu_4241_p2() {
    acc_5_V_fu_4241_p2 = (!sext_ln703_22_fu_4231_p1.read().is_01() || !add_ln703_433_fu_4235_p2.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln703_22_fu_4231_p1.read()) + sc_biguint<52>(add_ln703_433_fu_4235_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_6_V_fu_4269_p2() {
    acc_6_V_fu_4269_p2 = (!add_ln703_435_fu_4247_p2.read().is_01() || !add_ln703_437_fu_4263_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(add_ln703_435_fu_4247_p2.read()) + sc_biguint<52>(add_ln703_437_fu_4263_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_acc_7_V_fu_4297_p2() {
    acc_7_V_fu_4297_p2 = (!add_ln703_439_fu_4275_p2.read().is_01() || !add_ln703_441_fu_4291_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(add_ln703_439_fu_4275_p2.read()) + sc_biguint<52>(add_ln703_441_fu_4291_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_413_fu_4091_p2() {
    add_ln703_413_fu_4091_p2 = (!shl_ln728_302_fu_4001_p3.read().is_01() || !ap_const_lv52_FEBE800000000.is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_302_fu_4001_p3.read()) + sc_bigint<52>(ap_const_lv52_FEBE800000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_414_fu_4097_p2() {
    add_ln703_414_fu_4097_p2 = (!sext_ln728_135_fu_3917_p1.read().is_01() || !add_ln703_413_fu_4091_p2.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln728_135_fu_3917_p1.read()) + sc_biguint<52>(add_ln703_413_fu_4091_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_416_fu_4109_p2() {
    add_ln703_416_fu_4109_p2 = (!zext_ln728_259_fu_3804_p1.read().is_01() || !sext_ln728_fu_3712_p1.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln728_259_fu_3804_p1.read()) + sc_bigint<52>(sext_ln728_fu_3712_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_417_fu_4115_p2() {
    add_ln703_417_fu_4115_p2 = (!shl_ln728_303_fu_4009_p3.read().is_01() || !ap_const_lv51_7EEF000000000.is_01())? sc_lv<51>(): (sc_biguint<51>(shl_ln728_303_fu_4009_p3.read()) + sc_bigint<51>(ap_const_lv51_7EEF000000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_418_fu_4125_p2() {
    add_ln703_418_fu_4125_p2 = (!sext_ln728_136_fu_3929_p1.read().is_01() || !sext_ln703_fu_4121_p1.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln728_136_fu_3929_p1.read()) + sc_bigint<52>(sext_ln703_fu_4121_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_420_fu_4137_p2() {
    add_ln703_420_fu_4137_p2 = (!zext_ln728_260_fu_3816_p1.read().is_01() || !sext_ln728_133_fu_3724_p1.read().is_01())? sc_lv<51>(): (sc_biguint<51>(zext_ln728_260_fu_3816_p1.read()) + sc_bigint<51>(sext_ln728_133_fu_3724_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_421_fu_4147_p2() {
    add_ln703_421_fu_4147_p2 = (!zext_ln728_265_fu_4025_p1.read().is_01() || !ap_const_lv52_FEF6C00000000.is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln728_265_fu_4025_p1.read()) + sc_bigint<52>(ap_const_lv52_FEF6C00000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_422_fu_4153_p2() {
    add_ln703_422_fu_4153_p2 = (!zext_ln728_263_fu_3941_p1.read().is_01() || !add_ln703_421_fu_4147_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln728_263_fu_3941_p1.read()) + sc_biguint<52>(add_ln703_421_fu_4147_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_424_fu_4165_p2() {
    add_ln703_424_fu_4165_p2 = (!shl_ln728_290_fu_3820_p3.read().is_01() || !zext_ln728_253_fu_3736_p1.read().is_01())? sc_lv<51>(): (sc_biguint<51>(shl_ln728_290_fu_3820_p3.read()) + sc_biguint<51>(zext_ln728_253_fu_3736_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_425_fu_4175_p2() {
    add_ln703_425_fu_4175_p2 = (!shl_ln728_305_fu_4029_p3.read().is_01() || !ap_const_lv52_FEE5800000000.is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_305_fu_4029_p3.read()) + sc_bigint<52>(ap_const_lv52_FEE5800000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_426_fu_4181_p2() {
    add_ln703_426_fu_4181_p2 = (!shl_ln728_297_fu_3945_p3.read().is_01() || !add_ln703_425_fu_4175_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_297_fu_3945_p3.read()) + sc_biguint<52>(add_ln703_425_fu_4175_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_428_fu_4193_p2() {
    add_ln703_428_fu_4193_p2 = (!sext_ln728_134_fu_3864_p1.read().is_01() || !zext_ln728_254_fu_3748_p1.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln728_134_fu_3864_p1.read()) + sc_biguint<52>(zext_ln728_254_fu_3748_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_429_fu_4199_p2() {
    add_ln703_429_fu_4199_p2 = (!sext_ln1118_fu_4045_p1.read().is_01() || !ap_const_lv48_EBD000000000.is_01())? sc_lv<48>(): (sc_bigint<48>(sext_ln1118_fu_4045_p1.read()) + sc_bigint<48>(ap_const_lv48_EBD000000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_430_fu_4209_p2() {
    add_ln703_430_fu_4209_p2 = (!zext_ln1118_229_fu_3961_p1.read().is_01() || !sext_ln703_20_fu_4205_p1.read().is_01())? sc_lv<49>(): (sc_biguint<49>(zext_ln1118_229_fu_3961_p1.read()) + sc_bigint<49>(sext_ln703_20_fu_4205_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_432_fu_4225_p2() {
    add_ln703_432_fu_4225_p2 = (!zext_ln728_255_fu_3760_p1.read().is_01() || !shl_ln728_291_fu_3868_p3.read().is_01())? sc_lv<50>(): (sc_biguint<50>(zext_ln728_255_fu_3760_p1.read()) + sc_biguint<50>(shl_ln728_291_fu_3868_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_433_fu_4235_p2() {
    add_ln703_433_fu_4235_p2 = (!sext_ln728_139_fu_4057_p1.read().is_01() || !sext_ln728_137_fu_3973_p1.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln728_139_fu_4057_p1.read()) + sc_bigint<52>(sext_ln728_137_fu_3973_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_435_fu_4247_p2() {
    add_ln703_435_fu_4247_p2 = (!zext_ln728_261_fu_3884_p1.read().is_01() || !shl_ln728_285_fu_3764_p3.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln728_261_fu_3884_p1.read()) + sc_biguint<52>(shl_ln728_285_fu_3764_p3.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_436_fu_4253_p2() {
    add_ln703_436_fu_4253_p2 = (!shl_ln728_308_fu_4061_p3.read().is_01() || !ap_const_lv51_B3800000000.is_01())? sc_lv<51>(): (sc_biguint<51>(shl_ln728_308_fu_4061_p3.read()) + sc_biguint<51>(ap_const_lv51_B3800000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_437_fu_4263_p2() {
    add_ln703_437_fu_4263_p2 = (!sext_ln728_138_fu_3985_p1.read().is_01() || !zext_ln703_18_fu_4259_p1.read().is_01())? sc_lv<52>(): (sc_bigint<52>(sext_ln728_138_fu_3985_p1.read()) + sc_biguint<52>(zext_ln703_18_fu_4259_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_439_fu_4275_p2() {
    add_ln703_439_fu_4275_p2 = (!shl_ln728_293_fu_3888_p3.read().is_01() || !zext_ln728_256_fu_3780_p1.read().is_01())? sc_lv<52>(): (sc_biguint<52>(shl_ln728_293_fu_3888_p3.read()) + sc_biguint<52>(zext_ln728_256_fu_3780_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_440_fu_4281_p2() {
    add_ln703_440_fu_4281_p2 = (!zext_ln703_fu_4077_p1.read().is_01() || !ap_const_lv51_7FBF800000000.is_01())? sc_lv<51>(): (sc_biguint<51>(zext_ln703_fu_4077_p1.read()) + sc_bigint<51>(ap_const_lv51_7FBF800000000));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_441_fu_4291_p2() {
    add_ln703_441_fu_4291_p2 = (!zext_ln728_264_fu_3997_p1.read().is_01() || !sext_ln703_23_fu_4287_p1.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln728_264_fu_3997_p1.read()) + sc_bigint<52>(sext_ln703_23_fu_4287_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_add_ln703_fu_4081_p2() {
    add_ln703_fu_4081_p2 = (!zext_ln728_258_fu_3792_p1.read().is_01() || !zext_ln728_252_fu_3700_p1.read().is_01())? sc_lv<50>(): (sc_biguint<50>(zext_ln728_258_fu_3792_p1.read()) + sc_biguint<50>(zext_ln728_252_fu_3700_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = p_Val2_s_fu_4103_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = acc_1_V_fu_4131_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_2() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_2 = ap_return_2_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_2 = acc_2_V_fu_4159_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_3() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_3 = ap_return_3_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_3 = acc_3_V_fu_4187_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_4() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_4 = ap_return_4_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_4 = acc_4_V_fu_4219_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_5() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_5 = ap_return_5_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_5 = acc_5_V_fu_4241_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_6() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_6 = ap_return_6_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_6 = acc_6_V_fu_4269_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_ap_return_7() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_7 = ap_return_7_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_7 = acc_7_V_fu_4297_p2.read().range(51, 29);
    }
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_160_fu_167_p0() {
    mul_ln1118_160_fu_167_p0 =  (sc_lv<22>) (zext_ln1118_218_fu_3620_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_160_fu_167_p2() {
    mul_ln1118_160_fu_167_p2 = (!mul_ln1118_160_fu_167_p0.read().is_01() || !ap_const_lv34_3FFFFFA4B.is_01())? sc_lv<34>(): sc_biguint<22>(mul_ln1118_160_fu_167_p0.read()) * sc_bigint<34>(ap_const_lv34_3FFFFFA4B);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_161_fu_172_p0() {
    mul_ln1118_161_fu_172_p0 =  (sc_lv<22>) (mul_ln1118_161_fu_172_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_161_fu_172_p00() {
    mul_ln1118_161_fu_172_p00 = esl_zext<37,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_161_fu_172_p2() {
    mul_ln1118_161_fu_172_p2 = (!mul_ln1118_161_fu_172_p0.read().is_01() || !ap_const_lv37_1FFFFFD262.is_01())? sc_lv<37>(): sc_biguint<22>(mul_ln1118_161_fu_172_p0.read()) * sc_bigint<37>(ap_const_lv37_1FFFFFD262);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_162_fu_165_p0() {
    mul_ln1118_162_fu_165_p0 =  (sc_lv<22>) (zext_ln1118_222_fu_3641_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_162_fu_165_p2() {
    mul_ln1118_162_fu_165_p2 = (!mul_ln1118_162_fu_165_p0.read().is_01() || !ap_const_lv35_7FFFFF4B7.is_01())? sc_lv<35>(): sc_biguint<22>(mul_ln1118_162_fu_165_p0.read()) * sc_bigint<35>(ap_const_lv35_7FFFFF4B7);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_163_fu_178_p0() {
    mul_ln1118_163_fu_178_p0 =  (sc_lv<22>) (mul_ln1118_163_fu_178_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_163_fu_178_p00() {
    mul_ln1118_163_fu_178_p00 = esl_zext<37,22>(data_1_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_163_fu_178_p2() {
    mul_ln1118_163_fu_178_p2 = (!mul_ln1118_163_fu_178_p0.read().is_01() || !ap_const_lv37_1FFFFFD516.is_01())? sc_lv<37>(): sc_biguint<22>(mul_ln1118_163_fu_178_p0.read()) * sc_bigint<37>(ap_const_lv37_1FFFFFD516);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_164_fu_189_p0() {
    mul_ln1118_164_fu_189_p0 =  (sc_lv<22>) (zext_ln1118_228_fu_3900_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_164_fu_189_p2() {
    mul_ln1118_164_fu_189_p2 = (!mul_ln1118_164_fu_189_p0.read().is_01() || !ap_const_lv36_FFFFFECEA.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln1118_164_fu_189_p0.read()) * sc_bigint<36>(ap_const_lv36_FFFFFECEA);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_165_fu_170_p0() {
    mul_ln1118_165_fu_170_p0 =  (sc_lv<22>) (zext_ln1118_228_fu_3900_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_165_fu_170_p2() {
    mul_ln1118_165_fu_170_p2 = (!mul_ln1118_165_fu_170_p0.read().is_01() || !ap_const_lv36_FFFFFE3A6.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln1118_165_fu_170_p0.read()) * sc_bigint<36>(ap_const_lv36_FFFFFE3A6);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_166_fu_169_p0() {
    mul_ln1118_166_fu_169_p0 =  (sc_lv<22>) (mul_ln1118_166_fu_169_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_166_fu_169_p00() {
    mul_ln1118_166_fu_169_p00 = esl_zext<37,22>(data_2_V_read_19_reg_4431.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_166_fu_169_p2() {
    mul_ln1118_166_fu_169_p2 = (!mul_ln1118_166_fu_169_p0.read().is_01() || !ap_const_lv37_1FFFFFD21C.is_01())? sc_lv<37>(): sc_biguint<22>(mul_ln1118_166_fu_169_p0.read()) * sc_bigint<37>(ap_const_lv37_1FFFFFD21C);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_167_fu_193_p0() {
    mul_ln1118_167_fu_193_p0 =  (sc_lv<22>) (zext_ln1118_228_fu_3900_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_167_fu_193_p2() {
    mul_ln1118_167_fu_193_p2 = (!mul_ln1118_167_fu_193_p0.read().is_01() || !ap_const_lv36_FFFFFE86B.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln1118_167_fu_193_p0.read()) * sc_bigint<36>(ap_const_lv36_FFFFFE86B);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_168_fu_180_p0() {
    mul_ln1118_168_fu_180_p0 =  (sc_lv<22>) (zext_ln1118_228_fu_3900_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_168_fu_180_p2() {
    mul_ln1118_168_fu_180_p2 = (!mul_ln1118_168_fu_180_p0.read().is_01() || !ap_const_lv36_FFFFFEB88.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln1118_168_fu_180_p0.read()) * sc_bigint<36>(ap_const_lv36_FFFFFEB88);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_169_fu_183_p0() {
    mul_ln1118_169_fu_183_p0 =  (sc_lv<22>) (zext_ln1118_233_fu_3686_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_169_fu_183_p2() {
    mul_ln1118_169_fu_183_p2 = (!mul_ln1118_169_fu_183_p0.read().is_01() || !ap_const_lv37_1FFFFFD9F7.is_01())? sc_lv<37>(): sc_biguint<22>(mul_ln1118_169_fu_183_p0.read()) * sc_bigint<37>(ap_const_lv37_1FFFFFD9F7);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_170_fu_166_p0() {
    mul_ln1118_170_fu_166_p0 =  (sc_lv<22>) (zext_ln1118_232_fu_3679_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_170_fu_166_p2() {
    mul_ln1118_170_fu_166_p2 = (!mul_ln1118_170_fu_166_p0.read().is_01() || !ap_const_lv36_FFFFFEF70.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln1118_170_fu_166_p0.read()) * sc_bigint<36>(ap_const_lv36_FFFFFEF70);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_171_fu_182_p0() {
    mul_ln1118_171_fu_182_p0 =  (sc_lv<22>) (zext_ln1118_233_fu_3686_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_171_fu_182_p2() {
    mul_ln1118_171_fu_182_p2 = (!mul_ln1118_171_fu_182_p0.read().is_01() || !ap_const_lv37_1FFFFFDF8C.is_01())? sc_lv<37>(): sc_biguint<22>(mul_ln1118_171_fu_182_p0.read()) * sc_bigint<37>(ap_const_lv37_1FFFFFDF8C);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_172_fu_171_p0() {
    mul_ln1118_172_fu_171_p0 =  (sc_lv<22>) (mul_ln1118_172_fu_171_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_172_fu_171_p00() {
    mul_ln1118_172_fu_171_p00 = esl_zext<32,22>(data_3_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_172_fu_171_p2() {
    mul_ln1118_172_fu_171_p2 = (!mul_ln1118_172_fu_171_p0.read().is_01() || !ap_const_lv32_FFFFFE83.is_01())? sc_lv<32>(): sc_biguint<22>(mul_ln1118_172_fu_171_p0.read()) * sc_bigint<32>(ap_const_lv32_FFFFFE83);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_173_fu_164_p0() {
    mul_ln1118_173_fu_164_p0 =  (sc_lv<22>) (zext_ln1118_230_reg_4448.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_173_fu_164_p2() {
    mul_ln1118_173_fu_164_p2 = (!mul_ln1118_173_fu_164_p0.read().is_01() || !ap_const_lv35_7FFFFF5FE.is_01())? sc_lv<35>(): sc_biguint<22>(mul_ln1118_173_fu_164_p0.read()) * sc_bigint<35>(ap_const_lv35_7FFFFF5FE);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_fu_175_p0() {
    mul_ln1118_fu_175_p0 =  (sc_lv<22>) (mul_ln1118_fu_175_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_fu_175_p00() {
    mul_ln1118_fu_175_p00 = esl_zext<36,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln1118_fu_175_p2() {
    mul_ln1118_fu_175_p2 = (!mul_ln1118_fu_175_p0.read().is_01() || !ap_const_lv36_FFFFFEDA3.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln1118_fu_175_p0.read()) * sc_bigint<36>(ap_const_lv36_FFFFFEDA3);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_278_fu_191_p0() {
    mul_ln728_278_fu_191_p0 =  (sc_lv<22>) (mul_ln728_278_fu_191_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_278_fu_191_p00() {
    mul_ln728_278_fu_191_p00 = esl_zext<32,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_278_fu_191_p2() {
    mul_ln728_278_fu_191_p2 = (!mul_ln728_278_fu_191_p0.read().is_01() || !ap_const_lv32_27F.is_01())? sc_lv<32>(): sc_biguint<22>(mul_ln728_278_fu_191_p0.read()) * sc_biguint<32>(ap_const_lv32_27F);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_279_fu_179_p0() {
    mul_ln728_279_fu_179_p0 =  (sc_lv<22>) (zext_ln1118_220_reg_4443.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_279_fu_179_p2() {
    mul_ln728_279_fu_179_p2 = (!mul_ln728_279_fu_179_p0.read().is_01() || !ap_const_lv35_1F20.is_01())? sc_lv<35>(): sc_biguint<22>(mul_ln728_279_fu_179_p0.read()) * sc_biguint<35>(ap_const_lv35_1F20);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_280_fu_177_p0() {
    mul_ln728_280_fu_177_p0 =  (sc_lv<22>) (mul_ln728_280_fu_177_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_280_fu_177_p00() {
    mul_ln728_280_fu_177_p00 = esl_zext<33,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_280_fu_177_p2() {
    mul_ln728_280_fu_177_p2 = (!mul_ln728_280_fu_177_p0.read().is_01() || !ap_const_lv33_6AA.is_01())? sc_lv<33>(): sc_biguint<22>(mul_ln728_280_fu_177_p0.read()) * sc_biguint<33>(ap_const_lv33_6AA);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_281_fu_184_p0() {
    mul_ln728_281_fu_184_p0 =  (sc_lv<22>) (mul_ln728_281_fu_184_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_281_fu_184_p00() {
    mul_ln728_281_fu_184_p00 = esl_zext<35,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_281_fu_184_p2() {
    mul_ln728_281_fu_184_p2 = (!mul_ln728_281_fu_184_p0.read().is_01() || !ap_const_lv35_1240.is_01())? sc_lv<35>(): sc_biguint<22>(mul_ln728_281_fu_184_p0.read()) * sc_biguint<35>(ap_const_lv35_1240);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_282_fu_187_p0() {
    mul_ln728_282_fu_187_p0 =  (sc_lv<22>) (mul_ln728_282_fu_187_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_282_fu_187_p00() {
    mul_ln728_282_fu_187_p00 = esl_zext<31,22>(data_1_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_282_fu_187_p2() {
    mul_ln728_282_fu_187_p2 = (!mul_ln728_282_fu_187_p0.read().is_01() || !ap_const_lv31_1B8.is_01())? sc_lv<31>(): sc_biguint<22>(mul_ln728_282_fu_187_p0.read()) * sc_biguint<31>(ap_const_lv31_1B8);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_283_fu_162_p0() {
    mul_ln728_283_fu_162_p0 =  (sc_lv<22>) (zext_ln1118_224_fu_3657_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_283_fu_162_p2() {
    mul_ln728_283_fu_162_p2 = (!mul_ln728_283_fu_162_p0.read().is_01() || !ap_const_lv36_2988.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_283_fu_162_p0.read()) * sc_biguint<36>(ap_const_lv36_2988);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_284_fu_186_p0() {
    mul_ln728_284_fu_186_p0 =  (sc_lv<22>) (zext_ln1118_222_fu_3641_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_284_fu_186_p2() {
    mul_ln728_284_fu_186_p2 = (!mul_ln728_284_fu_186_p0.read().is_01() || !ap_const_lv35_139C.is_01())? sc_lv<35>(): sc_biguint<22>(mul_ln728_284_fu_186_p0.read()) * sc_biguint<35>(ap_const_lv35_139C);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_285_fu_174_p0() {
    mul_ln728_285_fu_174_p0 =  (sc_lv<22>) (zext_ln1118_224_fu_3657_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_285_fu_174_p2() {
    mul_ln728_285_fu_174_p2 = (!mul_ln728_285_fu_174_p0.read().is_01() || !ap_const_lv36_31FB.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_285_fu_174_p0.read()) * sc_biguint<36>(ap_const_lv36_31FB);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_286_fu_176_p0() {
    mul_ln728_286_fu_176_p0 =  (sc_lv<22>) (zext_ln1118_224_fu_3657_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_286_fu_176_p2() {
    mul_ln728_286_fu_176_p2 = (!mul_ln728_286_fu_176_p0.read().is_01() || !ap_const_lv36_2B24.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_286_fu_176_p0.read()) * sc_biguint<36>(ap_const_lv36_2B24);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_287_fu_168_p0() {
    mul_ln728_287_fu_168_p0 =  (sc_lv<22>) (zext_ln1118_228_fu_3900_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_287_fu_168_p2() {
    mul_ln728_287_fu_168_p2 = (!mul_ln728_287_fu_168_p0.read().is_01() || !ap_const_lv36_29A3.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_287_fu_168_p0.read()) * sc_biguint<36>(ap_const_lv36_29A3);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_288_fu_188_p0() {
    mul_ln728_288_fu_188_p0 =  (sc_lv<22>) (mul_ln728_288_fu_188_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_288_fu_188_p00() {
    mul_ln728_288_fu_188_p00 = esl_zext<33,22>(data_2_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_288_fu_188_p2() {
    mul_ln728_288_fu_188_p2 = (!mul_ln728_288_fu_188_p0.read().is_01() || !ap_const_lv33_6D0.is_01())? sc_lv<33>(): sc_biguint<22>(mul_ln728_288_fu_188_p0.read()) * sc_biguint<33>(ap_const_lv33_6D0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_289_fu_190_p0() {
    mul_ln728_289_fu_190_p0 =  (sc_lv<22>) (zext_ln1118_228_fu_3900_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_289_fu_190_p2() {
    mul_ln728_289_fu_190_p2 = (!mul_ln728_289_fu_190_p0.read().is_01() || !ap_const_lv36_395A.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_289_fu_190_p0.read()) * sc_biguint<36>(ap_const_lv36_395A);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_290_fu_185_p0() {
    mul_ln728_290_fu_185_p0 =  (sc_lv<22>) (zext_ln1118_232_fu_3679_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_290_fu_185_p2() {
    mul_ln728_290_fu_185_p2 = (!mul_ln728_290_fu_185_p0.read().is_01() || !ap_const_lv36_2D7C.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_290_fu_185_p0.read()) * sc_biguint<36>(ap_const_lv36_2D7C);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_291_fu_192_p0() {
    mul_ln728_291_fu_192_p0 =  (sc_lv<22>) (zext_ln1118_232_fu_3679_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_291_fu_192_p2() {
    mul_ln728_291_fu_192_p2 = (!mul_ln728_291_fu_192_p0.read().is_01() || !ap_const_lv36_2856.is_01())? sc_lv<36>(): sc_biguint<22>(mul_ln728_291_fu_192_p0.read()) * sc_biguint<36>(ap_const_lv36_2856);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_292_fu_181_p0() {
    mul_ln728_292_fu_181_p0 =  (sc_lv<22>) (mul_ln728_292_fu_181_p00.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_292_fu_181_p00() {
    mul_ln728_292_fu_181_p00 = esl_zext<35,22>(data_3_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_292_fu_181_p2() {
    mul_ln728_292_fu_181_p2 = (!mul_ln728_292_fu_181_p0.read().is_01() || !ap_const_lv35_1284.is_01())? sc_lv<35>(): sc_biguint<22>(mul_ln728_292_fu_181_p0.read()) * sc_biguint<35>(ap_const_lv35_1284);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_fu_163_p0() {
    mul_ln728_fu_163_p0 =  (sc_lv<22>) (zext_ln1118_218_fu_3620_p1.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_mul_ln728_fu_163_p2() {
    mul_ln728_fu_163_p2 = (!mul_ln728_fu_163_p0.read().is_01() || !ap_const_lv34_F73.is_01())? sc_lv<34>(): sc_biguint<22>(mul_ln728_fu_163_p0.read()) * sc_biguint<34>(ap_const_lv34_F73);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_p_Val2_s_fu_4103_p2() {
    p_Val2_s_fu_4103_p2 = (!zext_ln703_16_fu_4087_p1.read().is_01() || !add_ln703_414_fu_4097_p2.read().is_01())? sc_lv<52>(): (sc_biguint<52>(zext_ln703_16_fu_4087_p1.read()) + sc_biguint<52>(add_ln703_414_fu_4097_p2.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln1118_fu_4045_p1() {
    sext_ln1118_fu_4045_p1 = esl_sext<48,47>(shl_ln728_306_fu_4037_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln703_19_fu_4143_p1() {
    sext_ln703_19_fu_4143_p1 = esl_sext<52,51>(add_ln703_420_fu_4137_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln703_20_fu_4205_p1() {
    sext_ln703_20_fu_4205_p1 = esl_sext<49,48>(add_ln703_429_fu_4199_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln703_21_fu_4215_p1() {
    sext_ln703_21_fu_4215_p1 = esl_sext<52,49>(add_ln703_430_fu_4209_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln703_22_fu_4231_p1() {
    sext_ln703_22_fu_4231_p1 = esl_sext<52,50>(add_ln703_432_fu_4225_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln703_23_fu_4287_p1() {
    sext_ln703_23_fu_4287_p1 = esl_sext<52,51>(add_ln703_440_fu_4281_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln703_fu_4121_p1() {
    sext_ln703_fu_4121_p1 = esl_sext<52,51>(add_ln703_417_fu_4115_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_133_fu_3724_p1() {
    sext_ln728_133_fu_3724_p1 = esl_sext<51,49>(shl_ln728_281_fu_3716_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_134_fu_3864_p1() {
    sext_ln728_134_fu_3864_p1 = esl_sext<52,47>(tmp_5_fu_3856_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_135_fu_3917_p1() {
    sext_ln728_135_fu_3917_p1 = esl_sext<52,51>(shl_ln728_294_fu_3909_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_136_fu_3929_p1() {
    sext_ln728_136_fu_3929_p1 = esl_sext<52,51>(shl_ln728_295_fu_3921_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_137_fu_3973_p1() {
    sext_ln728_137_fu_3973_p1 = esl_sext<52,51>(shl_ln728_299_fu_3965_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_138_fu_3985_p1() {
    sext_ln728_138_fu_3985_p1 = esl_sext<52,51>(shl_ln728_300_fu_3977_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_139_fu_4057_p1() {
    sext_ln728_139_fu_4057_p1 = esl_sext<52,50>(shl_ln728_307_fu_4049_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sext_ln728_fu_3712_p1() {
    sext_ln728_fu_3712_p1 = esl_sext<52,51>(shl_ln728_s_fu_3704_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln1118_s_fu_3839_p3() {
    shl_ln1118_s_fu_3839_p3 = esl_concat<22,3>(data_1_V_read_19_reg_4437.read(), ap_const_lv3_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln6_fu_3828_p3() {
    shl_ln6_fu_3828_p3 = esl_concat<22,9>(data_1_V_read_19_reg_4437.read(), ap_const_lv9_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_281_fu_3716_p3() {
    shl_ln728_281_fu_3716_p3 = esl_concat<34,15>(mul_ln1118_160_reg_3106.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_282_fu_3728_p3() {
    shl_ln728_282_fu_3728_p3 = esl_concat<32,15>(mul_ln728_278_reg_3110.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_283_fu_3740_p3() {
    shl_ln728_283_fu_3740_p3 = esl_concat<35,15>(mul_ln728_279_fu_179_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_284_fu_3752_p3() {
    shl_ln728_284_fu_3752_p3 = esl_concat<33,15>(mul_ln728_280_reg_3114.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_285_fu_3764_p3() {
    shl_ln728_285_fu_3764_p3 = esl_concat<37,15>(mul_ln1118_161_reg_3118.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_286_fu_3772_p3() {
    shl_ln728_286_fu_3772_p3 = esl_concat<35,15>(mul_ln728_281_reg_3122.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_287_fu_3784_p3() {
    shl_ln728_287_fu_3784_p3 = esl_concat<31,15>(mul_ln728_282_reg_3126.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_288_fu_3796_p3() {
    shl_ln728_288_fu_3796_p3 = esl_concat<36,15>(mul_ln728_283_reg_3130.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_289_fu_3808_p3() {
    shl_ln728_289_fu_3808_p3 = esl_concat<35,15>(mul_ln728_284_reg_3134.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_290_fu_3820_p3() {
    shl_ln728_290_fu_3820_p3 = esl_concat<36,15>(mul_ln728_285_reg_3138.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_291_fu_3868_p3() {
    shl_ln728_291_fu_3868_p3 = esl_concat<35,15>(mul_ln1118_162_reg_3142.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_292_fu_3876_p3() {
    shl_ln728_292_fu_3876_p3 = esl_concat<36,15>(mul_ln728_286_reg_3146.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_293_fu_3888_p3() {
    shl_ln728_293_fu_3888_p3 = esl_concat<37,15>(mul_ln1118_163_reg_3150.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_294_fu_3909_p3() {
    shl_ln728_294_fu_3909_p3 = esl_concat<36,15>(mul_ln1118_164_fu_189_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_295_fu_3921_p3() {
    shl_ln728_295_fu_3921_p3 = esl_concat<36,15>(mul_ln1118_165_fu_170_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_296_fu_3933_p3() {
    shl_ln728_296_fu_3933_p3 = esl_concat<36,15>(mul_ln728_287_fu_168_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_297_fu_3945_p3() {
    shl_ln728_297_fu_3945_p3 = esl_concat<37,15>(mul_ln1118_166_fu_169_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_298_fu_3953_p3() {
    shl_ln728_298_fu_3953_p3 = esl_concat<33,15>(mul_ln728_288_reg_3154.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_299_fu_3965_p3() {
    shl_ln728_299_fu_3965_p3 = esl_concat<36,15>(mul_ln1118_167_fu_193_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_300_fu_3977_p3() {
    shl_ln728_300_fu_3977_p3 = esl_concat<36,15>(mul_ln1118_168_fu_180_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_301_fu_3989_p3() {
    shl_ln728_301_fu_3989_p3 = esl_concat<36,15>(mul_ln728_289_fu_190_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_302_fu_4001_p3() {
    shl_ln728_302_fu_4001_p3 = esl_concat<37,15>(mul_ln1118_169_reg_3158.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_303_fu_4009_p3() {
    shl_ln728_303_fu_4009_p3 = esl_concat<36,15>(mul_ln1118_170_reg_3162.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_304_fu_4017_p3() {
    shl_ln728_304_fu_4017_p3 = esl_concat<36,15>(mul_ln728_290_reg_3166.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_305_fu_4029_p3() {
    shl_ln728_305_fu_4029_p3 = esl_concat<37,15>(mul_ln1118_171_reg_3170.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_306_fu_4037_p3() {
    shl_ln728_306_fu_4037_p3 = esl_concat<32,15>(mul_ln1118_172_reg_3174.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_307_fu_4049_p3() {
    shl_ln728_307_fu_4049_p3 = esl_concat<35,15>(mul_ln1118_173_fu_164_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_308_fu_4061_p3() {
    shl_ln728_308_fu_4061_p3 = esl_concat<36,15>(mul_ln728_291_reg_3178.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_309_fu_4069_p3() {
    shl_ln728_309_fu_4069_p3 = esl_concat<35,15>(mul_ln728_292_reg_3182.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln728_s_fu_3704_p3() {
    shl_ln728_s_fu_3704_p3 = esl_concat<36,15>(mul_ln1118_reg_3102.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_shl_ln_fu_3692_p3() {
    shl_ln_fu_3692_p3 = esl_concat<34,15>(mul_ln728_reg_3098.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_sub_ln1118_fu_3850_p2() {
    sub_ln1118_fu_3850_p2 = (!zext_ln1118_225_fu_3835_p1.read().is_01() || !zext_ln1118_226_fu_3846_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln1118_225_fu_3835_p1.read()) - sc_biguint<32>(zext_ln1118_226_fu_3846_p1.read()));
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_tmp_5_fu_3856_p3() {
    tmp_5_fu_3856_p3 = esl_concat<32,15>(sub_ln1118_fu_3850_p2.read(), ap_const_lv15_0);
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_218_fu_3620_p1() {
    zext_ln1118_218_fu_3620_p1 = esl_zext<34,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_220_fu_3631_p1() {
    zext_ln1118_220_fu_3631_p1 = esl_zext<35,22>(data_0_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_222_fu_3641_p1() {
    zext_ln1118_222_fu_3641_p1 = esl_zext<35,22>(data_1_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_224_fu_3657_p1() {
    zext_ln1118_224_fu_3657_p1 = esl_zext<36,22>(data_1_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_225_fu_3835_p1() {
    zext_ln1118_225_fu_3835_p1 = esl_zext<32,31>(shl_ln6_fu_3828_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_226_fu_3846_p1() {
    zext_ln1118_226_fu_3846_p1 = esl_zext<32,25>(shl_ln1118_s_fu_3839_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_228_fu_3900_p1() {
    zext_ln1118_228_fu_3900_p1 = esl_zext<36,22>(data_2_V_read_19_reg_4431.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_229_fu_3961_p1() {
    zext_ln1118_229_fu_3961_p1 = esl_zext<49,48>(shl_ln728_298_fu_3953_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_230_fu_3669_p1() {
    zext_ln1118_230_fu_3669_p1 = esl_zext<35,22>(data_3_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_232_fu_3679_p1() {
    zext_ln1118_232_fu_3679_p1 = esl_zext<36,22>(data_3_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln1118_233_fu_3686_p1() {
    zext_ln1118_233_fu_3686_p1 = esl_zext<37,22>(data_3_V_read.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln703_16_fu_4087_p1() {
    zext_ln703_16_fu_4087_p1 = esl_zext<52,50>(add_ln703_fu_4081_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln703_17_fu_4171_p1() {
    zext_ln703_17_fu_4171_p1 = esl_zext<52,51>(add_ln703_424_fu_4165_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln703_18_fu_4259_p1() {
    zext_ln703_18_fu_4259_p1 = esl_zext<52,51>(add_ln703_436_fu_4253_p2.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln703_fu_4077_p1() {
    zext_ln703_fu_4077_p1 = esl_zext<51,50>(shl_ln728_309_fu_4069_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_252_fu_3700_p1() {
    zext_ln728_252_fu_3700_p1 = esl_zext<50,49>(shl_ln_fu_3692_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_253_fu_3736_p1() {
    zext_ln728_253_fu_3736_p1 = esl_zext<51,47>(shl_ln728_282_fu_3728_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_254_fu_3748_p1() {
    zext_ln728_254_fu_3748_p1 = esl_zext<52,50>(shl_ln728_283_fu_3740_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_255_fu_3760_p1() {
    zext_ln728_255_fu_3760_p1 = esl_zext<50,48>(shl_ln728_284_fu_3752_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_256_fu_3780_p1() {
    zext_ln728_256_fu_3780_p1 = esl_zext<52,50>(shl_ln728_286_fu_3772_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_258_fu_3792_p1() {
    zext_ln728_258_fu_3792_p1 = esl_zext<50,46>(shl_ln728_287_fu_3784_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_259_fu_3804_p1() {
    zext_ln728_259_fu_3804_p1 = esl_zext<52,51>(shl_ln728_288_fu_3796_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_260_fu_3816_p1() {
    zext_ln728_260_fu_3816_p1 = esl_zext<51,50>(shl_ln728_289_fu_3808_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_261_fu_3884_p1() {
    zext_ln728_261_fu_3884_p1 = esl_zext<52,51>(shl_ln728_292_fu_3876_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_263_fu_3941_p1() {
    zext_ln728_263_fu_3941_p1 = esl_zext<52,51>(shl_ln728_296_fu_3933_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_264_fu_3997_p1() {
    zext_ln728_264_fu_3997_p1 = esl_zext<52,51>(shl_ln728_301_fu_3989_p3.read());
}

void dense_latency_0_0_0_0_0_0_0_0_0::thread_zext_ln728_265_fu_4025_p1() {
    zext_ln728_265_fu_4025_p1 = esl_zext<52,51>(shl_ln728_304_fu_4017_p3.read());
}

}

