// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::ap_const_logic_1 = sc_dt::Log_1;
const bool linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::ap_const_boolean_1 = true;
const sc_lv<24> linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::ap_const_lv24_0 = "000000000000000000000000";
const sc_logic linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::ap_const_logic_0 = sc_dt::Log_0;

linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( sext_ln728_fu_128_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( sext_ln728_20_fu_140_p1 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( sext_ln728_29_fu_248_p1 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( sext_ln728_30_fu_260_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( sext_ln728_21_fu_152_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( sext_ln728_22_fu_164_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( sext_ln728_23_fu_176_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( sext_ln728_24_fu_188_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( sext_ln728_25_fu_200_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( sext_ln728_26_fu_212_p1 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( sext_ln728_27_fu_224_p1 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( sext_ln728_28_fu_236_p1 );

    SC_METHOD(thread_res_0_V_write_assign_fu_120_p3);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_res_10_V_write_assign_fu_240_p3);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_res_11_V_write_assign_fu_252_p3);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_res_1_V_write_assign_fu_132_p3);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_res_2_V_write_assign_fu_144_p3);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_res_3_V_write_assign_fu_156_p3);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_res_4_V_write_assign_fu_168_p3);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_res_5_V_write_assign_fu_180_p3);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_res_6_V_write_assign_fu_192_p3);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_res_7_V_write_assign_fu_204_p3);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_res_8_V_write_assign_fu_216_p3);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_res_9_V_write_assign_fu_228_p3);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_sext_ln728_20_fu_140_p1);
    sensitive << ( res_1_V_write_assign_fu_132_p3 );

    SC_METHOD(thread_sext_ln728_21_fu_152_p1);
    sensitive << ( res_2_V_write_assign_fu_144_p3 );

    SC_METHOD(thread_sext_ln728_22_fu_164_p1);
    sensitive << ( res_3_V_write_assign_fu_156_p3 );

    SC_METHOD(thread_sext_ln728_23_fu_176_p1);
    sensitive << ( res_4_V_write_assign_fu_168_p3 );

    SC_METHOD(thread_sext_ln728_24_fu_188_p1);
    sensitive << ( res_5_V_write_assign_fu_180_p3 );

    SC_METHOD(thread_sext_ln728_25_fu_200_p1);
    sensitive << ( res_6_V_write_assign_fu_192_p3 );

    SC_METHOD(thread_sext_ln728_26_fu_212_p1);
    sensitive << ( res_7_V_write_assign_fu_204_p3 );

    SC_METHOD(thread_sext_ln728_27_fu_224_p1);
    sensitive << ( res_8_V_write_assign_fu_216_p3 );

    SC_METHOD(thread_sext_ln728_28_fu_236_p1);
    sensitive << ( res_9_V_write_assign_fu_228_p3 );

    SC_METHOD(thread_sext_ln728_29_fu_248_p1);
    sensitive << ( res_10_V_write_assign_fu_240_p3 );

    SC_METHOD(thread_sext_ln728_30_fu_260_p1);
    sensitive << ( res_11_V_write_assign_fu_252_p3 );

    SC_METHOD(thread_sext_ln728_fu_128_p1);
    sensitive << ( res_0_V_write_assign_fu_120_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, res_0_V_write_assign_fu_120_p3, "res_0_V_write_assign_fu_120_p3");
    sc_trace(mVcdFile, res_1_V_write_assign_fu_132_p3, "res_1_V_write_assign_fu_132_p3");
    sc_trace(mVcdFile, res_2_V_write_assign_fu_144_p3, "res_2_V_write_assign_fu_144_p3");
    sc_trace(mVcdFile, res_3_V_write_assign_fu_156_p3, "res_3_V_write_assign_fu_156_p3");
    sc_trace(mVcdFile, res_4_V_write_assign_fu_168_p3, "res_4_V_write_assign_fu_168_p3");
    sc_trace(mVcdFile, res_5_V_write_assign_fu_180_p3, "res_5_V_write_assign_fu_180_p3");
    sc_trace(mVcdFile, res_6_V_write_assign_fu_192_p3, "res_6_V_write_assign_fu_192_p3");
    sc_trace(mVcdFile, res_7_V_write_assign_fu_204_p3, "res_7_V_write_assign_fu_204_p3");
    sc_trace(mVcdFile, res_8_V_write_assign_fu_216_p3, "res_8_V_write_assign_fu_216_p3");
    sc_trace(mVcdFile, res_9_V_write_assign_fu_228_p3, "res_9_V_write_assign_fu_228_p3");
    sc_trace(mVcdFile, res_10_V_write_assign_fu_240_p3, "res_10_V_write_assign_fu_240_p3");
    sc_trace(mVcdFile, res_11_V_write_assign_fu_252_p3, "res_11_V_write_assign_fu_252_p3");
    sc_trace(mVcdFile, sext_ln728_fu_128_p1, "sext_ln728_fu_128_p1");
    sc_trace(mVcdFile, sext_ln728_20_fu_140_p1, "sext_ln728_20_fu_140_p1");
    sc_trace(mVcdFile, sext_ln728_21_fu_152_p1, "sext_ln728_21_fu_152_p1");
    sc_trace(mVcdFile, sext_ln728_22_fu_164_p1, "sext_ln728_22_fu_164_p1");
    sc_trace(mVcdFile, sext_ln728_23_fu_176_p1, "sext_ln728_23_fu_176_p1");
    sc_trace(mVcdFile, sext_ln728_24_fu_188_p1, "sext_ln728_24_fu_188_p1");
    sc_trace(mVcdFile, sext_ln728_25_fu_200_p1, "sext_ln728_25_fu_200_p1");
    sc_trace(mVcdFile, sext_ln728_26_fu_212_p1, "sext_ln728_26_fu_212_p1");
    sc_trace(mVcdFile, sext_ln728_27_fu_224_p1, "sext_ln728_27_fu_224_p1");
    sc_trace(mVcdFile, sext_ln728_28_fu_236_p1, "sext_ln728_28_fu_236_p1");
    sc_trace(mVcdFile, sext_ln728_29_fu_248_p1, "sext_ln728_29_fu_248_p1");
    sc_trace(mVcdFile, sext_ln728_30_fu_260_p1, "sext_ln728_30_fu_260_p1");
#endif

    }
}

linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::~linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_0() {
    ap_return_0 = sext_ln728_fu_128_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_1() {
    ap_return_1 = sext_ln728_20_fu_140_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_10() {
    ap_return_10 = sext_ln728_29_fu_248_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_11() {
    ap_return_11 = sext_ln728_30_fu_260_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_2() {
    ap_return_2 = sext_ln728_21_fu_152_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_3() {
    ap_return_3 = sext_ln728_22_fu_164_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_4() {
    ap_return_4 = sext_ln728_23_fu_176_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_5() {
    ap_return_5 = sext_ln728_24_fu_188_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_6() {
    ap_return_6 = sext_ln728_25_fu_200_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_7() {
    ap_return_7 = sext_ln728_26_fu_212_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_8() {
    ap_return_8 = sext_ln728_27_fu_224_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_ap_return_9() {
    ap_return_9 = sext_ln728_28_fu_236_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_0_V_write_assign_fu_120_p3() {
    res_0_V_write_assign_fu_120_p3 = esl_concat<28,24>(data_0_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_10_V_write_assign_fu_240_p3() {
    res_10_V_write_assign_fu_240_p3 = esl_concat<28,24>(data_10_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_11_V_write_assign_fu_252_p3() {
    res_11_V_write_assign_fu_252_p3 = esl_concat<28,24>(data_11_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_1_V_write_assign_fu_132_p3() {
    res_1_V_write_assign_fu_132_p3 = esl_concat<28,24>(data_1_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_2_V_write_assign_fu_144_p3() {
    res_2_V_write_assign_fu_144_p3 = esl_concat<28,24>(data_2_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_3_V_write_assign_fu_156_p3() {
    res_3_V_write_assign_fu_156_p3 = esl_concat<28,24>(data_3_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_4_V_write_assign_fu_168_p3() {
    res_4_V_write_assign_fu_168_p3 = esl_concat<28,24>(data_4_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_5_V_write_assign_fu_180_p3() {
    res_5_V_write_assign_fu_180_p3 = esl_concat<28,24>(data_5_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_6_V_write_assign_fu_192_p3() {
    res_6_V_write_assign_fu_192_p3 = esl_concat<28,24>(data_6_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_7_V_write_assign_fu_204_p3() {
    res_7_V_write_assign_fu_204_p3 = esl_concat<28,24>(data_7_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_8_V_write_assign_fu_216_p3() {
    res_8_V_write_assign_fu_216_p3 = esl_concat<28,24>(data_8_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_res_9_V_write_assign_fu_228_p3() {
    res_9_V_write_assign_fu_228_p3 = esl_concat<28,24>(data_9_V_read.read(), ap_const_lv24_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_20_fu_140_p1() {
    sext_ln728_20_fu_140_p1 = esl_sext<64,52>(res_1_V_write_assign_fu_132_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_21_fu_152_p1() {
    sext_ln728_21_fu_152_p1 = esl_sext<64,52>(res_2_V_write_assign_fu_144_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_22_fu_164_p1() {
    sext_ln728_22_fu_164_p1 = esl_sext<64,52>(res_3_V_write_assign_fu_156_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_23_fu_176_p1() {
    sext_ln728_23_fu_176_p1 = esl_sext<64,52>(res_4_V_write_assign_fu_168_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_24_fu_188_p1() {
    sext_ln728_24_fu_188_p1 = esl_sext<64,52>(res_5_V_write_assign_fu_180_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_25_fu_200_p1() {
    sext_ln728_25_fu_200_p1 = esl_sext<64,52>(res_6_V_write_assign_fu_192_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_26_fu_212_p1() {
    sext_ln728_26_fu_212_p1 = esl_sext<64,52>(res_7_V_write_assign_fu_204_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_27_fu_224_p1() {
    sext_ln728_27_fu_224_p1 = esl_sext<64,52>(res_8_V_write_assign_fu_216_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_28_fu_236_p1() {
    sext_ln728_28_fu_236_p1 = esl_sext<64,52>(res_9_V_write_assign_fu_228_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_29_fu_248_p1() {
    sext_ln728_29_fu_248_p1 = esl_sext<64,52>(res_10_V_write_assign_fu_240_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_30_fu_260_p1() {
    sext_ln728_30_fu_260_p1 = esl_sext<64,52>(res_11_V_write_assign_fu_252_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config18_s::thread_sext_ln728_fu_128_p1() {
    sext_ln728_fu_128_p1 = esl_sext<64,52>(res_0_V_write_assign_fu_120_p3.read());
}

}

