// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s_HH_
#define _linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s : public sc_module {
    // Port declarations 41
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > data_0_V_read;
    sc_in< sc_lv<32> > data_1_V_read;
    sc_in< sc_lv<32> > data_2_V_read;
    sc_in< sc_lv<32> > data_3_V_read;
    sc_in< sc_lv<32> > data_4_V_read;
    sc_in< sc_lv<32> > data_5_V_read;
    sc_in< sc_lv<32> > data_6_V_read;
    sc_in< sc_lv<32> > data_7_V_read;
    sc_in< sc_lv<32> > data_8_V_read;
    sc_in< sc_lv<32> > data_9_V_read;
    sc_in< sc_lv<32> > data_10_V_read;
    sc_in< sc_lv<32> > data_11_V_read;
    sc_in< sc_lv<32> > data_12_V_read;
    sc_in< sc_lv<32> > data_13_V_read;
    sc_in< sc_lv<32> > data_14_V_read;
    sc_in< sc_lv<32> > data_15_V_read;
    sc_in< sc_lv<32> > data_16_V_read;
    sc_in< sc_lv<32> > data_17_V_read;
    sc_in< sc_lv<32> > data_18_V_read;
    sc_in< sc_lv<32> > data_19_V_read;
    sc_out< sc_lv<64> > ap_return_0;
    sc_out< sc_lv<64> > ap_return_1;
    sc_out< sc_lv<64> > ap_return_2;
    sc_out< sc_lv<64> > ap_return_3;
    sc_out< sc_lv<64> > ap_return_4;
    sc_out< sc_lv<64> > ap_return_5;
    sc_out< sc_lv<64> > ap_return_6;
    sc_out< sc_lv<64> > ap_return_7;
    sc_out< sc_lv<64> > ap_return_8;
    sc_out< sc_lv<64> > ap_return_9;
    sc_out< sc_lv<64> > ap_return_10;
    sc_out< sc_lv<64> > ap_return_11;
    sc_out< sc_lv<64> > ap_return_12;
    sc_out< sc_lv<64> > ap_return_13;
    sc_out< sc_lv<64> > ap_return_14;
    sc_out< sc_lv<64> > ap_return_15;
    sc_out< sc_lv<64> > ap_return_16;
    sc_out< sc_lv<64> > ap_return_17;
    sc_out< sc_lv<64> > ap_return_18;
    sc_out< sc_lv<64> > ap_return_19;


    // Module declarations
    linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s(sc_module_name name);
    SC_HAS_PROCESS(linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s);

    ~linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<50> > res_0_V_write_assign_fu_184_p3;
    sc_signal< sc_lv<50> > res_1_V_write_assign_fu_196_p3;
    sc_signal< sc_lv<50> > res_2_V_write_assign_fu_208_p3;
    sc_signal< sc_lv<50> > res_3_V_write_assign_fu_220_p3;
    sc_signal< sc_lv<50> > res_4_V_write_assign_fu_232_p3;
    sc_signal< sc_lv<50> > res_5_V_write_assign_fu_244_p3;
    sc_signal< sc_lv<50> > res_6_V_write_assign_fu_256_p3;
    sc_signal< sc_lv<50> > res_7_V_write_assign_fu_268_p3;
    sc_signal< sc_lv<50> > res_8_V_write_assign_fu_280_p3;
    sc_signal< sc_lv<50> > res_9_V_write_assign_fu_292_p3;
    sc_signal< sc_lv<50> > res_10_V_write_assign_fu_304_p3;
    sc_signal< sc_lv<50> > res_11_V_write_assign_fu_316_p3;
    sc_signal< sc_lv<50> > res_12_V_write_assign_fu_328_p3;
    sc_signal< sc_lv<50> > res_13_V_write_assign_fu_340_p3;
    sc_signal< sc_lv<50> > res_14_V_write_assign_fu_352_p3;
    sc_signal< sc_lv<50> > res_15_V_write_assign_fu_364_p3;
    sc_signal< sc_lv<50> > res_16_V_write_assign_fu_376_p3;
    sc_signal< sc_lv<50> > res_17_V_write_assign_fu_388_p3;
    sc_signal< sc_lv<50> > res_18_V_write_assign_fu_400_p3;
    sc_signal< sc_lv<50> > res_19_V_write_assign_fu_412_p3;
    sc_signal< sc_lv<64> > sext_ln728_fu_192_p1;
    sc_signal< sc_lv<64> > sext_ln728_1_fu_204_p1;
    sc_signal< sc_lv<64> > sext_ln728_2_fu_216_p1;
    sc_signal< sc_lv<64> > sext_ln728_3_fu_228_p1;
    sc_signal< sc_lv<64> > sext_ln728_4_fu_240_p1;
    sc_signal< sc_lv<64> > sext_ln728_5_fu_252_p1;
    sc_signal< sc_lv<64> > sext_ln728_6_fu_264_p1;
    sc_signal< sc_lv<64> > sext_ln728_7_fu_276_p1;
    sc_signal< sc_lv<64> > sext_ln728_8_fu_288_p1;
    sc_signal< sc_lv<64> > sext_ln728_9_fu_300_p1;
    sc_signal< sc_lv<64> > sext_ln728_10_fu_312_p1;
    sc_signal< sc_lv<64> > sext_ln728_11_fu_324_p1;
    sc_signal< sc_lv<64> > sext_ln728_12_fu_336_p1;
    sc_signal< sc_lv<64> > sext_ln728_13_fu_348_p1;
    sc_signal< sc_lv<64> > sext_ln728_14_fu_360_p1;
    sc_signal< sc_lv<64> > sext_ln728_15_fu_372_p1;
    sc_signal< sc_lv<64> > sext_ln728_16_fu_384_p1;
    sc_signal< sc_lv<64> > sext_ln728_17_fu_396_p1;
    sc_signal< sc_lv<64> > sext_ln728_18_fu_408_p1;
    sc_signal< sc_lv<64> > sext_ln728_19_fu_420_p1;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<18> ap_const_lv18_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_10();
    void thread_ap_return_11();
    void thread_ap_return_12();
    void thread_ap_return_13();
    void thread_ap_return_14();
    void thread_ap_return_15();
    void thread_ap_return_16();
    void thread_ap_return_17();
    void thread_ap_return_18();
    void thread_ap_return_19();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_res_0_V_write_assign_fu_184_p3();
    void thread_res_10_V_write_assign_fu_304_p3();
    void thread_res_11_V_write_assign_fu_316_p3();
    void thread_res_12_V_write_assign_fu_328_p3();
    void thread_res_13_V_write_assign_fu_340_p3();
    void thread_res_14_V_write_assign_fu_352_p3();
    void thread_res_15_V_write_assign_fu_364_p3();
    void thread_res_16_V_write_assign_fu_376_p3();
    void thread_res_17_V_write_assign_fu_388_p3();
    void thread_res_18_V_write_assign_fu_400_p3();
    void thread_res_19_V_write_assign_fu_412_p3();
    void thread_res_1_V_write_assign_fu_196_p3();
    void thread_res_2_V_write_assign_fu_208_p3();
    void thread_res_3_V_write_assign_fu_220_p3();
    void thread_res_4_V_write_assign_fu_232_p3();
    void thread_res_5_V_write_assign_fu_244_p3();
    void thread_res_6_V_write_assign_fu_256_p3();
    void thread_res_7_V_write_assign_fu_268_p3();
    void thread_res_8_V_write_assign_fu_280_p3();
    void thread_res_9_V_write_assign_fu_292_p3();
    void thread_sext_ln728_10_fu_312_p1();
    void thread_sext_ln728_11_fu_324_p1();
    void thread_sext_ln728_12_fu_336_p1();
    void thread_sext_ln728_13_fu_348_p1();
    void thread_sext_ln728_14_fu_360_p1();
    void thread_sext_ln728_15_fu_372_p1();
    void thread_sext_ln728_16_fu_384_p1();
    void thread_sext_ln728_17_fu_396_p1();
    void thread_sext_ln728_18_fu_408_p1();
    void thread_sext_ln728_19_fu_420_p1();
    void thread_sext_ln728_1_fu_204_p1();
    void thread_sext_ln728_2_fu_216_p1();
    void thread_sext_ln728_3_fu_228_p1();
    void thread_sext_ln728_4_fu_240_p1();
    void thread_sext_ln728_5_fu_252_p1();
    void thread_sext_ln728_6_fu_264_p1();
    void thread_sext_ln728_7_fu_276_p1();
    void thread_sext_ln728_8_fu_288_p1();
    void thread_sext_ln728_9_fu_300_p1();
    void thread_sext_ln728_fu_192_p1();
};

}

using namespace ap_rtl;

#endif
