// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::ap_const_logic_1 = sc_dt::Log_1;
const bool linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::ap_const_boolean_1 = true;
const sc_lv<18> linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::ap_const_lv18_0 = "000000000000000000";
const sc_logic linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::ap_const_logic_0 = sc_dt::Log_0;

linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( sext_ln728_fu_192_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( sext_ln728_1_fu_204_p1 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( sext_ln728_10_fu_312_p1 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( sext_ln728_11_fu_324_p1 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( sext_ln728_12_fu_336_p1 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( sext_ln728_13_fu_348_p1 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( sext_ln728_14_fu_360_p1 );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( sext_ln728_15_fu_372_p1 );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( sext_ln728_16_fu_384_p1 );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( sext_ln728_17_fu_396_p1 );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( sext_ln728_18_fu_408_p1 );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( sext_ln728_19_fu_420_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( sext_ln728_2_fu_216_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( sext_ln728_3_fu_228_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( sext_ln728_4_fu_240_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( sext_ln728_5_fu_252_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( sext_ln728_6_fu_264_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( sext_ln728_7_fu_276_p1 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( sext_ln728_8_fu_288_p1 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( sext_ln728_9_fu_300_p1 );

    SC_METHOD(thread_res_0_V_write_assign_fu_184_p3);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_res_10_V_write_assign_fu_304_p3);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_res_11_V_write_assign_fu_316_p3);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_res_12_V_write_assign_fu_328_p3);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_res_13_V_write_assign_fu_340_p3);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_res_14_V_write_assign_fu_352_p3);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_res_15_V_write_assign_fu_364_p3);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_res_16_V_write_assign_fu_376_p3);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_res_17_V_write_assign_fu_388_p3);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_res_18_V_write_assign_fu_400_p3);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_res_19_V_write_assign_fu_412_p3);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_res_1_V_write_assign_fu_196_p3);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_res_2_V_write_assign_fu_208_p3);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_res_3_V_write_assign_fu_220_p3);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_res_4_V_write_assign_fu_232_p3);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_res_5_V_write_assign_fu_244_p3);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_res_6_V_write_assign_fu_256_p3);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_res_7_V_write_assign_fu_268_p3);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_res_8_V_write_assign_fu_280_p3);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_res_9_V_write_assign_fu_292_p3);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_sext_ln728_10_fu_312_p1);
    sensitive << ( res_10_V_write_assign_fu_304_p3 );

    SC_METHOD(thread_sext_ln728_11_fu_324_p1);
    sensitive << ( res_11_V_write_assign_fu_316_p3 );

    SC_METHOD(thread_sext_ln728_12_fu_336_p1);
    sensitive << ( res_12_V_write_assign_fu_328_p3 );

    SC_METHOD(thread_sext_ln728_13_fu_348_p1);
    sensitive << ( res_13_V_write_assign_fu_340_p3 );

    SC_METHOD(thread_sext_ln728_14_fu_360_p1);
    sensitive << ( res_14_V_write_assign_fu_352_p3 );

    SC_METHOD(thread_sext_ln728_15_fu_372_p1);
    sensitive << ( res_15_V_write_assign_fu_364_p3 );

    SC_METHOD(thread_sext_ln728_16_fu_384_p1);
    sensitive << ( res_16_V_write_assign_fu_376_p3 );

    SC_METHOD(thread_sext_ln728_17_fu_396_p1);
    sensitive << ( res_17_V_write_assign_fu_388_p3 );

    SC_METHOD(thread_sext_ln728_18_fu_408_p1);
    sensitive << ( res_18_V_write_assign_fu_400_p3 );

    SC_METHOD(thread_sext_ln728_19_fu_420_p1);
    sensitive << ( res_19_V_write_assign_fu_412_p3 );

    SC_METHOD(thread_sext_ln728_1_fu_204_p1);
    sensitive << ( res_1_V_write_assign_fu_196_p3 );

    SC_METHOD(thread_sext_ln728_2_fu_216_p1);
    sensitive << ( res_2_V_write_assign_fu_208_p3 );

    SC_METHOD(thread_sext_ln728_3_fu_228_p1);
    sensitive << ( res_3_V_write_assign_fu_220_p3 );

    SC_METHOD(thread_sext_ln728_4_fu_240_p1);
    sensitive << ( res_4_V_write_assign_fu_232_p3 );

    SC_METHOD(thread_sext_ln728_5_fu_252_p1);
    sensitive << ( res_5_V_write_assign_fu_244_p3 );

    SC_METHOD(thread_sext_ln728_6_fu_264_p1);
    sensitive << ( res_6_V_write_assign_fu_256_p3 );

    SC_METHOD(thread_sext_ln728_7_fu_276_p1);
    sensitive << ( res_7_V_write_assign_fu_268_p3 );

    SC_METHOD(thread_sext_ln728_8_fu_288_p1);
    sensitive << ( res_8_V_write_assign_fu_280_p3 );

    SC_METHOD(thread_sext_ln728_9_fu_300_p1);
    sensitive << ( res_9_V_write_assign_fu_292_p3 );

    SC_METHOD(thread_sext_ln728_fu_192_p1);
    sensitive << ( res_0_V_write_assign_fu_184_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, res_0_V_write_assign_fu_184_p3, "res_0_V_write_assign_fu_184_p3");
    sc_trace(mVcdFile, res_1_V_write_assign_fu_196_p3, "res_1_V_write_assign_fu_196_p3");
    sc_trace(mVcdFile, res_2_V_write_assign_fu_208_p3, "res_2_V_write_assign_fu_208_p3");
    sc_trace(mVcdFile, res_3_V_write_assign_fu_220_p3, "res_3_V_write_assign_fu_220_p3");
    sc_trace(mVcdFile, res_4_V_write_assign_fu_232_p3, "res_4_V_write_assign_fu_232_p3");
    sc_trace(mVcdFile, res_5_V_write_assign_fu_244_p3, "res_5_V_write_assign_fu_244_p3");
    sc_trace(mVcdFile, res_6_V_write_assign_fu_256_p3, "res_6_V_write_assign_fu_256_p3");
    sc_trace(mVcdFile, res_7_V_write_assign_fu_268_p3, "res_7_V_write_assign_fu_268_p3");
    sc_trace(mVcdFile, res_8_V_write_assign_fu_280_p3, "res_8_V_write_assign_fu_280_p3");
    sc_trace(mVcdFile, res_9_V_write_assign_fu_292_p3, "res_9_V_write_assign_fu_292_p3");
    sc_trace(mVcdFile, res_10_V_write_assign_fu_304_p3, "res_10_V_write_assign_fu_304_p3");
    sc_trace(mVcdFile, res_11_V_write_assign_fu_316_p3, "res_11_V_write_assign_fu_316_p3");
    sc_trace(mVcdFile, res_12_V_write_assign_fu_328_p3, "res_12_V_write_assign_fu_328_p3");
    sc_trace(mVcdFile, res_13_V_write_assign_fu_340_p3, "res_13_V_write_assign_fu_340_p3");
    sc_trace(mVcdFile, res_14_V_write_assign_fu_352_p3, "res_14_V_write_assign_fu_352_p3");
    sc_trace(mVcdFile, res_15_V_write_assign_fu_364_p3, "res_15_V_write_assign_fu_364_p3");
    sc_trace(mVcdFile, res_16_V_write_assign_fu_376_p3, "res_16_V_write_assign_fu_376_p3");
    sc_trace(mVcdFile, res_17_V_write_assign_fu_388_p3, "res_17_V_write_assign_fu_388_p3");
    sc_trace(mVcdFile, res_18_V_write_assign_fu_400_p3, "res_18_V_write_assign_fu_400_p3");
    sc_trace(mVcdFile, res_19_V_write_assign_fu_412_p3, "res_19_V_write_assign_fu_412_p3");
    sc_trace(mVcdFile, sext_ln728_fu_192_p1, "sext_ln728_fu_192_p1");
    sc_trace(mVcdFile, sext_ln728_1_fu_204_p1, "sext_ln728_1_fu_204_p1");
    sc_trace(mVcdFile, sext_ln728_2_fu_216_p1, "sext_ln728_2_fu_216_p1");
    sc_trace(mVcdFile, sext_ln728_3_fu_228_p1, "sext_ln728_3_fu_228_p1");
    sc_trace(mVcdFile, sext_ln728_4_fu_240_p1, "sext_ln728_4_fu_240_p1");
    sc_trace(mVcdFile, sext_ln728_5_fu_252_p1, "sext_ln728_5_fu_252_p1");
    sc_trace(mVcdFile, sext_ln728_6_fu_264_p1, "sext_ln728_6_fu_264_p1");
    sc_trace(mVcdFile, sext_ln728_7_fu_276_p1, "sext_ln728_7_fu_276_p1");
    sc_trace(mVcdFile, sext_ln728_8_fu_288_p1, "sext_ln728_8_fu_288_p1");
    sc_trace(mVcdFile, sext_ln728_9_fu_300_p1, "sext_ln728_9_fu_300_p1");
    sc_trace(mVcdFile, sext_ln728_10_fu_312_p1, "sext_ln728_10_fu_312_p1");
    sc_trace(mVcdFile, sext_ln728_11_fu_324_p1, "sext_ln728_11_fu_324_p1");
    sc_trace(mVcdFile, sext_ln728_12_fu_336_p1, "sext_ln728_12_fu_336_p1");
    sc_trace(mVcdFile, sext_ln728_13_fu_348_p1, "sext_ln728_13_fu_348_p1");
    sc_trace(mVcdFile, sext_ln728_14_fu_360_p1, "sext_ln728_14_fu_360_p1");
    sc_trace(mVcdFile, sext_ln728_15_fu_372_p1, "sext_ln728_15_fu_372_p1");
    sc_trace(mVcdFile, sext_ln728_16_fu_384_p1, "sext_ln728_16_fu_384_p1");
    sc_trace(mVcdFile, sext_ln728_17_fu_396_p1, "sext_ln728_17_fu_396_p1");
    sc_trace(mVcdFile, sext_ln728_18_fu_408_p1, "sext_ln728_18_fu_408_p1");
    sc_trace(mVcdFile, sext_ln728_19_fu_420_p1, "sext_ln728_19_fu_420_p1");
#endif

    }
}

linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::~linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_0() {
    ap_return_0 = sext_ln728_fu_192_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_1() {
    ap_return_1 = sext_ln728_1_fu_204_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_10() {
    ap_return_10 = sext_ln728_10_fu_312_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_11() {
    ap_return_11 = sext_ln728_11_fu_324_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_12() {
    ap_return_12 = sext_ln728_12_fu_336_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_13() {
    ap_return_13 = sext_ln728_13_fu_348_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_14() {
    ap_return_14 = sext_ln728_14_fu_360_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_15() {
    ap_return_15 = sext_ln728_15_fu_372_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_16() {
    ap_return_16 = sext_ln728_16_fu_384_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_17() {
    ap_return_17 = sext_ln728_17_fu_396_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_18() {
    ap_return_18 = sext_ln728_18_fu_408_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_19() {
    ap_return_19 = sext_ln728_19_fu_420_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_2() {
    ap_return_2 = sext_ln728_2_fu_216_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_3() {
    ap_return_3 = sext_ln728_3_fu_228_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_4() {
    ap_return_4 = sext_ln728_4_fu_240_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_5() {
    ap_return_5 = sext_ln728_5_fu_252_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_6() {
    ap_return_6 = sext_ln728_6_fu_264_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_7() {
    ap_return_7 = sext_ln728_7_fu_276_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_8() {
    ap_return_8 = sext_ln728_8_fu_288_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_ap_return_9() {
    ap_return_9 = sext_ln728_9_fu_300_p1.read();
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_0_V_write_assign_fu_184_p3() {
    res_0_V_write_assign_fu_184_p3 = esl_concat<32,18>(data_0_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_10_V_write_assign_fu_304_p3() {
    res_10_V_write_assign_fu_304_p3 = esl_concat<32,18>(data_10_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_11_V_write_assign_fu_316_p3() {
    res_11_V_write_assign_fu_316_p3 = esl_concat<32,18>(data_11_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_12_V_write_assign_fu_328_p3() {
    res_12_V_write_assign_fu_328_p3 = esl_concat<32,18>(data_12_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_13_V_write_assign_fu_340_p3() {
    res_13_V_write_assign_fu_340_p3 = esl_concat<32,18>(data_13_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_14_V_write_assign_fu_352_p3() {
    res_14_V_write_assign_fu_352_p3 = esl_concat<32,18>(data_14_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_15_V_write_assign_fu_364_p3() {
    res_15_V_write_assign_fu_364_p3 = esl_concat<32,18>(data_15_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_16_V_write_assign_fu_376_p3() {
    res_16_V_write_assign_fu_376_p3 = esl_concat<32,18>(data_16_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_17_V_write_assign_fu_388_p3() {
    res_17_V_write_assign_fu_388_p3 = esl_concat<32,18>(data_17_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_18_V_write_assign_fu_400_p3() {
    res_18_V_write_assign_fu_400_p3 = esl_concat<32,18>(data_18_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_19_V_write_assign_fu_412_p3() {
    res_19_V_write_assign_fu_412_p3 = esl_concat<32,18>(data_19_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_1_V_write_assign_fu_196_p3() {
    res_1_V_write_assign_fu_196_p3 = esl_concat<32,18>(data_1_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_2_V_write_assign_fu_208_p3() {
    res_2_V_write_assign_fu_208_p3 = esl_concat<32,18>(data_2_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_3_V_write_assign_fu_220_p3() {
    res_3_V_write_assign_fu_220_p3 = esl_concat<32,18>(data_3_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_4_V_write_assign_fu_232_p3() {
    res_4_V_write_assign_fu_232_p3 = esl_concat<32,18>(data_4_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_5_V_write_assign_fu_244_p3() {
    res_5_V_write_assign_fu_244_p3 = esl_concat<32,18>(data_5_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_6_V_write_assign_fu_256_p3() {
    res_6_V_write_assign_fu_256_p3 = esl_concat<32,18>(data_6_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_7_V_write_assign_fu_268_p3() {
    res_7_V_write_assign_fu_268_p3 = esl_concat<32,18>(data_7_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_8_V_write_assign_fu_280_p3() {
    res_8_V_write_assign_fu_280_p3 = esl_concat<32,18>(data_8_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_res_9_V_write_assign_fu_292_p3() {
    res_9_V_write_assign_fu_292_p3 = esl_concat<32,18>(data_9_V_read.read(), ap_const_lv18_0);
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_10_fu_312_p1() {
    sext_ln728_10_fu_312_p1 = esl_sext<64,50>(res_10_V_write_assign_fu_304_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_11_fu_324_p1() {
    sext_ln728_11_fu_324_p1 = esl_sext<64,50>(res_11_V_write_assign_fu_316_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_12_fu_336_p1() {
    sext_ln728_12_fu_336_p1 = esl_sext<64,50>(res_12_V_write_assign_fu_328_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_13_fu_348_p1() {
    sext_ln728_13_fu_348_p1 = esl_sext<64,50>(res_13_V_write_assign_fu_340_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_14_fu_360_p1() {
    sext_ln728_14_fu_360_p1 = esl_sext<64,50>(res_14_V_write_assign_fu_352_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_15_fu_372_p1() {
    sext_ln728_15_fu_372_p1 = esl_sext<64,50>(res_15_V_write_assign_fu_364_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_16_fu_384_p1() {
    sext_ln728_16_fu_384_p1 = esl_sext<64,50>(res_16_V_write_assign_fu_376_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_17_fu_396_p1() {
    sext_ln728_17_fu_396_p1 = esl_sext<64,50>(res_17_V_write_assign_fu_388_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_18_fu_408_p1() {
    sext_ln728_18_fu_408_p1 = esl_sext<64,50>(res_18_V_write_assign_fu_400_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_19_fu_420_p1() {
    sext_ln728_19_fu_420_p1 = esl_sext<64,50>(res_19_V_write_assign_fu_412_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_1_fu_204_p1() {
    sext_ln728_1_fu_204_p1 = esl_sext<64,50>(res_1_V_write_assign_fu_196_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_2_fu_216_p1() {
    sext_ln728_2_fu_216_p1 = esl_sext<64,50>(res_2_V_write_assign_fu_208_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_3_fu_228_p1() {
    sext_ln728_3_fu_228_p1 = esl_sext<64,50>(res_3_V_write_assign_fu_220_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_4_fu_240_p1() {
    sext_ln728_4_fu_240_p1 = esl_sext<64,50>(res_4_V_write_assign_fu_232_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_5_fu_252_p1() {
    sext_ln728_5_fu_252_p1 = esl_sext<64,50>(res_5_V_write_assign_fu_244_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_6_fu_264_p1() {
    sext_ln728_6_fu_264_p1 = esl_sext<64,50>(res_6_V_write_assign_fu_256_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_7_fu_276_p1() {
    sext_ln728_7_fu_276_p1 = esl_sext<64,50>(res_7_V_write_assign_fu_268_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_8_fu_288_p1() {
    sext_ln728_8_fu_288_p1 = esl_sext<64,50>(res_8_V_write_assign_fu_280_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_9_fu_300_p1() {
    sext_ln728_9_fu_300_p1 = esl_sext<64,50>(res_9_V_write_assign_fu_292_p3.read());
}

void linear_ap_fixed_ap_fixed_64_16_5_3_0_linear_config21_s::thread_sext_ln728_fu_192_p1() {
    sext_ln728_fu_192_p1 = esl_sext<64,50>(res_0_V_write_assign_fu_184_p3.read());
}

}

